my $f = "f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_, r_a_ts_0_, r_a_ts_1_, r_a_us_0_, r_a_us_1_)";
my $info = [
  [
    ["r_a_f", "$f"]
  ], [
    ["r_a_dfdrs",    "diff($f, r_a_rs)"],
    ["r_a_dfdz",     "diff($f, r_a_z)"],
    ["r_a_dfdxt",    "diff($f, r_a_xt)"],
    ["r_a_dfdxs_0_", "diff($f, r_a_xs_0_)"],
    ["r_a_dfdxs_1_", "diff($f, r_a_xs_1_)"],
    ["r_a_dfdts_0_", "diff($f, r_a_ts_0_)"],
    ["r_a_dfdts_1_", "diff($f, r_a_ts_1_)"],
    ["r_a_dfdus_0_", "diff($f, r_a_us_0_)"],
    ["r_a_dfdus_1_", "diff($f, r_a_us_1_)"]
  ], [
    ["r_a_d2fdrs2",     "diff($f, r_a_rs\$2)"],
    ["r_a_d2fdrsz",     "diff($f, r_a_rs, r_a_z)"],
    ["r_a_d2fdrsxt",    "diff($f, r_a_rs, r_a_xt)"],
    ["r_a_d2fdrsxs_0_", "diff($f, r_a_rs, r_a_xs_0_)"],
    ["r_a_d2fdrsxs_1_", "diff($f, r_a_rs, r_a_xs_1_)"],
    ["r_a_d2fdrsts_0_", "diff($f, r_a_rs, r_a_ts_0_)"],
    ["r_a_d2fdrsts_1_", "diff($f, r_a_rs, r_a_ts_1_)"],
    ["r_a_d2fdrsus_0_", "diff($f, r_a_rs, r_a_us_0_)"],
    ["r_a_d2fdrsus_1_", "diff($f, r_a_rs, r_a_us_1_)"],
    ["r_a_d2fdz2",      "diff($f, r_a_z\$2)"],
    ["r_a_d2fdzxt",     "diff($f, r_a_z, r_a_xt)"],
    ["r_a_d2fdzxs_0_",  "diff($f, r_a_z, r_a_xs_0_)"],
    ["r_a_d2fdzxs_1_",  "diff($f, r_a_z, r_a_xs_1_)"],
    ["r_a_d2fdzts_0_",  "diff($f, r_a_z, r_a_ts_0_)"],
    ["r_a_d2fdzts_1_",  "diff($f, r_a_z, r_a_ts_1_)"],
    ["r_a_d2fdzus_0_",  "diff($f, r_a_z, r_a_us_0_)"],
    ["r_a_d2fdzus_1_",  "diff($f, r_a_z, r_a_us_1_)"],
    ["r_a_d2fdxt2",     "diff($f, r_a_xt\$2)"],
    ["r_a_d2fdxtxs_0_", "diff($f, r_a_xt, r_a_xs_0_)"],
    ["r_a_d2fdxtxs_1_", "diff($f, r_a_xt, r_a_xs_1_)"],
    ["r_a_d2fdxtts_0_", "diff($f, r_a_xt, r_a_ts_0_)"],
    ["r_a_d2fdxtts_1_", "diff($f, r_a_xt, r_a_ts_1_)"],
    ["r_a_d2fdxtus_0_", "diff($f, r_a_xt, r_a_us_0_)"],
    ["r_a_d2fdxtus_1_", "diff($f, r_a_xt, r_a_us_1_)"],
    ["r_a_d2fdxs2_0_",  "diff($f, r_a_xs_0_\$2)"],
    ["r_a_d2fdxs2_1_",  "diff($f, r_a_xs_0_, r_a_xs_1_)"],
    ["r_a_d2fdxs2_2_",  "diff($f, r_a_xs_1_\$2)"],
    ["r_a_d2fdxsts_0_", "diff($f, r_a_xs_0_, r_a_ts_0_)"],
    ["r_a_d2fdxsts_1_", "diff($f, r_a_xs_0_, r_a_ts_1_)"],
    ["r_a_d2fdxsts_2_", "diff($f, r_a_xs_1_, r_a_ts_0_)"],
    ["r_a_d2fdxsts_3_", "diff($f, r_a_xs_1_, r_a_ts_1_)"],
    ["r_a_d2fdxsus_0_", "diff($f, r_a_xs_0_, r_a_us_0_)"],
    ["r_a_d2fdxsus_1_", "diff($f, r_a_xs_0_, r_a_us_1_)"],
    ["r_a_d2fdxsus_2_", "diff($f, r_a_xs_1_, r_a_us_0_)"],
    ["r_a_d2fdxsus_3_", "diff($f, r_a_xs_1_, r_a_us_1_)"],
    ["r_a_d2fdts2_0_",  "diff($f, r_a_ts_0_\$2)"],
    ["r_a_d2fdts2_1_",  "diff($f, r_a_ts_0_, r_a_ts_1_)"],
    ["r_a_d2fdts2_2_",  "diff($f, r_a_ts_1_\$2)"],
    ["r_a_d2fdtsus_0_", "diff($f, r_a_ts_0_, r_a_us_0_)"],
    ["r_a_d2fdtsus_1_", "diff($f, r_a_ts_0_, r_a_us_1_)"],
    ["r_a_d2fdtsus_2_", "diff($f, r_a_ts_1_, r_a_us_0_)"],
    ["r_a_d2fdtsus_3_", "diff($f, r_a_ts_1_, r_a_us_1_)"],
    ["r_a_d2fdus2_0_",  "diff($f, r_a_us_0_\$2)"],
    ["r_a_d2fdus2_1_",  "diff($f, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d2fdus2_2_",  "diff($f, r_a_us_1_\$2)"]
  ], [
    ["r_a_d3fdrs3",       "diff($f, r_a_rs\$3)"],
    ["r_a_d3fdrs2z",      "diff($f, r_a_rs\$2, r_a_z)"],
    ["r_a_d3fdrsz2",      "diff($f, r_a_rs, r_a_z\$2)"],
    ["r_a_d3fdrszxt",     "diff($f, r_a_rs, r_a_z, r_a_xt)"],
    ["r_a_d3fdrszxs_0_",  "diff($f, r_a_rs, r_a_z, r_a_xs_0_)"],
    ["r_a_d3fdrszxs_1_",  "diff($f, r_a_rs, r_a_z, r_a_xs_1_)"],
    ["r_a_d3fdrszts_0_",  "diff($f, r_a_rs, r_a_z, r_a_ts_0_)"],
    ["r_a_d3fdrszts_1_",  "diff($f, r_a_rs, r_a_z, r_a_ts_1_)"],
    ["r_a_d3fdrszus_0_",  "diff($f, r_a_rs, r_a_z, r_a_us_0_)"],
    ["r_a_d3fdrszus_1_",  "diff($f, r_a_rs, r_a_z, r_a_us_1_)"],
    ["r_a_d3fdrs2xt",     "diff($f, r_a_rs\$2, r_a_xt)"],
    ["r_a_d3fdrsxt2",     "diff($f, r_a_rs, r_a_xt\$2)"],
    ["r_a_d3fdrsxtxs_0_", "diff($f, r_a_rs, r_a_xt, r_a_xs_0_)"],
    ["r_a_d3fdrsxtxs_1_", "diff($f, r_a_rs, r_a_xt, r_a_xs_1_)"],
    ["r_a_d3fdrsxtts_0_", "diff($f, r_a_rs, r_a_xt, r_a_ts_0_)"],
    ["r_a_d3fdrsxtts_1_", "diff($f, r_a_rs, r_a_xt, r_a_ts_1_)"],
    ["r_a_d3fdrsxtus_0_", "diff($f, r_a_rs, r_a_xt, r_a_us_0_)"],
    ["r_a_d3fdrsxtus_1_", "diff($f, r_a_rs, r_a_xt, r_a_us_1_)"],
    ["r_a_d3fdrs2xs_0_",  "diff($f, r_a_rs\$2, r_a_xs_0_)"],
    ["r_a_d3fdrs2xs_1_",  "diff($f, r_a_rs\$2, r_a_xs_1_)"],
    ["r_a_d3fdrsxs2_0_",  "diff($f, r_a_rs, r_a_xs_0_\$2)"],
    ["r_a_d3fdrsxs2_1_",  "diff($f, r_a_rs, r_a_xs_0_, r_a_xs_1_)"],
    ["r_a_d3fdrsxs2_2_",  "diff($f, r_a_rs, r_a_xs_1_\$2)"],
    ["r_a_d3fdrsxsts_0_", "diff($f, r_a_rs, r_a_xs_0_, r_a_ts_0_)"],
    ["r_a_d3fdrsxsts_1_", "diff($f, r_a_rs, r_a_xs_0_, r_a_ts_1_)"],
    ["r_a_d3fdrsxsts_2_", "diff($f, r_a_rs, r_a_xs_1_, r_a_ts_0_)"],
    ["r_a_d3fdrsxsts_3_", "diff($f, r_a_rs, r_a_xs_1_, r_a_ts_1_)"],
    ["r_a_d3fdrsxsus_0_", "diff($f, r_a_rs, r_a_xs_0_, r_a_us_0_)"],
    ["r_a_d3fdrsxsus_1_", "diff($f, r_a_rs, r_a_xs_0_, r_a_us_1_)"],
    ["r_a_d3fdrsxsus_2_", "diff($f, r_a_rs, r_a_xs_1_, r_a_us_0_)"],
    ["r_a_d3fdrsxsus_3_", "diff($f, r_a_rs, r_a_xs_1_, r_a_us_1_)"],
    ["r_a_d3fdrs2ts_0_",  "diff($f, r_a_rs\$2, r_a_ts_0_)"],
    ["r_a_d3fdrs2ts_1_",  "diff($f, r_a_rs\$2, r_a_ts_1_)"],
    ["r_a_d3fdrsts2_0_",  "diff($f, r_a_rs, r_a_ts_0_\$2)"],
    ["r_a_d3fdrsts2_1_",  "diff($f, r_a_rs, r_a_ts_0_, r_a_ts_1_)"],
    ["r_a_d3fdrsts2_2_",  "diff($f, r_a_rs, r_a_ts_1_\$2)"],
    ["r_a_d3fdrstsus_0_", "diff($f, r_a_rs, r_a_ts_0_, r_a_us_0_)"],
    ["r_a_d3fdrstsus_1_", "diff($f, r_a_rs, r_a_ts_0_, r_a_us_1_)"],
    ["r_a_d3fdrstsus_2_", "diff($f, r_a_rs, r_a_ts_1_, r_a_us_0_)"],
    ["r_a_d3fdrstsus_3_", "diff($f, r_a_rs, r_a_ts_1_, r_a_us_1_)"],
    ["r_a_d3fdrs2us_0_",  "diff($f, r_a_rs\$2, r_a_us_0_)"],
    ["r_a_d3fdrs2us_1_",  "diff($f, r_a_rs\$2, r_a_us_1_)"],
    ["r_a_d3fdrsus2_0_",  "diff($f, r_a_rs, r_a_us_0_\$2)"],
    ["r_a_d3fdrsus2_1_",  "diff($f, r_a_rs, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d3fdrsus2_2_",  "diff($f, r_a_rs, r_a_us_1_\$2)"],
    ["r_a_d3fdz3",        "diff($f, r_a_z\$3)"],
    ["r_a_d3fdz2xt",      "diff($f, r_a_z\$2, r_a_xt)"],
    ["r_a_d3fdzxt2",      "diff($f, r_a_z, r_a_xt\$2)"],
    ["r_a_d3fdzxtxs_0_",  "diff($f, r_a_z, r_a_xt, r_a_xs_0_)"],
    ["r_a_d3fdzxtxs_1_",  "diff($f, r_a_z, r_a_xt, r_a_xs_1_)"],
    ["r_a_d3fdzxtts_0_",  "diff($f, r_a_z, r_a_xt, r_a_ts_0_)"],
    ["r_a_d3fdzxtts_1_",  "diff($f, r_a_z, r_a_xt, r_a_ts_1_)"],
    ["r_a_d3fdzxtus_0_",  "diff($f, r_a_z, r_a_xt, r_a_us_0_)"],
    ["r_a_d3fdzxtus_1_",  "diff($f, r_a_z, r_a_xt, r_a_us_1_)"],
    ["r_a_d3fdz2xs_0_",   "diff($f, r_a_z\$2, r_a_xs_0_)"],
    ["r_a_d3fdz2xs_1_",   "diff($f, r_a_z\$2, r_a_xs_1_)"],
    ["r_a_d3fdzxs2_0_",   "diff($f, r_a_z, r_a_xs_0_\$2)"],
    ["r_a_d3fdzxs2_1_",   "diff($f, r_a_z, r_a_xs_0_, r_a_xs_1_)"],
    ["r_a_d3fdzxs2_2_",   "diff($f, r_a_z, r_a_xs_1_\$2)"],
    ["r_a_d3fdzxsts_0_",  "diff($f, r_a_z, r_a_xs_0_, r_a_ts_0_)"],
    ["r_a_d3fdzxsts_1_",  "diff($f, r_a_z, r_a_xs_0_, r_a_ts_1_)"],
    ["r_a_d3fdzxsts_2_",  "diff($f, r_a_z, r_a_xs_1_, r_a_ts_0_)"],
    ["r_a_d3fdzxsts_3_",  "diff($f, r_a_z, r_a_xs_1_, r_a_ts_1_)"],
    ["r_a_d3fdzxsus_0_",  "diff($f, r_a_z, r_a_xs_0_, r_a_us_0_)"],
    ["r_a_d3fdzxsus_1_",  "diff($f, r_a_z, r_a_xs_0_, r_a_us_1_)"],
    ["r_a_d3fdzxsus_2_",  "diff($f, r_a_z, r_a_xs_1_, r_a_us_0_)"],
    ["r_a_d3fdzxsus_3_",  "diff($f, r_a_z, r_a_xs_1_, r_a_us_1_)"],
    ["r_a_d3fdz2ts_0_",   "diff($f, r_a_z\$2, r_a_ts_0_)"],
    ["r_a_d3fdz2ts_1_",   "diff($f, r_a_z\$2, r_a_ts_1_)"],
    ["r_a_d3fdzts2_0_",   "diff($f, r_a_z, r_a_ts_0_\$2)"],
    ["r_a_d3fdzts2_1_",   "diff($f, r_a_z, r_a_ts_0_, r_a_ts_1_)"],
    ["r_a_d3fdzts2_2_",   "diff($f, r_a_z, r_a_ts_1_\$2)"],
    ["r_a_d3fdztsus_0_",  "diff($f, r_a_z, r_a_ts_0_, r_a_us_0_)"],
    ["r_a_d3fdztsus_1_",  "diff($f, r_a_z, r_a_ts_0_, r_a_us_1_)"],
    ["r_a_d3fdztsus_2_",  "diff($f, r_a_z, r_a_ts_1_, r_a_us_0_)"],
    ["r_a_d3fdztsus_3_",  "diff($f, r_a_z, r_a_ts_1_, r_a_us_1_)"],
    ["r_a_d3fdz2us_0_",   "diff($f, r_a_z\$2, r_a_us_0_)"],
    ["r_a_d3fdz2us_1_",   "diff($f, r_a_z\$2, r_a_us_1_)"],
    ["r_a_d3fdzus2_0_",   "diff($f, r_a_z, r_a_us_0_\$2)"],
    ["r_a_d3fdzus2_1_",   "diff($f, r_a_z, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d3fdzus2_2_",   "diff($f, r_a_z, r_a_us_1_\$2)"],
    ["r_a_d3fdxt3",       "diff($f, r_a_xt\$3)"],
    ["r_a_d3fdxt2xs_0_",  "diff($f, r_a_xt\$2, r_a_xs_0_)"],
    ["r_a_d3fdxt2xs_1_",  "diff($f, r_a_xt\$2, r_a_xs_1_)"],
    ["r_a_d3fdxtxs2_0_",  "diff($f, r_a_xt, r_a_xs_0_\$2)"],
    ["r_a_d3fdxtxs2_1_",  "diff($f, r_a_xt, r_a_xs_0_, r_a_xs_1_)"],
    ["r_a_d3fdxtxs2_2_",  "diff($f, r_a_xt, r_a_xs_1_\$2)"],
    ["r_a_d3fdxtxsts_0_", "diff($f, r_a_xt, r_a_xs_0_, r_a_ts_0_)"],
    ["r_a_d3fdxtxsts_1_", "diff($f, r_a_xt, r_a_xs_0_, r_a_ts_1_)"],
    ["r_a_d3fdxtxsts_2_", "diff($f, r_a_xt, r_a_xs_1_, r_a_ts_0_)"],
    ["r_a_d3fdxtxsts_3_", "diff($f, r_a_xt, r_a_xs_1_, r_a_ts_1_)"],
    ["r_a_d3fdxtxsus_0_", "diff($f, r_a_xt, r_a_xs_0_, r_a_us_0_)"],
    ["r_a_d3fdxtxsus_1_", "diff($f, r_a_xt, r_a_xs_0_, r_a_us_1_)"],
    ["r_a_d3fdxtxsus_2_", "diff($f, r_a_xt, r_a_xs_1_, r_a_us_0_)"],
    ["r_a_d3fdxtxsus_3_", "diff($f, r_a_xt, r_a_xs_1_, r_a_us_1_)"],
    ["r_a_d3fdxt2ts_0_",  "diff($f, r_a_xt\$2, r_a_ts_0_)"],
    ["r_a_d3fdxt2ts_1_",  "diff($f, r_a_xt\$2, r_a_ts_1_)"],
    ["r_a_d3fdxtts2_0_",  "diff($f, r_a_xt, r_a_ts_0_\$2)"],
    ["r_a_d3fdxtts2_1_",  "diff($f, r_a_xt, r_a_ts_0_, r_a_ts_1_)"],
    ["r_a_d3fdxtts2_2_",  "diff($f, r_a_xt, r_a_ts_1_\$2)"],
    ["r_a_d3fdxttsus_0_", "diff($f, r_a_xt, r_a_ts_0_, r_a_us_0_)"],
    ["r_a_d3fdxttsus_1_", "diff($f, r_a_xt, r_a_ts_0_, r_a_us_1_)"],
    ["r_a_d3fdxttsus_2_", "diff($f, r_a_xt, r_a_ts_1_, r_a_us_0_)"],
    ["r_a_d3fdxttsus_3_", "diff($f, r_a_xt, r_a_ts_1_, r_a_us_1_)"],
    ["r_a_d3fdxt2us_0_",  "diff($f, r_a_xt\$2, r_a_us_0_)"],
    ["r_a_d3fdxt2us_1_",  "diff($f, r_a_xt\$2, r_a_us_1_)"],
    ["r_a_d3fdxtus2_0_",  "diff($f, r_a_xt, r_a_us_0_\$2)"],
    ["r_a_d3fdxtus2_1_",  "diff($f, r_a_xt, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d3fdxtus2_2_",  "diff($f, r_a_xt, r_a_us_1_\$2)"],
    ["r_a_d3fdxs3_0_",    "diff($f, r_a_xs_0_\$3)"],
    ["r_a_d3fdxs3_1_",    "diff($f, r_a_xs_0_\$2, r_a_xs_1_)"],
    ["r_a_d3fdxs3_2_",    "diff($f, r_a_xs_0_, r_a_xs_1_\$2)"],
    ["r_a_d3fdxs3_3_",    "diff($f, r_a_xs_1_\$3)"],
    ["r_a_d3fdxs2ts_0_",  "diff($f, r_a_xs_0_\$2, r_a_ts_0_)"],
    ["r_a_d3fdxs2ts_1_",  "diff($f, r_a_xs_0_\$2, r_a_ts_1_)"],
    ["r_a_d3fdxs2ts_2_",  "diff($f, r_a_xs_0_, r_a_xs_1_, r_a_ts_0_)"],
    ["r_a_d3fdxs2ts_3_",  "diff($f, r_a_xs_0_, r_a_xs_1_, r_a_ts_1_)"],
    ["r_a_d3fdxs2ts_4_",  "diff($f, r_a_xs_1_\$2, r_a_ts_0_)"],
    ["r_a_d3fdxs2ts_5_",  "diff($f, r_a_xs_1_\$2, r_a_ts_1_)"],
    ["r_a_d3fdxs2us_0_",  "diff($f, r_a_xs_0_\$2, r_a_us_0_)"],
    ["r_a_d3fdxs2us_1_",  "diff($f, r_a_xs_0_\$2, r_a_us_1_)"],
    ["r_a_d3fdxs2us_2_",  "diff($f, r_a_xs_0_, r_a_xs_1_, r_a_us_0_)"],
    ["r_a_d3fdxs2us_3_",  "diff($f, r_a_xs_0_, r_a_xs_1_, r_a_us_1_)"],
    ["r_a_d3fdxs2us_4_",  "diff($f, r_a_xs_1_\$2, r_a_us_0_)"],
    ["r_a_d3fdxs2us_5_",  "diff($f, r_a_xs_1_\$2, r_a_us_1_)"],
    ["r_a_d3fdxsts2_0_",  "diff($f, r_a_xs_0_, r_a_ts_0_\$2)"],
    ["r_a_d3fdxsts2_1_",  "diff($f, r_a_xs_0_, r_a_ts_0_, r_a_ts_1_)"],
    ["r_a_d3fdxsts2_2_",  "diff($f, r_a_xs_0_, r_a_ts_1_\$2)"],
    ["r_a_d3fdxsts2_3_",  "diff($f, r_a_xs_1_, r_a_ts_0_\$2)"],
    ["r_a_d3fdxsts2_4_",  "diff($f, r_a_xs_1_, r_a_ts_0_, r_a_ts_1_)"],
    ["r_a_d3fdxsts2_5_",  "diff($f, r_a_xs_1_, r_a_ts_1_\$2)"],
    ["r_a_d3fdxstsus_0_", "diff($f, r_a_xs_0_, r_a_ts_0_, r_a_us_0_)"],
    ["r_a_d3fdxstsus_1_", "diff($f, r_a_xs_0_, r_a_ts_0_, r_a_us_1_)"],
    ["r_a_d3fdxstsus_2_", "diff($f, r_a_xs_0_, r_a_ts_1_, r_a_us_0_)"],
    ["r_a_d3fdxstsus_3_", "diff($f, r_a_xs_0_, r_a_ts_1_, r_a_us_1_)"],
    ["r_a_d3fdxstsus_4_", "diff($f, r_a_xs_1_, r_a_ts_0_, r_a_us_0_)"],
    ["r_a_d3fdxstsus_5_", "diff($f, r_a_xs_1_, r_a_ts_0_, r_a_us_1_)"],
    ["r_a_d3fdxstsus_6_", "diff($f, r_a_xs_1_, r_a_ts_1_, r_a_us_0_)"],
    ["r_a_d3fdxstsus_7_", "diff($f, r_a_xs_1_, r_a_ts_1_, r_a_us_1_)"],
    ["r_a_d3fdxsus2_0_",  "diff($f, r_a_xs_0_, r_a_us_0_\$2)"],
    ["r_a_d3fdxsus2_1_",  "diff($f, r_a_xs_0_, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d3fdxsus2_2_",  "diff($f, r_a_xs_0_, r_a_us_1_\$2)"],
    ["r_a_d3fdxsus2_3_",  "diff($f, r_a_xs_1_, r_a_us_0_\$2)"],
    ["r_a_d3fdxsus2_4_",  "diff($f, r_a_xs_1_, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d3fdxsus2_5_",  "diff($f, r_a_xs_1_, r_a_us_1_\$2)"],
    ["r_a_d3fdts3_0_",    "diff($f, r_a_ts_0_\$3)"],
    ["r_a_d3fdts3_1_",    "diff($f, r_a_ts_0_\$2, r_a_ts_1_)"],
    ["r_a_d3fdts3_2_",    "diff($f, r_a_ts_0_, r_a_ts_1_\$2)"],
    ["r_a_d3fdts3_3_",    "diff($f, r_a_ts_1_\$3)"],
    ["r_a_d3fdts2us_0_",  "diff($f, r_a_ts_0_\$2, r_a_us_0_)"],
    ["r_a_d3fdts2us_1_",  "diff($f, r_a_ts_0_\$2, r_a_us_1_)"],
    ["r_a_d3fdts2us_2_",  "diff($f, r_a_ts_0_, r_a_ts_1_, r_a_us_0_)"],
    ["r_a_d3fdts2us_3_",  "diff($f, r_a_ts_0_, r_a_ts_1_, r_a_us_1_)"],
    ["r_a_d3fdts2us_4_",  "diff($f, r_a_ts_1_\$2, r_a_us_0_)"],
    ["r_a_d3fdts2us_5_",  "diff($f, r_a_ts_1_\$2, r_a_us_1_)"],
    ["r_a_d3fdtsus2_0_",  "diff($f, r_a_ts_0_, r_a_us_0_\$2)"],
    ["r_a_d3fdtsus2_1_",  "diff($f, r_a_ts_0_, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d3fdtsus2_2_",  "diff($f, r_a_ts_0_, r_a_us_1_\$2)"],
    ["r_a_d3fdtsus2_3_",  "diff($f, r_a_ts_1_, r_a_us_0_\$2)"],
    ["r_a_d3fdtsus2_4_",  "diff($f, r_a_ts_1_, r_a_us_0_, r_a_us_1_)"],
    ["r_a_d3fdtsus2_5_",  "diff($f, r_a_ts_1_, r_a_us_1_\$2)"],
    ["r_a_d3fdus3_0_",    "diff($f, r_a_us_0_\$3)"],
    ["r_a_d3fdus3_1_",    "diff($f, r_a_us_0_\$2, r_a_us_1_)"],
    ["r_a_d3fdus3_2_",    "diff($f, r_a_us_0_, r_a_us_1_\$2)"],
    ["r_a_d3fdus3_3_",    "diff($f, r_a_us_1_\$3)"]
  ]
];
