my $info = [
  [
    ['r_a_f',             'f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_)']
  ], [
    ['r_a_dfdrs',         'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs)'],
    ['r_a_dfdz',          'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z)'],
    ['r_a_dfdxt',         'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt)'],
    ['r_a_dfdxs_0_',      'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_0_)'],
    ['r_a_dfdxs_1_',      'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_1_)']
  ], [
    ['r_a_d2fdrs2',       'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs$2)'],
    ['r_a_d2fdrsz',       'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_z)'],
    ['r_a_d2fdrsxt',      'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xt)'],
    ['r_a_d2fdrsxs_0_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xs_0_)'],
    ['r_a_d2fdrsxs_1_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xs_1_)'],
    ['r_a_d2fdz2',        'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z$2)'],
    ['r_a_d2fdzxt',       'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xt)'],
    ['r_a_d2fdzxs_0_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xs_0_)'],
    ['r_a_d2fdzxs_1_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xs_1_)'],
    ['r_a_d2fdxt2',       'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt$2)'],
    ['r_a_d2fdxtxs_0_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt, r_a_xs_0_)'],
    ['r_a_d2fdxtxs_1_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt, r_a_xs_1_)'],
    ['r_a_d2fdxs2_0_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_0_$2)'],
    ['r_a_d2fdxs2_1_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_0_, r_a_xs_1_)'],
    ['r_a_d2fdxs2_2_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_1_$2)']
  ], [
    ['r_a_d3fdrs3',       'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs$3)'],
    ['r_a_d3fdrs2z',      'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs$2, r_a_z)'],
    ['r_a_d3fdrsz2',      'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_z$2)'],
    ['r_a_d3fdrszxt',     'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_z, r_a_xt)'],
    ['r_a_d3fdrszxs_0_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_z, r_a_xs_0_)'],
    ['r_a_d3fdrszxs_1_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_z, r_a_xs_1_)'],
    ['r_a_d3fdrs2xt',     'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs$2, r_a_xt)'],
    ['r_a_d3fdrsxt2',     'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xt$2)'],
    ['r_a_d3fdrsxtxs_0_', 'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xt, r_a_xs_0_)'],
    ['r_a_d3fdrsxtxs_1_', 'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xt, r_a_xs_1_)'],
    ['r_a_d3fdrs2xs_0_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs$2, r_a_xs_0_)'],
    ['r_a_d3fdrs2xs_1_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs$2, r_a_xs_1_)'],
    ['r_a_d3fdrsxs2_0_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xs_0_$2)'],
    ['r_a_d3fdrsxs2_1_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xs_0_, r_a_xs_1_)'],
    ['r_a_d3fdrsxs2_2_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_rs, r_a_xs_1_$2)'],
    ['r_a_d3fdz3',        'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z$3)'],
    ['r_a_d3fdz2xt',      'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z$2, r_a_xt)'],
    ['r_a_d3fdzxt2',      'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xt$2)'],
    ['r_a_d3fdzxtxs_0_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xt, r_a_xs_0_)'],
    ['r_a_d3fdzxtxs_1_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xt, r_a_xs_1_)'],
    ['r_a_d3fdz2xs_0_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z$2, r_a_xs_0_)'],
    ['r_a_d3fdz2xs_1_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z$2, r_a_xs_1_)'],
    ['r_a_d3fdzxs2_0_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xs_0_$2)'],
    ['r_a_d3fdzxs2_1_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xs_0_, r_a_xs_1_)'],
    ['r_a_d3fdzxs2_2_',   'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_z, r_a_xs_1_$2)'],
    ['r_a_d3fdxt3',       'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt$3)'],
    ['r_a_d3fdxt2xs_0_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt$2, r_a_xs_0_)'],
    ['r_a_d3fdxt2xs_1_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt$2, r_a_xs_1_)'],
    ['r_a_d3fdxtxs2_0_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt, r_a_xs_0_$2)'],
    ['r_a_d3fdxtxs2_1_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt, r_a_xs_0_, r_a_xs_1_)'],
    ['r_a_d3fdxtxs2_2_',  'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xt, r_a_xs_1_$2)'],
    ['r_a_d3fdxs3_0_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_0_$3)'],
    ['r_a_d3fdxs3_1_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_0_$2, r_a_xs_1_)'],
    ['r_a_d3fdxs3_2_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_0_, r_a_xs_1_$2)'],
    ['r_a_d3fdxs3_3_',    'diff(f(r_a_rs, r_a_z, r_a_xt, r_a_xs_0_, r_a_xs_1_), r_a_xs_1_$3)']
  ]
];
