# Copyright (C) 2019-2020 Xavier Andrade, Alfredo A. Correa

image: debian:stable-backports

variables:
  GIT_SUBMODULE_STRATEGY: recursive

gcc:
    stage: build
    script:
      - time apt update -qq
      - time apt install --no-install-recommends -y -qq autoconf automake make gcc gfortran libtool bzip2 
      - autoreconf -i
      - mkdir build/
      - cd build/
      - export CC=gcc
      - export CFLAGS="-O3 -pipe -Wall"      
      - ../configure --prefix=$HOME
      - make
      - make check
      - make install
      
g++:
    stage: build
    script:
      - time apt update -qq
      - time apt install --no-install-recommends -y -qq autoconf automake make gcc g++ gfortran libtool bzip2 
      - autoreconf -i
      - mkdir build/
      - cd build/
      - export CFLAGS="-O3 -pipe -Wall"
      - export CC=g++
      - ../configure --prefix=$HOME
      - make
      - make check
      - make install


clang++:
    stage: build
    script:
      - time apt update -qq
      - time apt install --no-install-recommends -y -qq autoconf automake make clang gfortran libtool bzip2 
      - autoreconf -i
      - mkdir build/
      - cd build/
      - export CFLAGS="-O3 -pipe -Wall"
      - export CC=clang++
      - ../configure --prefix=$HOME
      - make
      - make check
      - make install
