# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
    - apt update && apt -y install make cmake libgsl-dev
  script: 
    - cmake -H. -Bobjdir -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug
    - cd objdir && make
  after_script:
    - pwd
    - cd objdir && ctest
  artifacts:
    paths:
      - objdir/libxc.so
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"
