/* 
  This file was generated automatically with ../scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  Maple source      : ../maple/gga_x_pbea.mpl
  Type of functional: work_gga_x
*/

void XC(gga_x_pbea_enhance)
  (const XC(func_type) *p, int order, 
   FLOAT x, FLOAT *f, FLOAT *dfdx, FLOAT *d2fdx2, FLOAT *d3fdx3)
{
  double t1, t3, t4, t6, t8, t12;


  t1 = x * x;
  t3 = 0.10e1 + 0.86399408095363255118e-2 * t1;
  t4 = pow(t3, -0.52e0);
  *f = 0.180400e1 - 0.8040e0 * t4;

  if(order < 1) return;

  t6 = pow(t3, -0.152e1);
  *dfdx = 0.72243729073018939401e-2 * t6 * x;

  if(order < 2) return;

  t8 = pow(t3, -0.252e1);
  *d2fdx2 = -0.18975118908752291802e-3 * t8 * t1 + 0.72243729073018939401e-2 * t6;

  if(order < 3) return;

  t12 = pow(t3, -0.352e1);
  *d3fdx3 = 0.82627727729668790042e-5 * t12 * t1 * x - 0.56925356726256875406e-3 * t8 * x;

  if(order < 4) return;


}

#define maple2c_order 3
#define maple2c_func  XC(gga_x_pbea_enhance)
