/* 
  This file was generated automatically with ../scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  Maple source      : ../maple/gga_x_herman.mpl
  Type of functional: work_gga_x
*/

void XC(gga_x_herman_enhance)
  (const XC(func_type) *p,  XC(gga_work_x_t) *r)
{
  double t1;


  t1 = r->x * r->x;
  r->f = 0.10e1 + 0.32239839080329392815e-2 * t1;

  if(r->order < 1) return;

  r->dfdx = 0.64479678160658785630e-2 * r->x;

  if(r->order < 2) return;

  r->d2fdx2 = 0.64479678160658785630e-2;

  if(r->order < 3) return;

  r->d3fdx3 = 0;

  if(r->order < 4) return;


}

#define maple2c_order 3
#define maple2c_func  XC(gga_x_herman_enhance)
