/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2020 (X86 64 LINUX)
  Maple source      : ./maple/lda_exc/lda_c_chachiyo_mod.mpl
  Type of functional: lda_exc
*/

#define maple2c_order 4
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC | XC_FLAGS_I_HAVE_KXC | XC_FLAGS_I_HAVE_LXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho , double *zk LDA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t5, t7, t8, t9, t10;
  double t13, t14, t16, t17, t18, t19, t22, t23;
  double t24, t25, t28, t31, t32, t36, t37, t40;
  double t41;

#ifndef XC_DONT_COMPILE_VXC
  double t43, t47, t50, t52, t53, t58, t60, t63;

#ifndef XC_DONT_COMPILE_FXC
  double t70, t74, t77, t78, t79, t80, t82, t83;
  double t84, t88, t89, t91, t93, t94, t97;

#ifndef XC_DONT_COMPILE_KXC
  double t103, t106, t111, t115, t116, t117, t118, t119;
  double t123, t124, t125, t131, t133, t139, t143;

#ifndef XC_DONT_COMPILE_LXC
  double t150, t153, t158, t163, t165, t168, t169, t172;
  double t173, t175, t178, t191, t195, t197;
#endif

#endif

#endif

#endif

#endif


  lda_c_chachiyo_mod_params *params;

  assert(p->params != NULL);
  params = (lda_c_chachiyo_mod_params * )(p->params);

  t1 = M_CBRT3;
  t2 = t1 * t1;
  t3 = params->bp * t2;
  t5 = POW_1_3(0.1e1 / M_PI);
  t7 = M_CBRT4;
  t8 = 0.1e1 / t5 * t7;
  t9 = POW_1_3(rho[0]);
  t10 = t8 * t9;
  t13 = params->bp * t1;
  t14 = t5 * t5;
  t16 = t7 * t7;
  t17 = 0.1e1 / t14 * t16;
  t18 = t9 * t9;
  t19 = t17 * t18;
  t22 = 0.1e1 + t3 * t10 / 0.3e1 + t13 * t19 / 0.3e1;
  t23 = log(t22);
  t24 = params->ap * t23;
  t25 = params->bf * t2;
  t28 = params->bf * t1;
  t31 = 0.1e1 + t25 * t10 / 0.3e1 + t28 * t19 / 0.3e1;
  t32 = log(t31);
  t36 = my_piecewise3(0.1e1 <= p->zeta_threshold, 0, 1);
  t37 = t36 * t36;
  t40 = -0.2e1 * t37 * t36 + 0.2e1;
  t41 = (params->af * t32 - t24) * t40;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = t24 + t41;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t43 = t8 / t18;
  t47 = t17 / t9;
  t50 = t3 * t43 / 0.9e1 + 0.2e1 / 0.9e1 * t13 * t47;
  t52 = 0.1e1 / t22;
  t53 = params->ap * t50 * t52;
  t58 = t25 * t43 / 0.9e1 + 0.2e1 / 0.9e1 * t28 * t47;
  t60 = 0.1e1 / t31;
  t63 = (params->af * t58 * t60 - t53) * t40;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t24 + t41 + rho[0] * (t53 + t63);

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t70 = t8 / t18 / rho[0];
  t74 = t17 / t9 / rho[0];
  t77 = -0.2e1 / 0.27e2 * t13 * t74 - 0.2e1 / 0.27e2 * t3 * t70;
  t78 = params->ap * t77;
  t79 = t78 * t52;
  t80 = t50 * t50;
  t82 = t22 * t22;
  t83 = 0.1e1 / t82;
  t84 = params->ap * t80 * t83;
  t88 = -0.2e1 / 0.27e2 * t25 * t70 - 0.2e1 / 0.27e2 * t28 * t74;
  t89 = params->af * t88;
  t91 = t58 * t58;
  t93 = t31 * t31;
  t94 = 0.1e1 / t93;
  t97 = (-params->af * t91 * t94 + t89 * t60 - t79 + t84) * t40;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * t53 + 0.2e1 * t63 + rho[0] * (t79 - t84 + t97);

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t103 = rho[0] * rho[0];
  t106 = t8 / t18 / t103;
  t111 = t17 / t9 / t103;
  t115 = params->ap * (0.10e2 / 0.81e2 * t3 * t106 + 0.8e1 / 0.81e2 * t13 * t111);
  t116 = t115 * t52;
  t117 = t83 * t50;
  t118 = t78 * t117;
  t119 = 0.3e1 * t118;
  t123 = 0.1e1 / t82 / t22;
  t124 = params->ap * t80 * t50 * t123;
  t125 = 0.2e1 * t124;
  t131 = params->af * (0.10e2 / 0.81e2 * t25 * t106 + 0.8e1 / 0.81e2 * t28 * t111);
  t133 = t94 * t58;
  t139 = 0.1e1 / t93 / t31;
  t143 = (0.2e1 * params->af * t91 * t58 * t139 + t131 * t60 - 0.3e1 * t89 * t133 - t116 + t119 - t125) * t40;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = 0.3e1 * t79 - 0.3e1 * t84 + 0.3e1 * t97 + rho[0] * (t116 - t119 + t125 + t143);

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t150 = t103 * rho[0];
  t153 = t8 / t18 / t150;
  t158 = t17 / t9 / t150;
  t163 = params->ap * (-0.80e2 / 0.243e3 * t3 * t153 - 0.56e2 / 0.243e3 * t13 * t158) * t52;
  t165 = 0.4e1 * t115 * t117;
  t168 = 0.12e2 * t78 * t123 * t80;
  t169 = t77 * t77;
  t172 = 0.3e1 * params->ap * t169 * t83;
  t173 = t80 * t80;
  t175 = t82 * t82;
  t178 = 0.6e1 * params->ap * t173 / t175;
  t191 = t88 * t88;
  t195 = t91 * t91;
  t197 = t93 * t93;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = 0.4e1 * t116 - 0.12e2 * t118 + 0.8e1 * t124 + 0.4e1 * t143 + rho[0] * (t163 - t165 + t168 - t172 - t178 + (params->af * (-0.80e2 / 0.243e3 * t25 * t153 - 0.56e2 / 0.243e3 * t28 * t158) * t60 - 0.4e1 * t131 * t133 + 0.12e2 * t89 * t139 * t91 - 0.3e1 * params->af * t191 * t94 - 0.6e1 * params->af * t195 / t197 - t163 + t165 - t168 + t172 + t178) * t40);

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho , double *zk LDA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t5, t7, t8, t9, t10;
  double t11, t14, t15, t17, t18, t19, t20, t23;
  double t24, t25, t26, t29, t32, t33, t35, t36;
  double t37, t38, t39, t40, t41, t42, t43, t44;
  double t45, t46, t47, t48, t50, t51, t54, t55;

#ifndef XC_DONT_COMPILE_VXC
  double t57, t61, t64, t66, t67, t72, t74, t76;
  double t77, t78, t79, t80, t81, t82, t83, t86;
  double t87, t88, t91, t93, t94, t95, t98, t101;
  double t102, t105, t107, t108, t109;

#ifndef XC_DONT_COMPILE_FXC
  double t112, t113, t117, t121, t124, t125, t126, t127;
  double t129, t130, t131, t135, t136, t138, t140, t141;
  double t143, t144, t145, t146, t147, t148, t149, t150;
  double t151, t153, t154, t157, t158, t159, t161, t165;
  double t167, t168, t171, t175, t177, t178, t179, t183;
  double t185, t186, t188, t191, t195, t196, t199, t203;
  double t205, t206, t211, t212, t213, t214, t215, t219;
  double t223, t224, t227, t231, t233, t234, t235;

#ifndef XC_DONT_COMPILE_KXC
  double t238, t239, t240, t246, t251, t255, t256, t257;
  double t258, t259, t263, t264, t265, t271, t273, t279;
  double t282, t283, t284, t285, t286, t287, t288, t290;
  double t292, t293, t294, t295, t296, t297, t298, t300;
  double t301, t304, t307, t308, t309, t311, t315, t316;
  double t318, t319, t322, t325, t329, t331, t332, t333;
  double t337, t338, t342, t344, t345, t346, t347, t348;
  double t349, t351, t352, t354, t355, t357, t360, t371;
  double t372, t375, t386, t388, t389, t391, t396, t398;
  double t399, t401, t402, t404, t406, t407, t409, t414;
  double t419, t423, t424, t429, t432, t436, t438, t439;
  double t441, t446, t449, t450, t451, t452, t453, t454;
  double t455, t461, t465, t466, t471, t475, t477, t478;
  double t479;

#ifndef XC_DONT_COMPILE_LXC
  double t482, t483, t486, t489, t491, t492, t495, t496;
  double t498, t501, t502, t503, t505, t507, t515, t520;
  double t531, t535, t537, t547, t549, t550, t551, t553;
  double t555, t557, t563, t564, t570, t576, t577, t579;
  double t583, t586, t587, t593, t602, t607, t609, t615;
  double t644, t646, t671, t673, t678, t680, t681, t682;
  double t687, t692, t695, t696, t697, t699, t712, t717;
  double t727, t734, t751, t754, t770, t796, t801, t804;
  double t809, t811, t813, t818, t829, t841, t844, t847;
  double t867, t871, t892, t897, t899, t914, t921, t931;
  double t944, t949, t955, t959, t960, t965, t974, t979;
#endif

#endif

#endif

#endif

#endif


  lda_c_chachiyo_mod_params *params;

  assert(p->params != NULL);
  params = (lda_c_chachiyo_mod_params * )(p->params);

  t1 = M_CBRT3;
  t2 = t1 * t1;
  t3 = params->bp * t2;
  t5 = POW_1_3(0.1e1 / M_PI);
  t7 = M_CBRT4;
  t8 = 0.1e1 / t5 * t7;
  t9 = rho[0] + rho[1];
  t10 = POW_1_3(t9);
  t11 = t8 * t10;
  t14 = params->bp * t1;
  t15 = t5 * t5;
  t17 = t7 * t7;
  t18 = 0.1e1 / t15 * t17;
  t19 = t10 * t10;
  t20 = t18 * t19;
  t23 = 0.1e1 + t3 * t11 / 0.3e1 + t14 * t20 / 0.3e1;
  t24 = log(t23);
  t25 = params->ap * t24;
  t26 = params->bf * t2;
  t29 = params->bf * t1;
  t32 = 0.1e1 + t26 * t11 / 0.3e1 + t29 * t20 / 0.3e1;
  t33 = log(t32);
  t35 = params->af * t33 - t25;
  t36 = rho[0] - rho[1];
  t37 = 0.1e1 / t9;
  t38 = t36 * t37;
  t39 = 0.1e1 + t38;
  t40 = t39 <= p->zeta_threshold;
  t41 = POW_1_3(t39);
  t42 = t41 * t41;
  t43 = my_piecewise3(t40, 0, t42);
  t44 = 0.1e1 - t38;
  t45 = t44 <= p->zeta_threshold;
  t46 = POW_1_3(t44);
  t47 = t46 * t46;
  t48 = my_piecewise3(t45, 0, t47);
  t50 = t43 / 0.2e1 + t48 / 0.2e1;
  t51 = t50 * t50;
  t54 = -0.2e1 * t51 * t50 + 0.2e1;
  t55 = t35 * t54;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = t25 + t55;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t57 = t8 / t19;
  t61 = t18 / t10;
  t64 = t3 * t57 / 0.9e1 + 0.2e1 / 0.9e1 * t14 * t61;
  t66 = 0.1e1 / t23;
  t67 = params->ap * t64 * t66;
  t72 = t26 * t57 / 0.9e1 + 0.2e1 / 0.9e1 * t29 * t61;
  t74 = 0.1e1 / t32;
  t76 = params->af * t72 * t74 - t67;
  t77 = t76 * t54;
  t78 = t35 * t51;
  t79 = 0.1e1 / t41;
  t80 = t9 * t9;
  t81 = 0.1e1 / t80;
  t82 = t36 * t81;
  t83 = t37 - t82;
  t86 = my_piecewise3(t40, 0, 0.2e1 / 0.3e1 * t79 * t83);
  t87 = 0.1e1 / t46;
  t88 = -t83;
  t91 = my_piecewise3(t45, 0, 0.2e1 / 0.3e1 * t87 * t88);
  t93 = t86 / 0.2e1 + t91 / 0.2e1;
  t94 = t78 * t93;
  t95 = 0.6e1 * t94;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t25 + t55 + t9 * (t67 + t77 - t95);

  t98 = -t37 - t82;
  t101 = my_piecewise3(t40, 0, 0.2e1 / 0.3e1 * t79 * t98);
  t102 = -t98;
  t105 = my_piecewise3(t45, 0, 0.2e1 / 0.3e1 * t87 * t102);
  t107 = t101 / 0.2e1 + t105 / 0.2e1;
  t108 = t78 * t107;
  t109 = 0.6e1 * t108;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = t25 + t55 + t9 * (t67 + t77 - t109);

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t112 = 0.2e1 * t67;
  t113 = 0.2e1 * t77;
  t117 = t8 / t19 / t9;
  t121 = t18 / t10 / t9;
  t124 = -0.2e1 / 0.27e2 * t3 * t117 - 0.2e1 / 0.27e2 * t14 * t121;
  t125 = params->ap * t124;
  t126 = t125 * t66;
  t127 = t64 * t64;
  t129 = t23 * t23;
  t130 = 0.1e1 / t129;
  t131 = params->ap * t127 * t130;
  t135 = -0.2e1 / 0.27e2 * t26 * t117 - 0.2e1 / 0.27e2 * t29 * t121;
  t136 = params->af * t135;
  t138 = t72 * t72;
  t140 = t32 * t32;
  t141 = 0.1e1 / t140;
  t143 = -params->af * t138 * t141 + t136 * t74 - t126 + t131;
  t144 = t143 * t54;
  t145 = t76 * t51;
  t146 = t145 * t93;
  t147 = 0.12e2 * t146;
  t148 = t35 * t50;
  t149 = t93 * t93;
  t150 = t148 * t149;
  t151 = 0.12e2 * t150;
  t153 = 0.1e1 / t41 / t39;
  t154 = t83 * t83;
  t157 = t80 * t9;
  t158 = 0.1e1 / t157;
  t159 = t36 * t158;
  t161 = -0.2e1 * t81 + 0.2e1 * t159;
  t165 = my_piecewise3(t40, 0, -0.2e1 / 0.9e1 * t153 * t154 + 0.2e1 / 0.3e1 * t79 * t161);
  t167 = 0.1e1 / t46 / t44;
  t168 = t88 * t88;
  t171 = -t161;
  t175 = my_piecewise3(t45, 0, -0.2e1 / 0.9e1 * t167 * t168 + 0.2e1 / 0.3e1 * t87 * t171);
  t177 = t165 / 0.2e1 + t175 / 0.2e1;
  t178 = t78 * t177;
  t179 = 0.6e1 * t178;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = t112 + t113 - 0.12e2 * t94 + t9 * (t126 - t131 + t144 - t147 - t151 - t179);

  t183 = t145 * t107;
  t185 = t107 * t93;
  t186 = t148 * t185;
  t188 = t153 * t98;
  t191 = t79 * t36;
  t195 = my_piecewise3(t40, 0, -0.2e1 / 0.9e1 * t188 * t83 + 0.4e1 / 0.3e1 * t191 * t158);
  t196 = t167 * t102;
  t199 = t87 * t36;
  t203 = my_piecewise3(t45, 0, -0.2e1 / 0.9e1 * t196 * t88 - 0.4e1 / 0.3e1 * t199 * t158);
  t205 = t195 / 0.2e1 + t203 / 0.2e1;
  t206 = t78 * t205;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = t112 + t113 - t95 - t109 + t9 * (t126 - t131 + t144 - 0.6e1 * t146 - 0.6e1 * t183 - 0.12e2 * t186 - 0.6e1 * t206);

  t211 = 0.12e2 * t183;
  t212 = t107 * t107;
  t213 = t148 * t212;
  t214 = 0.12e2 * t213;
  t215 = t98 * t98;
  t219 = 0.2e1 * t81 + 0.2e1 * t159;
  t223 = my_piecewise3(t40, 0, -0.2e1 / 0.9e1 * t153 * t215 + 0.2e1 / 0.3e1 * t79 * t219);
  t224 = t102 * t102;
  t227 = -t219;
  t231 = my_piecewise3(t45, 0, -0.2e1 / 0.9e1 * t167 * t224 + 0.2e1 / 0.3e1 * t87 * t227);
  t233 = t223 / 0.2e1 + t231 / 0.2e1;
  t234 = t78 * t233;
  t235 = 0.6e1 * t234;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = t112 + t113 - 0.12e2 * t108 + t9 * (t126 - t131 + t144 - t211 - t214 - t235);

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t238 = 0.3e1 * t126;
  t239 = 0.3e1 * t131;
  t240 = 0.3e1 * t144;
  t246 = t8 / t19 / t80;
  t251 = t18 / t10 / t80;
  t255 = params->ap * (0.10e2 / 0.81e2 * t3 * t246 + 0.8e1 / 0.81e2 * t14 * t251);
  t256 = t255 * t66;
  t257 = t130 * t64;
  t258 = t125 * t257;
  t259 = 0.3e1 * t258;
  t263 = 0.1e1 / t129 / t23;
  t264 = params->ap * t127 * t64 * t263;
  t265 = 0.2e1 * t264;
  t271 = params->af * (0.10e2 / 0.81e2 * t26 * t246 + 0.8e1 / 0.81e2 * t29 * t251);
  t273 = t141 * t72;
  t279 = 0.1e1 / t140 / t32;
  t282 = 0.2e1 * params->af * t138 * t72 * t279 - 0.3e1 * t136 * t273 + t271 * t74 - t256 + t259 - t265;
  t283 = t282 * t54;
  t284 = t143 * t51;
  t285 = t284 * t93;
  t286 = 0.18e2 * t285;
  t287 = t76 * t50;
  t288 = t287 * t149;
  t290 = t145 * t177;
  t292 = t149 * t93;
  t293 = t35 * t292;
  t294 = 0.12e2 * t293;
  t295 = t93 * t177;
  t296 = t148 * t295;
  t297 = 0.36e2 * t296;
  t298 = t39 * t39;
  t300 = 0.1e1 / t41 / t298;
  t301 = t154 * t83;
  t304 = t153 * t83;
  t307 = t80 * t80;
  t308 = 0.1e1 / t307;
  t309 = t36 * t308;
  t311 = 0.6e1 * t158 - 0.6e1 * t309;
  t315 = my_piecewise3(t40, 0, 0.8e1 / 0.27e2 * t300 * t301 - 0.2e1 / 0.3e1 * t304 * t161 + 0.2e1 / 0.3e1 * t79 * t311);
  t316 = t44 * t44;
  t318 = 0.1e1 / t46 / t316;
  t319 = t168 * t88;
  t322 = t167 * t88;
  t325 = -t311;
  t329 = my_piecewise3(t45, 0, 0.8e1 / 0.27e2 * t318 * t319 - 0.2e1 / 0.3e1 * t322 * t171 + 0.2e1 / 0.3e1 * t87 * t325);
  t331 = t315 / 0.2e1 + t329 / 0.2e1;
  t332 = t78 * t331;
  t333 = 0.6e1 * t332;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = t238 - t239 + t240 - 0.36e2 * t146 - 0.36e2 * t150 - 0.18e2 * t178 + t9 * (t256 - t259 + t265 + t283 - t286 - 0.36e2 * t288 - 0.18e2 * t290 - t294 - t297 - t333);

  t337 = 0.24e2 * t186;
  t338 = 0.12e2 * t206;
  t342 = t284 * t107;
  t344 = t287 * t185;
  t345 = 0.24e2 * t344;
  t346 = t145 * t205;
  t347 = 0.12e2 * t346;
  t348 = t35 * t149;
  t349 = t348 * t107;
  t351 = t205 * t93;
  t352 = t148 * t351;
  t354 = t107 * t177;
  t355 = t148 * t354;
  t357 = t300 * t98;
  t360 = t153 * t36;
  t371 = my_piecewise3(t40, 0, 0.8e1 / 0.27e2 * t357 * t154 - 0.8e1 / 0.9e1 * t360 * t158 * t83 - 0.2e1 / 0.9e1 * t188 * t161 + 0.4e1 / 0.3e1 * t79 * t158 - 0.4e1 * t191 * t308);
  t372 = t318 * t102;
  t375 = t167 * t36;
  t386 = my_piecewise3(t45, 0, 0.8e1 / 0.27e2 * t372 * t168 + 0.8e1 / 0.9e1 * t375 * t158 * t88 - 0.2e1 / 0.9e1 * t196 * t171 - 0.4e1 / 0.3e1 * t87 * t158 + 0.4e1 * t199 * t308);
  t388 = t371 / 0.2e1 + t386 / 0.2e1;
  t389 = t78 * t388;
  t391 = t256 - t259 + t265 + t283 - 0.12e2 * t285 - 0.12e2 * t288 - 0.6e1 * t290 - 0.6e1 * t342 - t345 - t347 - 0.12e2 * t349 - 0.24e2 * t352 - 0.12e2 * t355 - 0.6e1 * t389;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[1] = t9 * t391 - 0.24e2 * t146 - t151 - t179 - t211 + t238 - t239 + t240 - t337 - t338;

  t396 = t287 * t212;
  t398 = t35 * t93;
  t399 = t398 * t212;
  t401 = t107 * t205;
  t402 = t148 * t401;
  t404 = t145 * t233;
  t406 = t233 * t93;
  t407 = t148 * t406;
  t409 = t300 * t215;
  t414 = t153 * t219;
  t419 = -0.2e1 * t158 - 0.6e1 * t309;
  t423 = my_piecewise3(t40, 0, 0.8e1 / 0.27e2 * t409 * t83 - 0.8e1 / 0.9e1 * t188 * t159 - 0.2e1 / 0.9e1 * t414 * t83 + 0.2e1 / 0.3e1 * t79 * t419);
  t424 = t318 * t224;
  t429 = t167 * t227;
  t432 = -t419;
  t436 = my_piecewise3(t45, 0, 0.8e1 / 0.27e2 * t424 * t88 + 0.8e1 / 0.9e1 * t196 * t159 - 0.2e1 / 0.9e1 * t429 * t88 + 0.2e1 / 0.3e1 * t87 * t432);
  t438 = t423 / 0.2e1 + t436 / 0.2e1;
  t439 = t78 * t438;
  t441 = t256 - t259 + t265 + t283 - 0.6e1 * t285 - 0.12e2 * t342 - t345 - t347 - 0.12e2 * t396 - 0.12e2 * t399 - 0.24e2 * t402 - 0.6e1 * t404 - 0.12e2 * t407 - 0.6e1 * t439;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[2] = t9 * t441 - t147 - 0.24e2 * t183 - t214 - t235 + t238 - t239 + t240 - t337 - t338;

  t446 = 0.18e2 * t342;
  t449 = t212 * t107;
  t450 = t35 * t449;
  t451 = 0.12e2 * t450;
  t452 = t107 * t233;
  t453 = t148 * t452;
  t454 = 0.36e2 * t453;
  t455 = t215 * t98;
  t461 = -0.6e1 * t158 - 0.6e1 * t309;
  t465 = my_piecewise3(t40, 0, 0.8e1 / 0.27e2 * t300 * t455 - 0.2e1 / 0.3e1 * t188 * t219 + 0.2e1 / 0.3e1 * t79 * t461);
  t466 = t224 * t102;
  t471 = -t461;
  t475 = my_piecewise3(t45, 0, 0.8e1 / 0.27e2 * t318 * t466 - 0.2e1 / 0.3e1 * t196 * t227 + 0.2e1 / 0.3e1 * t87 * t471);
  t477 = t465 / 0.2e1 + t475 / 0.2e1;
  t478 = t78 * t477;
  t479 = 0.6e1 * t478;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[3] = t238 - t239 + t240 - 0.36e2 * t183 - 0.36e2 * t213 - 0.18e2 * t234 + t9 * (t256 - t259 + t265 + t283 - t446 - 0.36e2 * t396 - 0.18e2 * t404 - t451 - t454 - t479);

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t482 = 0.12e2 * t258;
  t483 = 0.8e1 * t264;
  t486 = 0.4e1 * t283;
  t489 = 0.12e2 * t125 * t263 * t127;
  t491 = 0.4e1 * t255 * t257;
  t492 = t124 * t124;
  t495 = 0.3e1 * params->ap * t492 * t130;
  t496 = t127 * t127;
  t498 = t129 * t129;
  t501 = 0.6e1 * params->ap * t496 / t498;
  t502 = t143 * t50;
  t503 = t502 * t149;
  t505 = t287 * t295;
  t507 = t177 * t177;
  t515 = t8 / t19 / t157;
  t520 = t18 / t10 / t157;
  t531 = t135 * t135;
  t535 = t138 * t138;
  t537 = t140 * t140;
  t547 = params->ap * (-0.80e2 / 0.243e3 * t3 * t515 - 0.56e2 / 0.243e3 * t14 * t520) * t66;
  t549 = (params->af * (-0.80e2 / 0.243e3 * t26 * t515 - 0.56e2 / 0.243e3 * t29 * t520) * t74 - 0.4e1 * t271 * t273 + 0.12e2 * t136 * t279 * t138 - 0.3e1 * params->af * t531 * t141 - 0.6e1 * params->af * t535 / t537 - t547 + t491 - t489 + t495 + t501) * t54;
  t550 = t282 * t51;
  t551 = t550 * t93;
  t553 = t284 * t177;
  t555 = t76 * t292;
  t557 = t145 * t331;
  t563 = 0.1e1 / t41 / t298 / t39;
  t564 = t154 * t154;
  t570 = t161 * t161;
  t576 = 0.1e1 / t307 / t9;
  t577 = t36 * t576;
  t579 = -0.24e2 * t308 + 0.24e2 * t577;
  t583 = my_piecewise3(t40, 0, -0.56e2 / 0.81e2 * t563 * t564 + 0.16e2 / 0.9e1 * t300 * t154 * t161 - 0.2e1 / 0.3e1 * t153 * t570 - 0.8e1 / 0.9e1 * t304 * t311 + 0.2e1 / 0.3e1 * t79 * t579);
  t586 = 0.1e1 / t46 / t316 / t44;
  t587 = t168 * t168;
  t593 = t171 * t171;
  t602 = my_piecewise3(t45, 0, -0.56e2 / 0.81e2 * t586 * t587 + 0.16e2 / 0.9e1 * t318 * t168 * t171 - 0.2e1 / 0.3e1 * t167 * t593 - 0.8e1 / 0.9e1 * t322 * t325 - 0.2e1 / 0.3e1 * t87 * t579);
  t607 = t489 - t491 - t495 - t501 - 0.72e2 * t503 - 0.144e3 * t505 - 0.36e2 * t148 * t507 - 0.48e2 * t148 * t93 * t331 + t549 + t547 - 0.24e2 * t551 - 0.36e2 * t553 - 0.48e2 * t555 - 0.24e2 * t557 - 0.72e2 * t348 * t177 - 0.6e1 * t78 * (t583 / 0.2e1 + t602 / 0.2e1);
  t609 = 0.4e1 * t256;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = t9 * t607 - 0.72e2 * t285 - 0.144e3 * t288 - 0.72e2 * t290 - 0.48e2 * t293 - 0.144e3 * t296 - 0.24e2 * t332 - t482 + t483 + t486 + t609;

  t615 = 0.72e2 * t344;
  t644 = 0.16e2 * t191 * t576;
  t646 = my_piecewise3(t40, 0, -0.56e2 / 0.81e2 * t563 * t98 * t301 + 0.16e2 / 0.9e1 * t300 * t36 * t158 * t154 + 0.8e1 / 0.9e1 * t357 * t83 * t161 - 0.4e1 / 0.3e1 * t153 * t158 * t83 + 0.4e1 * t360 * t308 * t83 - 0.4e1 / 0.3e1 * t360 * t158 * t161 - 0.2e1 / 0.9e1 * t188 * t311 - 0.8e1 * t79 * t308 + t644);
  t671 = 0.16e2 * t199 * t576;
  t673 = my_piecewise3(t45, 0, -0.56e2 / 0.81e2 * t586 * t102 * t319 - 0.16e2 / 0.9e1 * t318 * t36 * t158 * t168 + 0.8e1 / 0.9e1 * t372 * t88 * t171 + 0.4e1 / 0.3e1 * t167 * t158 * t88 - 0.4e1 * t375 * t308 * t88 + 0.4e1 / 0.3e1 * t375 * t158 * t171 - 0.2e1 / 0.9e1 * t196 * t325 + 0.8e1 * t87 * t308 - t671);
  t678 = t550 * t107;
  t680 = t284 * t205;
  t681 = 0.18e2 * t680;
  t682 = t145 * t388;
  t687 = t76 * t149 * t107;
  t692 = -0.12e2 * t555 + t549 - 0.6e1 * t78 * (t646 / 0.2e1 + t673 / 0.2e1) - 0.6e1 * t678 - t681 - 0.18e2 * t682 - 0.36e2 * t348 * t205 - 0.36e2 * t687 - 0.36e2 * t503 + t547 - 0.18e2 * t551 - 0.18e2 * t553;
  t695 = t502 * t185;
  t696 = 0.36e2 * t695;
  t697 = t287 * t351;
  t699 = t287 * t354;
  t712 = -0.12e2 * t148 * t107 * t331 - 0.36e2 * t148 * t205 * t177 - 0.36e2 * t148 * t388 * t93 - 0.36e2 * t398 * t354 + t489 - t491 - t495 - t501 - 0.36e2 * t505 - 0.6e1 * t557 - t696 - 0.72e2 * t697 - 0.36e2 * t699;
  t717 = 0.36e2 * t346;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[1] = -t482 + t483 - 0.72e2 * t288 - t297 - t615 - 0.36e2 * t349 - 0.72e2 * t352 - 0.36e2 * t355 + t486 + t9 * (t692 + t712) + t609 - 0.54e2 * t285 - 0.36e2 * t290 - t294 - t333 - t446 - t717 - 0.18e2 * t389;

  t727 = t287 * t401;
  t734 = t287 * t406;
  t751 = t36 * t36;
  t754 = 0.1e1 / t307 / t80;
  t770 = my_piecewise3(t40, 0, -0.56e2 / 0.81e2 * t563 * t215 * t154 + 0.64e2 / 0.27e2 * t357 * t83 * t36 * t158 + 0.8e1 / 0.27e2 * t409 * t161 - 0.16e2 / 0.9e1 * t153 * t751 * t754 - 0.8e1 / 0.9e1 * t188 * t158 + 0.8e1 / 0.3e1 * t188 * t309 + 0.8e1 / 0.27e2 * t300 * t219 * t154 - 0.4e1 / 0.9e1 * t153 * t419 * t83 - 0.2e1 / 0.9e1 * t414 * t161 + t644);
  t796 = my_piecewise3(t45, 0, -0.56e2 / 0.81e2 * t586 * t224 * t168 - 0.64e2 / 0.27e2 * t372 * t88 * t36 * t158 + 0.8e1 / 0.27e2 * t424 * t171 - 0.16e2 / 0.9e1 * t167 * t751 * t754 + 0.8e1 / 0.9e1 * t196 * t158 - 0.8e1 / 0.3e1 * t196 * t309 + 0.8e1 / 0.27e2 * t318 * t227 * t168 - 0.4e1 / 0.9e1 * t167 * t432 * t88 - 0.2e1 / 0.9e1 * t429 * t171 - t671);
  t801 = t502 * t212;
  t804 = t76 * t93 * t212;
  t809 = t284 * t233;
  t811 = t145 * t438;
  t813 = t205 * t205;
  t818 = -0.48e2 * t727 - 0.48e2 * t398 * t401 - 0.24e2 * t148 * t107 * t388 - 0.24e2 * t734 - 0.24e2 * t148 * t438 * t93 - 0.12e2 * t148 * t233 * t177 + t549 - 0.6e1 * t78 * (t770 / 0.2e1 + t796 / 0.2e1) - 0.12e2 * t801 - 0.24e2 * t804 - 0.12e2 * t35 * t177 * t212 - 0.6e1 * t809 - 0.12e2 * t811 - 0.24e2 * t148 * t813 - 0.12e2 * t348 * t233;
  t829 = -0.12e2 * t678 - 0.24e2 * t680 - 0.12e2 * t682 - 0.24e2 * t687 - 0.12e2 * t503 + t547 - 0.12e2 * t551 - 0.6e1 * t553 - t495 - t501 + t489 - t491 - 0.48e2 * t695 - 0.48e2 * t697 - 0.24e2 * t699;
  t841 = t9 * (t818 + t829) + t609 - 0.36e2 * t285 - 0.12e2 * t290 - 0.36e2 * t342 - 0.48e2 * t346 - 0.12e2 * t389 - 0.24e2 * t396 - 0.24e2 * t399 - 0.12e2 * t404 - 0.12e2 * t439;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[2] = -t482 + t483 - 0.24e2 * t288 - 0.96e2 * t344 - 0.24e2 * t349 - 0.48e2 * t352 - 0.24e2 * t355 - 0.48e2 * t402 - 0.24e2 * t407 + t486 + t841;

  t844 = t35 * t212;
  t847 = t145 * t477;
  t867 = 0.12e2 * t308 + 0.24e2 * t577;
  t871 = my_piecewise3(t40, 0, -0.56e2 / 0.81e2 * t563 * t455 * t83 + 0.16e2 / 0.9e1 * t409 * t159 + 0.8e1 / 0.9e1 * t357 * t219 * t83 - 0.4e1 / 0.3e1 * t360 * t158 * t219 - 0.2e1 / 0.3e1 * t188 * t419 - 0.2e1 / 0.9e1 * t153 * t461 * t83 + 0.2e1 / 0.3e1 * t79 * t867);
  t892 = my_piecewise3(t45, 0, -0.56e2 / 0.81e2 * t586 * t466 * t88 - 0.16e2 / 0.9e1 * t424 * t159 + 0.8e1 / 0.9e1 * t372 * t227 * t88 + 0.4e1 / 0.3e1 * t375 * t158 * t227 - 0.2e1 / 0.3e1 * t196 * t432 - 0.2e1 / 0.9e1 * t167 * t471 * t88 - 0.2e1 / 0.3e1 * t87 * t867);
  t897 = t76 * t449;
  t899 = t287 * t452;
  t914 = -0.36e2 * t844 * t205 - 0.6e1 * t847 - 0.6e1 * t78 * (t871 / 0.2e1 + t892 / 0.2e1) - 0.12e2 * t897 - 0.36e2 * t899 - 0.36e2 * t398 * t452 - 0.36e2 * t148 * t205 * t233 - 0.36e2 * t148 * t107 * t438 - 0.12e2 * t148 * t477 * t93 - 0.72e2 * t727 - 0.36e2 * t734 + t549;
  t921 = -0.36e2 * t801 - 0.36e2 * t804 - 0.18e2 * t809 - 0.18e2 * t811 - 0.18e2 * t678 - t681 + t547 - 0.6e1 * t551 - t495 - t501 + t489 - t491 - t696;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[3] = -t482 + t483 - t615 - 0.72e2 * t402 - 0.36e2 * t407 - t454 + t486 + t9 * (t914 + t921) + t609 - t286 - 0.54e2 * t342 - t717 - 0.72e2 * t396 - 0.36e2 * t399 - 0.36e2 * t404 - 0.18e2 * t439 - t451 - t479;

  t931 = t233 * t233;
  t944 = t215 * t215;
  t949 = t219 * t219;
  t955 = 0.24e2 * t308 + 0.24e2 * t577;
  t959 = my_piecewise3(t40, 0, -0.56e2 / 0.81e2 * t563 * t944 + 0.16e2 / 0.9e1 * t409 * t219 - 0.2e1 / 0.3e1 * t153 * t949 - 0.8e1 / 0.9e1 * t188 * t461 + 0.2e1 / 0.3e1 * t79 * t955);
  t960 = t224 * t224;
  t965 = t227 * t227;
  t974 = my_piecewise3(t45, 0, -0.56e2 / 0.81e2 * t586 * t960 + 0.16e2 / 0.9e1 * t424 * t227 - 0.2e1 / 0.3e1 * t167 * t965 - 0.8e1 / 0.9e1 * t196 * t471 - 0.2e1 / 0.3e1 * t87 * t955);
  t979 = t489 - t491 - t495 - t501 - 0.144e3 * t899 - 0.36e2 * t148 * t931 - 0.48e2 * t148 * t107 * t477 + t549 - 0.48e2 * t897 + t547 - 0.24e2 * t678 - 0.72e2 * t801 - 0.36e2 * t809 - 0.24e2 * t847 - 0.72e2 * t844 * t233 - 0.6e1 * t78 * (t959 / 0.2e1 + t974 / 0.2e1);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[4] = t9 * t979 - 0.72e2 * t342 - 0.144e3 * t396 - 0.72e2 * t404 - 0.48e2 * t450 - 0.144e3 * t453 - 0.24e2 * t478 - t482 + t483 + t486 + t609;

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}

