/* 
  This file was generated automatically with ./maple2c_new.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2018 (X86 64 LINUX)
  Maple source      : ../maple/lda_exc/lda_x_sloc.mpl
  Type of functional: lda_exc
*/

#define maple2c_order 3

static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, double *zk, double *vrho, double *v2rho2, double *v3rho3)
{
  double t4, t5, t6, t8, t11, t14, t19, t20;

  lda_x_sloc_params *params;

  assert(p->params != NULL);
  params = (lda_x_sloc_params * )(p->params);

  t4 = params->a / (0.2e1 * params->b + 0.2e1);
  t5 = pow(rho[0], params->b);
  t6 = t4 * t5;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    *zk = -0.2e1 * t6;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t8 = t5 * params->b;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -0.2e1 * t4 * t8 - 0.2e1 * t6;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t11 = 0.1e1 / rho[0];
  t14 = params->b * params->b;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -0.2e1 * t4 * t5 * t14 * t11 - 0.2e1 * t4 * t8 * t11;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t19 = rho[0] * rho[0];
  t20 = 0.1e1 / t19;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = -0.2e1 * t4 * t5 * t14 * params->b * t20 + 0.2e1 * t4 * t8 * t20;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


#endif

#endif

#endif

#endif


}


static inline void
func_ferr(const xc_func_type *p, int order, const double *rho, double *zk, double *vrho, double *v2rho2, double *v3rho3)
{
  double t1, t4, t5, t6, t12, t13, t17, t21;
  double t22;

  lda_x_sloc_params *params;

  assert(p->params != NULL);
  params = (lda_x_sloc_params * )(p->params);

  t1 = params->b + 0.1e1;
  t4 = params->a / t1 / 0.2e1;
  t5 = pow(rho[0], params->b);
  t6 = pow(0.2e1, t1);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    *zk = -t4 * t5 * t6;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t4 * t5 * params->b * t6 + (-t4 * t5 * t6);

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t12 = t4 * t5;
  t13 = 0.1e1 / rho[0];
  t17 = params->b * params->b;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t12 * t17 * t13 * t6 - t12 * params->b * t13 * t6;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t21 = rho[0] * rho[0];
  t22 = 0.1e1 / t21;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = -t12 * t17 * params->b * t22 * t6 + t12 * params->b * t22 * t6;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


#endif

#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, double *zk, double *vrho, double *v2rho2, double *v3rho3)
{
  double t1, t3, t4, t5, t6, t7, t8, t9;
  double t10, t11, t12, t13, t14, t17, t19, t20;
  double t21, t22, t23, t24, t25, t26, t27, t30;
  double t31, t32, t35, t38, t41, t44, t47, t48;
  double t50, t52, t54, t55, t57, t59, t61, t62;
  double t63, t64, t65, t66, t69, t70, t72, t76;
  double t77, t78, t79, t80, t82, t86, t90, t92;
  double t93, t94, t100, t101, t107, t112, t113, t116;
  double t120, t121, t123, t127, t132, t134, t137, t142;
  double t144, t147, t149, t150, t153, t154, t156, t161;
  double t163, t165, t172, t175, t176, t178, t190, t196;
  double t199, t201, t204, t206, t209, t215, t233, t236;
  double t242, t259, t265, t267, t269, t276, t280, t290;
  double t297, t308, t316, t319, t325, t333, t336, t348;

  lda_x_sloc_params *params;

  assert(p->params != NULL);
  params = (lda_x_sloc_params * )(p->params);

  t1 = params->b + 0.1e1;
  t3 = 0.1e1 / t1 / 0.2e1;
  t4 = params->a * t3;
  t5 = rho[0] + rho[1];
  t6 = pow(t5, params->b);
  t7 = rho[0] - rho[1];
  t8 = 0.1e1 / t5;
  t9 = t7 * t8;
  t10 = 0.1e1 + t9;
  t11 = pow(t10, t1);
  t12 = 0.1e1 - t9;
  t13 = pow(t12, t1);
  t14 = t11 + t13;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    *zk = -t4 * t6 * t14;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t17 = t6 * params->b;
  t19 = t4 * t17 * t14;
  t20 = t5 * params->a;
  t21 = t3 * t6;
  t22 = t11 * t1;
  t23 = t5 * t5;
  t24 = 0.1e1 / t23;
  t25 = t7 * t24;
  t26 = t8 - t25;
  t27 = 0.1e1 / t10;
  t30 = t13 * t1;
  t31 = -t26;
  t32 = 0.1e1 / t12;
  t35 = t22 * t26 * t27 + t30 * t31 * t32;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t20 * t21 * t35 + (-t4 * t6 * t14) - t19;

  t38 = -t8 - t25;
  t41 = -t38;
  t44 = t22 * t38 * t27 + t30 * t41 * t32;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = -t20 * t21 * t44 + (-t4 * t6 * t14) - t19;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t47 = t4 * t6;
  t48 = params->b * t8;
  t50 = t47 * t48 * t14;
  t52 = t4 * t6 * t35;
  t54 = params->b * params->b;
  t55 = t54 * t8;
  t57 = t47 * t55 * t14;
  t59 = t4 * t17 * t35;
  t61 = t1 * t1;
  t62 = t11 * t61;
  t63 = t26 * t26;
  t64 = t10 * t10;
  t65 = 0.1e1 / t64;
  t66 = t63 * t65;
  t69 = 0.1e1 / t23 / t5;
  t70 = t7 * t69;
  t72 = -0.2e1 * t24 + 0.2e1 * t70;
  t76 = t13 * t61;
  t77 = t31 * t31;
  t78 = t12 * t12;
  t79 = 0.1e1 / t78;
  t80 = t77 * t79;
  t82 = -t72;
  t86 = t22 * t72 * t27 + t30 * t82 * t32 - t22 * t66 - t30 * t80 + t62 * t66 + t76 * t80;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t20 * t21 * t86 - t50 - 0.2e1 * t52 - t57 - 0.2e1 * t59;

  t90 = t4 * t6 * t44;
  t92 = t4 * t17 * t44;
  t93 = t26 * t65;
  t94 = t93 * t38;
  t100 = t31 * t79;
  t101 = t100 * t41;
  t107 = 0.2e1 * t22 * t70 * t27 - 0.2e1 * t30 * t70 * t32 - t30 * t101 + t76 * t101 - t22 * t94 + t62 * t94;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = -t20 * t21 * t107 - t50 - t52 - t57 - t59 - t90 - t92;

  t112 = t38 * t38;
  t113 = t112 * t65;
  t116 = 0.2e1 * t24 + 0.2e1 * t70;
  t120 = t41 * t41;
  t121 = t120 * t79;
  t123 = -t116;
  t127 = t22 * t116 * t27 + t30 * t123 * t32 - t22 * t113 + t62 * t113 - t30 * t121 + t76 * t121;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = -t20 * t21 * t127 - t50 - t57 - 0.2e1 * t90 - 0.2e1 * t92;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t132 = t47 * params->b * t24 * t14;
  t134 = t47 * t48 * t35;
  t137 = t4 * t6 * t86;
  t142 = t47 * t54 * params->b * t24 * t14;
  t144 = t47 * t55 * t35;
  t147 = t4 * t17 * t86;
  t149 = t61 * t1;
  t150 = t11 * t149;
  t153 = 0.1e1 / t64 / t10;
  t154 = t63 * t26 * t153;
  t156 = t93 * t72;
  t161 = t23 * t23;
  t163 = t7 / t161;
  t165 = 0.6e1 * t69 - 0.6e1 * t163;
  t172 = t13 * t149;
  t175 = 0.1e1 / t78 / t12;
  t176 = t77 * t31 * t175;
  t178 = t100 * t82;
  t190 = t22 * t165 * t27 - t30 * t165 * t32 + t150 * t154 + 0.2e1 * t22 * t154 - 0.3e1 * t62 * t154 - 0.3e1 * t22 * t156 + 0.3e1 * t62 * t156 + t172 * t176 + 0.2e1 * t30 * t176 - 0.3e1 * t76 * t176 - 0.3e1 * t30 * t178 + 0.3e1 * t76 * t178;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = -t20 * t21 * t190 + t132 - 0.3e1 * t134 - 0.3e1 * t137 - t142 - 0.3e1 * t144 - 0.3e1 * t147;

  t196 = t47 * t48 * t44;
  t199 = 0.2e1 * t4 * t6 * t107;
  t201 = t47 * t55 * t44;
  t204 = 0.2e1 * t4 * t17 * t107;
  t206 = t63 * t153 * t38;
  t209 = t72 * t65 * t38;
  t215 = t65 * t7 * t69;
  t233 = t77 * t175 * t41;
  t236 = t82 * t79 * t41;
  t242 = t79 * t7 * t69;
  t259 = -0.4e1 * t22 * t7 * t69 * t65 * t26 + 0.4e1 * t30 * t7 * t69 * t79 * t31 - 0.6e1 * t22 * t163 * t27 + 0.6e1 * t30 * t163 * t32 + 0.4e1 * t62 * t26 * t215 + 0.2e1 * t22 * t69 * t27 - 0.4e1 * t76 * t31 * t242 - 0.2e1 * t30 * t69 * t32 + t150 * t206 + t172 * t233 + 0.2e1 * t22 * t206 - 0.3e1 * t62 * t206 - t22 * t209 + t62 * t209 + 0.2e1 * t30 * t233 - 0.3e1 * t76 * t233 - t30 * t236 + t76 * t236;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[1] = -t20 * t21 * t259 + t132 - 0.2e1 * t134 - t137 - t142 - 0.2e1 * t144 - t147 - t196 - t199 - t201 - t204;

  t265 = t4 * t6 * t127;
  t267 = t4 * t17 * t127;
  t269 = t26 * t153 * t112;
  t276 = t93 * t116;
  t280 = -0.2e1 * t69 - 0.6e1 * t163;
  t290 = t31 * t175 * t120;
  t297 = t100 * t123;
  t308 = -0.4e1 * t22 * t38 * t215 + 0.4e1 * t62 * t38 * t215 + t22 * t280 * t27 + 0.4e1 * t30 * t41 * t242 - 0.4e1 * t76 * t41 * t242 - t30 * t280 * t32 + t150 * t269 + t172 * t290 + 0.2e1 * t22 * t269 - t22 * t276 - 0.3e1 * t62 * t269 + t62 * t276 + 0.2e1 * t30 * t290 - 0.3e1 * t76 * t290 - t30 * t297 + t76 * t297;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[2] = -t20 * t21 * t308 + t132 - t134 - t142 - t144 - 0.2e1 * t196 - t199 - 0.2e1 * t201 - t204 - t265 - t267;

  t316 = t112 * t38 * t153;
  t319 = t38 * t65 * t116;
  t325 = -0.6e1 * t69 - 0.6e1 * t163;
  t333 = t120 * t41 * t175;
  t336 = t41 * t79 * t123;
  t348 = t22 * t325 * t27 - t30 * t325 * t32 + t150 * t316 + t172 * t333 + 0.2e1 * t22 * t316 - 0.3e1 * t22 * t319 + 0.2e1 * t30 * t333 - 0.3e1 * t30 * t336 - 0.3e1 * t62 * t316 + 0.3e1 * t62 * t319 - 0.3e1 * t76 * t333 + 0.3e1 * t76 * t336;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[3] = -t20 * t21 * t348 + t132 - t142 - 0.3e1 * t196 - 0.3e1 * t201 - 0.3e1 * t265 - 0.3e1 * t267;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


#endif

#endif

#endif

#endif


}

