#!/usr/bin/env bash

if [ -n "$SKIP_CHECK" ]; then
    echo "Skipping checks"
    exit 0
fi

if [ -z "$srcdir" ]; then
  srcdir="./"
fi

if [ -z "$tmpdir" ]; then
  tmpdir="/tmp"
fi

if [ -z "$builddir" ]; then
  builddir="./"
fi

# We only print using colors if the output is going to a terminal
if [ -t 1 ] ; then
  NC='\033[0m'
  RED='\033[1;31m'
  GREEN='\033[1;32m'
  YELLOW='\033[1;33m'
  PINK='\033[1;35m'
fi
 
fail=0
echo -e "${YELLOW}Comparing against reference data${NC}"
echo -e "======================================================================"
echo -e "   Functional              System      NSpin       Result"
echo -e "======================================================================"

for i in $(ls $srcdir/regression/*.bz2 | sort); do
  refname=$(basename ${i} .bz2)
  func=${refname%%.*}
  testcase=${refname#*.}
  system=${testcase%.*}
  if [ "x${testcase#*.}" = "xunpol" ]; then
      nspin=1
  else
      nspin=2
  fi
  name=$(printf '%-24s %-12s %-5d' ${func} ${system} ${nspin})

  workdir=$(mktemp -d ${tmpdir}/libxc.XXXXXXXXXX)
  
  echo -ne "${NC} * ${PINK}${name}"

  bunzip2 -c $srcdir/regression/$refname.bz2 > $workdir/${refname}_ref

  $EXEC $builddir/xc-regression $func $nspin $srcdir/input/$system $workdir/$refname > /dev/null
  
  res=$($builddir/xc-error $workdir/$refname $workdir/${refname}_ref)
  if [ "x$res" = "x1" ]; then
      echo -e "      ${GREEN}OK"
  else
      echo -e "     ${RED}FAIL"
      let fail++
  fi
done

echo -e "${NC}"

exit $fail
