#!/usr/bin/env bash

if [ -z "$srcdir" ]; then
  srcdir="./"
fi

if [ -z "$builddir" ]; then
  builddir="./"
fi

systems="H Li BrOH BrOH+"
funcs=$*
if [ "x$funcs" = "x" ]; then
  funcs=$(awk '{print tolower($2)}' ${builddir}../src/xc_funcs.h | sed 's/^xc_//g')
fi

for func in $funcs; do
  echo "processing $func"

  dir=${func%%_*}
  tmp=${func//${dir}_/}
  if [ "x$dir" = "xhyb" ]; then
    dir=${dir}_${tmp%%_*}
    tmp=${func//${dir}_/}
  fi
  dir=${dir}_${tmp%%_*}
  func=${func//${dir}_/}
  
  for system in $systems; do
    for spin in pol unpol; do
      refname=$func.$system.$spin
      if [ "x$spin" = "xunpol" ]; then
        nspin=1
      else
        nspin=2
      fi
      echo $builddir/xc-regression $func $nspin $srcdir/input/$system $srcdir/regression/$dir/$refname > /dev/null
      echo rm -f $srcdir/regression/$dir/$refname.bz2
      echo bzip2 $srcdir/regression/$dir/$refname
    done
  done
done
