#!/usr/bin/env bash

if [ -z "$srcdir" ]; then
  srcdir="./"
fi

if [ -z "$builddir" ]; then
  builddir="./"
fi

systems="H Li BrOH BrOH+"
funcs=$*
if [ "x$funcs" = "x" ]; then
  funcs=$(awk '{print tolower($2)}' ${builddir}../src/xc_funcs.h | sed 's/^xc_//g')
fi

for func in $funcs; do
  echo "processing $func"

  for system in $systems; do
    for spin in pol unpol; do
      refname=$func.$system.$spin
      if [ "x$spin" = "xunpol" ]; then
        nspin=1
      else
        nspin=2
      fi
      $builddir/xc-regression $func $nspin $srcdir/input/$system $srcdir/regression/$refname > /dev/null
      rm -f $srcdir/regression/$refname.bz2
      bzip2 $srcdir/regression/$refname
    done
  done
done
