/* 
  This file was generated automatically with ./scripts/maple2c_new.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : .//maple/mgga_exc/mgga_x_rlda.mpl
  Type of functional: mgga_exc
*/

#define maple2c_order 3

static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, const double *sigma, const double *lapl, const double *tau, double *zk, double *vrho, double *vsigma, double *vlapl, double *vtau, double *v2rho2, double *v2rhosigma, double *v2rholapl, double *v2rhotau, double *v2sigma2, double *v2sigmalapl, double *v2sigmatau, double *v2lapl2, double *v2lapltau, double *v2tau2, double *v3rho3, double *v3rho2sigma, double *v3rho2lapl, double *v3rho2tau, double *v3rhosigma2, double *v3rhosigmalapl, double *v3rhosigmatau, double *v3rholapl2, double *v3rholapltau, double *v3rhotau2, double *v3sigma3, double *v3sigma2lapl, double *v3sigma2tau, double *v3sigmalapl2, double *v3sigmalapltau, double *v3sigmatau2, double *v3lapl3, double *v3lapl2tau, double *v3lapltau2, double *v3tau3)
{
  double t2, t4, t6, t7, t8, t9, t10, t11;
  double t12, t13, t14, t16, t19, t22, t23, t24;
  double t25, t26, t27, t28, t33, t35, t40, t41;
  double t42, t43, t44, t46, t51, t56, t61, t62;
  double t63, t65, t67, t68, t72, t73, t76, t77;
  double t85, t86, t91, t93, t98, t104, t109, t112;
  double t115, t117, t119, t122, t123, t131, t132, t137;
  double t139, t141, t142, t146, t147, t151, t152, t164;
  double t165, t175, t177, t188, t193, t198, t201, t205;
  double t209, t213, t216, t229, t237, t243, t246, t255;
  double t264, t272, t274, t279, t284, t289;

  mgga_x_rlda_params *params;

  assert(p->params != NULL);
  params = (mgga_x_rlda_params * )(p->params);

  t2 = M_CBRT3;
  t4 = POW_1_3(0.1e1 / M_PI);
  t6 = M_CBRT4;
  t7 = t6 * t6;
  t8 = t2 * t4 * t7;
  t9 = M_CBRT2;
  t10 = t9 * t9;
  t11 = POW_1_3(rho[0]);
  t12 = t10 * t11;
  t13 = tau[0] * t10;
  t14 = t11 * t11;
  t16 = 0.1e1 / t14 / rho[0];
  t19 = lapl[0] * t10;
  t22 = 0.2e1 * t13 * t16 - t19 * t16 / 0.4e1;
  t23 = 0.1e-9 < t22;
  t24 = M_PI * params->prefactor;
  t25 = t2 * t2;
  t26 = t24 * t25;
  t27 = 0.1e1 / t4;
  t28 = t27 * t6;
  t33 = my_piecewise3(t23, 0.5e1 / 0.12e2 * t26 * t28 / t22, 0);
  t35 = t8 * t12 * t33;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    *zk = -0.3e1 / 0.16e2 * t35;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t40 = t11 * rho[0] * t2 * t4;
  t41 = t7 * t10;
  t42 = t22 * t22;
  t43 = 0.1e1 / t42;
  t44 = rho[0] * rho[0];
  t46 = 0.1e1 / t14 / t44;
  t51 = -0.10e2 / 0.3e1 * t13 * t46 + 0.5e1 / 0.12e2 * t19 * t46;
  t56 = my_piecewise3(t23, -0.5e1 / 0.12e2 * t26 * t28 * t43 * t51, 0);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t35 / 0.4e1 - 0.3e1 / 0.16e2 * t40 * t41 * t56;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.0e0;

  t61 = t24 * t25 * t27;
  t62 = t6 * t43;
  t63 = t10 * t16;
  t65 = t61 * t62 * t63;
  t67 = my_piecewise3(t23, 0.5e1 / 0.48e2 * t65, 0);
  t68 = t41 * t67;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vlapl[0] = -0.3e1 / 0.16e2 * t40 * t68;

  t72 = my_piecewise3(t23, -0.5e1 / 0.6e1 * t65, 0);
  t73 = t41 * t72;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vtau[0] = -0.3e1 / 0.16e2 * t40 * t73;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t76 = 0.1e1 / t14;
  t77 = t10 * t76;
  t85 = 0.1e1 / t42 / t22;
  t86 = t51 * t51;
  t91 = t44 * rho[0];
  t93 = 0.1e1 / t14 / t91;
  t98 = 0.80e2 / 0.9e1 * t13 * t93 - 0.10e2 / 0.9e1 * t19 * t93;
  t104 = my_piecewise3(t23, 0.5e1 / 0.6e1 * t26 * t28 * t85 * t86 - 0.5e1 / 0.12e2 * t26 * t28 * t43 * t98, 0);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t8 * t77 * t33 / 0.12e2 - t8 * t12 * t56 / 0.2e1 - 0.3e1 / 0.16e2 * t40 * t41 * t104;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = 0.0e0;

  t109 = t11 * t2 * t4;
  t112 = t6 * t85;
  t115 = t61 * t112 * t63 * t51;
  t117 = t10 * t46;
  t119 = t61 * t62 * t117;
  t122 = my_piecewise3(t23, -0.5e1 / 0.24e2 * t115 - 0.25e2 / 0.144e3 * t119, 0);
  t123 = t41 * t122;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[0] = -t109 * t68 / 0.4e1 - 0.3e1 / 0.16e2 * t40 * t123;

  t131 = my_piecewise3(t23, 0.5e1 / 0.3e1 * t115 + 0.25e2 / 0.18e2 * t119, 0);
  t132 = t41 * t131;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[0] = -t109 * t73 / 0.4e1 - 0.3e1 / 0.16e2 * t40 * t132;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[0] = 0.0e0;

  t137 = t9 / t11 / t91;
  t139 = t61 * t112 * t137;
  t141 = my_piecewise3(t23, 0.5e1 / 0.48e2 * t139, 0);
  t142 = t41 * t141;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[0] = -0.3e1 / 0.16e2 * t40 * t142;

  t146 = my_piecewise3(t23, -0.5e1 / 0.6e1 * t139, 0);
  t147 = t41 * t146;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[0] = -0.3e1 / 0.16e2 * t40 * t147;

  t151 = my_piecewise3(t23, 0.20e2 / 0.3e1 * t139, 0);
  t152 = t41 * t151;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[0] = -0.3e1 / 0.16e2 * t40 * t152;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t164 = t42 * t42;
  t165 = 0.1e1 / t164;
  t175 = t44 * t44;
  t177 = 0.1e1 / t14 / t175;
  t188 = my_piecewise3(t23, -0.5e1 / 0.2e1 * t26 * t28 * t165 * t86 * t51 + 0.5e1 / 0.2e1 * t61 * t112 * t51 * t98 - 0.5e1 / 0.12e2 * t26 * t28 * t43 * (-0.880e3 / 0.27e2 * t13 * t177 + 0.110e3 / 0.27e2 * t19 * t177), 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = t8 * t63 * t33 / 0.18e2 - t8 * t77 * t56 / 0.4e1 - 0.3e1 / 0.4e1 * t8 * t12 * t104 - 0.3e1 / 0.16e2 * t40 * t41 * t188;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = 0.0e0;

  t193 = t76 * t2 * t4;
  t198 = t6 * t165;
  t201 = t61 * t198 * t63 * t86;
  t205 = t61 * t112 * t117 * t51;
  t209 = t61 * t112 * t63 * t98;
  t213 = t61 * t62 * t10 * t93;
  t216 = my_piecewise3(t23, 0.5e1 / 0.8e1 * t201 + 0.25e2 / 0.36e2 * t205 - 0.5e1 / 0.24e2 * t209 + 0.25e2 / 0.54e2 * t213, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[0] = -t193 * t68 / 0.12e2 - t109 * t123 / 0.2e1 - 0.3e1 / 0.16e2 * t40 * t41 * t216;

  t229 = my_piecewise3(t23, -0.5e1 * t201 - 0.50e2 / 0.9e1 * t205 + 0.5e1 / 0.3e1 * t209 - 0.100e3 / 0.27e2 * t213, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[0] = -t193 * t73 / 0.12e2 - t109 * t132 / 0.2e1 - 0.3e1 / 0.16e2 * t40 * t41 * t229;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[0] = 0.0e0;

  t237 = t61 * t198 * t137 * t51;
  t243 = t61 * t112 * t9 / t11 / t175;
  t246 = my_piecewise3(t23, -0.5e1 / 0.16e2 * t237 - 0.25e2 / 0.72e2 * t243, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapl2[0] = 0.0e0;

  t255 = my_piecewise3(t23, 0.5e1 / 0.2e1 * t237 + 0.25e2 / 0.9e1 * t243, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[0] = -t109 * t147 / 0.4e1 - 0.3e1 / 0.16e2 * t40 * t41 * t255;

  t264 = my_piecewise3(t23, -0.20e2 * t237 - 0.200e3 / 0.9e1 * t243, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[0] = -t109 * t152 / 0.4e1 - 0.3e1 / 0.16e2 * t40 * t41 * t264;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[0] = 0.0e0;

  t272 = t26 * t28 * t165 / t175 / rho[0];
  t274 = my_piecewise3(t23, 0.5e1 / 0.32e2 * t272, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl3[0] = -0.3e1 / 0.16e2 * t40 * t41 * t274;

  t279 = my_piecewise3(t23, -0.5e1 / 0.4e1 * t272, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[0] = -0.3e1 / 0.16e2 * t40 * t41 * t279;

  t284 = my_piecewise3(t23, 0.10e2 * t272, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[0] = -0.3e1 / 0.16e2 * t40 * t41 * t284;

  t289 = my_piecewise3(t23, -0.80e2 * t272, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3tau3[0] = -0.3e1 / 0.16e2 * t40 * t41 * t289;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


#endif

#endif

#endif

#endif


}


static inline void
func_ferr(const xc_func_type *p, int order, const double *rho, const double *sigma, const double *lapl, const double *tau, double *zk, double *vrho, double *vsigma, double *vlapl, double *vtau, double *v2rho2, double *v2rhosigma, double *v2rholapl, double *v2rhotau, double *v2sigma2, double *v2sigmalapl, double *v2sigmatau, double *v2lapl2, double *v2lapltau, double *v2tau2, double *v3rho3, double *v3rho2sigma, double *v3rho2lapl, double *v3rho2tau, double *v3rhosigma2, double *v3rhosigmalapl, double *v3rhosigmatau, double *v3rholapl2, double *v3rholapltau, double *v3rhotau2, double *v3sigma3, double *v3sigma2lapl, double *v3sigma2tau, double *v3sigmalapl2, double *v3sigmalapltau, double *v3sigmatau2, double *v3lapl3, double *v3lapl2tau, double *v3lapltau2, double *v3tau3)
{
  double t2, t4, t5, t6, t7, t8, t9, t10;
  double t12, t17, t18, t19, t20, t21, t22, t23;
  double t28, t30, t34, t35, t36, t37, t38, t40;
  double t45, t50, t56, t58, t59, t63, t64, t67;
  double t68, t75, t76, t81, t83, t88, t94, t98;
  double t102, t103, t106, t110, t113, t114, t122, t123;
  double t127, t130, t132, t133, t137, t138, t142, t143;
  double t156, t157, t167, t169, t180, t184, t188, t191;
  double t195, t199, t203, t206, t218, t226, t232, t235;
  double t244, t253, t261, t263, t268, t273, t278;

  mgga_x_rlda_params *params;

  assert(p->params != NULL);
  params = (mgga_x_rlda_params * )(p->params);

  t2 = M_CBRT3;
  t4 = POW_1_3(0.1e1 / M_PI);
  t5 = t2 * t4;
  t6 = M_CBRT4;
  t7 = t6 * t6;
  t8 = POW_1_3(rho[0]);
  t9 = t7 * t8;
  t10 = t8 * t8;
  t12 = 0.1e1 / t10 / rho[0];
  t17 = 0.2e1 * tau[0] * t12 - lapl[0] * t12 / 0.4e1;
  t18 = 0.1e-9 < t17;
  t19 = M_PI * params->prefactor;
  t20 = t2 * t2;
  t21 = t19 * t20;
  t22 = 0.1e1 / t4;
  t23 = t22 * t6;
  t28 = my_piecewise3(t18, 0.5e1 / 0.12e2 * t21 * t23 / t17, 0);
  t30 = t5 * t9 * t28;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    *zk = -0.3e1 / 0.8e1 * t30;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t34 = t8 * rho[0] * t2;
  t35 = t4 * t7;
  t36 = t17 * t17;
  t37 = 0.1e1 / t36;
  t38 = rho[0] * rho[0];
  t40 = 0.1e1 / t10 / t38;
  t45 = -0.10e2 / 0.3e1 * tau[0] * t40 + 0.5e1 / 0.12e2 * lapl[0] * t40;
  t50 = my_piecewise3(t18, -0.5e1 / 0.12e2 * t21 * t23 * t37 * t45, 0);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t30 / 0.2e1 - 0.3e1 / 0.8e1 * t34 * t35 * t50;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.0e0;

  t56 = t21 * t23 * t37 * t12;
  t58 = my_piecewise3(t18, 0.5e1 / 0.48e2 * t56, 0);
  t59 = t35 * t58;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vlapl[0] = -0.3e1 / 0.8e1 * t34 * t59;

  t63 = my_piecewise3(t18, -0.5e1 / 0.6e1 * t56, 0);
  t64 = t35 * t63;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vtau[0] = -0.3e1 / 0.8e1 * t34 * t64;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t67 = 0.1e1 / t10;
  t68 = t7 * t67;
  t75 = 0.1e1 / t36 / t17;
  t76 = t45 * t45;
  t81 = t38 * rho[0];
  t83 = 0.1e1 / t10 / t81;
  t88 = 0.80e2 / 0.9e1 * tau[0] * t83 - 0.10e2 / 0.9e1 * lapl[0] * t83;
  t94 = my_piecewise3(t18, 0.5e1 / 0.6e1 * t21 * t23 * t75 * t76 - 0.5e1 / 0.12e2 * t21 * t23 * t37 * t88, 0);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t5 * t68 * t28 / 0.6e1 - t5 * t9 * t50 - 0.3e1 / 0.8e1 * t34 * t35 * t94;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = 0.0e0;

  t98 = t8 * t2;
  t102 = t19 * t20 * t22;
  t103 = t6 * t75;
  t106 = t102 * t103 * t12 * t45;
  t110 = t21 * t23 * t37 * t40;
  t113 = my_piecewise3(t18, -0.5e1 / 0.24e2 * t106 - 0.25e2 / 0.144e3 * t110, 0);
  t114 = t35 * t113;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[0] = -t98 * t59 / 0.2e1 - 0.3e1 / 0.8e1 * t34 * t114;

  t122 = my_piecewise3(t18, 0.5e1 / 0.3e1 * t106 + 0.25e2 / 0.18e2 * t110, 0);
  t123 = t35 * t122;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[0] = -t98 * t64 / 0.2e1 - 0.3e1 / 0.8e1 * t34 * t123;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[0] = 0.0e0;

  t127 = 0.1e1 / t8 / t81;
  t130 = t21 * t23 * t75 * t127;
  t132 = my_piecewise3(t18, 0.5e1 / 0.96e2 * t130, 0);
  t133 = t35 * t132;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[0] = -0.3e1 / 0.8e1 * t34 * t133;

  t137 = my_piecewise3(t18, -0.5e1 / 0.12e2 * t130, 0);
  t138 = t35 * t137;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[0] = -0.3e1 / 0.8e1 * t34 * t138;

  t142 = my_piecewise3(t18, 0.10e2 / 0.3e1 * t130, 0);
  t143 = t35 * t142;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[0] = -0.3e1 / 0.8e1 * t34 * t143;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t156 = t36 * t36;
  t157 = 0.1e1 / t156;
  t167 = t38 * t38;
  t169 = 0.1e1 / t10 / t167;
  t180 = my_piecewise3(t18, -0.5e1 / 0.2e1 * t21 * t23 * t157 * t76 * t45 + 0.5e1 / 0.2e1 * t102 * t103 * t45 * t88 - 0.5e1 / 0.12e2 * t21 * t23 * t37 * (-0.880e3 / 0.27e2 * tau[0] * t169 + 0.110e3 / 0.27e2 * lapl[0] * t169), 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = t5 * t7 * t12 * t28 / 0.9e1 - t5 * t68 * t50 / 0.2e1 - 0.3e1 / 0.2e1 * t5 * t9 * t94 - 0.3e1 / 0.8e1 * t34 * t35 * t180;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = 0.0e0;

  t184 = t67 * t2;
  t188 = t6 * t157;
  t191 = t102 * t188 * t12 * t76;
  t195 = t102 * t103 * t40 * t45;
  t199 = t102 * t103 * t12 * t88;
  t203 = t21 * t23 * t37 * t83;
  t206 = my_piecewise3(t18, 0.5e1 / 0.8e1 * t191 + 0.25e2 / 0.36e2 * t195 - 0.5e1 / 0.24e2 * t199 + 0.25e2 / 0.54e2 * t203, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[0] = -t184 * t59 / 0.6e1 - t98 * t114 - 0.3e1 / 0.8e1 * t34 * t35 * t206;

  t218 = my_piecewise3(t18, -0.5e1 * t191 - 0.50e2 / 0.9e1 * t195 + 0.5e1 / 0.3e1 * t199 - 0.100e3 / 0.27e2 * t203, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[0] = -t184 * t64 / 0.6e1 - t98 * t123 - 0.3e1 / 0.8e1 * t34 * t35 * t218;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[0] = 0.0e0;

  t226 = t102 * t188 * t127 * t45;
  t232 = t21 * t23 * t75 / t8 / t167;
  t235 = my_piecewise3(t18, -0.5e1 / 0.32e2 * t226 - 0.25e2 / 0.144e3 * t232, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapl2[0] = 0.0e0;

  t244 = my_piecewise3(t18, 0.5e1 / 0.4e1 * t226 + 0.25e2 / 0.18e2 * t232, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[0] = -t98 * t138 / 0.2e1 - 0.3e1 / 0.8e1 * t34 * t35 * t244;

  t253 = my_piecewise3(t18, -0.10e2 * t226 - 0.100e3 / 0.9e1 * t232, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[0] = -t98 * t143 / 0.2e1 - 0.3e1 / 0.8e1 * t34 * t35 * t253;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[0] = 0.0e0;

  t261 = t21 * t23 * t157 / t167 / rho[0];
  t263 = my_piecewise3(t18, 0.5e1 / 0.128e3 * t261, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl3[0] = -0.3e1 / 0.8e1 * t34 * t35 * t263;

  t268 = my_piecewise3(t18, -0.5e1 / 0.16e2 * t261, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[0] = -0.3e1 / 0.8e1 * t34 * t35 * t268;

  t273 = my_piecewise3(t18, 0.5e1 / 0.2e1 * t261, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[0] = -0.3e1 / 0.8e1 * t34 * t35 * t273;

  t278 = my_piecewise3(t18, -0.20e2 * t261, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3tau3[0] = -0.3e1 / 0.8e1 * t34 * t35 * t278;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


#endif

#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, const double *sigma, const double *lapl, const double *tau, double *zk, double *vrho, double *vsigma, double *vlapl, double *vtau, double *v2rho2, double *v2rhosigma, double *v2rholapl, double *v2rhotau, double *v2sigma2, double *v2sigmalapl, double *v2sigmatau, double *v2lapl2, double *v2lapltau, double *v2tau2, double *v3rho3, double *v3rho2sigma, double *v3rho2lapl, double *v3rho2tau, double *v3rhosigma2, double *v3rhosigmalapl, double *v3rhosigmatau, double *v3rholapl2, double *v3rholapltau, double *v3rhotau2, double *v3sigma3, double *v3sigma2lapl, double *v3sigma2tau, double *v3sigmalapl2, double *v3sigmalapltau, double *v3sigmatau2, double *v3lapl3, double *v3lapl2tau, double *v3lapltau2, double *v3tau3)
{
  double t2, t4, t5, t6, t7, t8, t9, t10;
  double t11, t12, t14, t15, t16, t17, t18, t19;
  double t20, t22, t27, t28, t29, t30, t31, t32;
  double t33, t38, t40, t42, t43, t44, t45, t46;
  double t47, t49, t54, t55, t60, t62, t64, t65;
  double t66, t67, t68, t69, t71, t72, t74, t75;
  double t76, t77, t78, t80, t81, t82, t83, t84;
  double t86, t91, t96, t98, t99, t100, t101, t102;
  double t104, t105, t106, t108, t109, t113, t114, t116;
  double t117, t118, t119, t121, t122, t123, t124, t125;
  double t127, t132, t137, t139, t140, t144, t145, t146;
  double t149, t151, t155, t158, t160, t165, t170, t174;
  double t176, t177, t178, t179, t180, t181, t183, t184;
  double t185, t187, t188, t189, t191, t192, t193, t194;
  double t195, t196, t198, t199, t201, t202, t204, t205;
  double t207, t208, t210, t211, t216, t218, t223, t229;
  double t231, t232, t233, t234, t235, t236, t237, t239;
  double t240, t241, t243, t244, t245, t246, t248, t249;
  double t250, t252, t253, t254, t256, t257, t258, t259;
  double t261, t264, t266, t268, t271, t272, t273, t275;
  double t279, t280, t281, t282, t284, t287, t289, t290;
  double t292, t295, t297, t300, t302, t305, t306, t308;
  double t309, t310, t311, t312, t314, t315, t316, t317;
  double t319, t320, t321, t322, t324, t325, t326, t328;
  double t329, t330, t332, t333, t338, t340, t345, t351;
  double t353, t354, t355, t358, t360, t361, t366, t367;
  double t370, t374, t377, t382, t383, t384, t389, t394;
  double t397, t400, t404, t407, t408, t412, t414, t421;
  double t426, t427, t432, t437, t443, t444, t448, t451;
  double t453, t454, t458, t461, t463, t464, t468, t469;
  double t473, t474, t478, t479, t483, t484, t491, t493;
  double t497, t500, t502, t503, t513, t515, t526, t531;
  double t532, t538, t540, t546, t548, t551, t552, t558;
  double t560, t567, t569, t576, t578, t588, t590, t592;
  double t600, t602, t612, t613, t620, t621, t626, t632;
  double t640, t641, t647, t655, t665, t668, t671, t677;
  double t685, t688, t689, t696, t718, t720, t723, t765;
  double t783, t785, t787, t790, t793, t796, t807, t809;
  double t812, t820, t821, t831, t833, t844, t873, t898;
  double t902, t906, t908, t920, t923, t927, t931, t935;
  double t938, t943, t947, t959, t960, t963, t973, t979;
  double t989, t1016, t1019, t1023, t1027, t1031, t1034, t1039;
  double t1043, t1045, t1062, t1067, t1071, t1082, t1097, t1107;
  double t1139, t1143, t1151, t1157, t1160, t1164, t1180, t1186;
  double t1189, t1193, t1202, t1206, t1223, t1227, t1236, t1240;
  double t1257, t1265, t1267, t1275, t1277, t1282, t1287, t1292;
  double t1297, t1302, t1307;

  mgga_x_rlda_params *params;

  assert(p->params != NULL);
  params = (mgga_x_rlda_params * )(p->params);

  t2 = M_CBRT3;
  t4 = POW_1_3(0.1e1 / M_PI);
  t5 = t2 * t4;
  t6 = M_CBRT4;
  t7 = t6 * t6;
  t8 = t5 * t7;
  t9 = rho[0] - rho[1];
  t10 = rho[0] + rho[1];
  t11 = 0.1e1 / t10;
  t12 = t9 * t11;
  t14 = 0.1e1 / 0.2e1 + t12 / 0.2e1;
  t15 = POW_1_3(t14);
  t16 = t15 * t14;
  t17 = POW_1_3(t10);
  t18 = t16 * t17;
  t19 = POW_1_3(rho[0]);
  t20 = t19 * t19;
  t22 = 0.1e1 / t20 / rho[0];
  t27 = 0.2e1 * tau[0] * t22 - lapl[0] * t22 / 0.4e1;
  t28 = 0.1e-9 < t27;
  t29 = M_PI * params->prefactor;
  t30 = t2 * t2;
  t31 = t29 * t30;
  t32 = 0.1e1 / t4;
  t33 = t32 * t6;
  t38 = my_piecewise3(t28, 0.5e1 / 0.12e2 * t31 * t33 / t27, 0);
  t40 = t8 * t18 * t38;
  t42 = 0.1e1 / 0.2e1 - t12 / 0.2e1;
  t43 = POW_1_3(t42);
  t44 = t43 * t42;
  t45 = t44 * t17;
  t46 = POW_1_3(rho[1]);
  t47 = t46 * t46;
  t49 = 0.1e1 / t47 / rho[1];
  t54 = 0.2e1 * tau[1] * t49 - lapl[1] * t49 / 0.4e1;
  t55 = 0.1e-9 < t54;
  t60 = my_piecewise3(t55, 0.5e1 / 0.12e2 * t31 * t33 / t54, 0);
  t62 = t8 * t45 * t60;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    *zk = -0.3e1 / 0.8e1 * t40 - 0.3e1 / 0.8e1 * t62;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t64 = 0.3e1 / 0.8e1 * t40;
  t65 = 0.3e1 / 0.8e1 * t62;
  t66 = t15 * t17;
  t67 = t10 * t10;
  t68 = 0.1e1 / t67;
  t69 = t9 * t68;
  t71 = t11 / 0.2e1 - t69 / 0.2e1;
  t72 = t38 * t71;
  t74 = t8 * t66 * t72;
  t75 = t74 / 0.2e1;
  t76 = t17 * t17;
  t77 = 0.1e1 / t76;
  t78 = t16 * t77;
  t80 = t8 * t78 * t38;
  t81 = t80 / 0.8e1;
  t82 = t27 * t27;
  t83 = 0.1e1 / t82;
  t84 = rho[0] * rho[0];
  t86 = 0.1e1 / t20 / t84;
  t91 = -0.10e2 / 0.3e1 * tau[0] * t86 + 0.5e1 / 0.12e2 * lapl[0] * t86;
  t96 = my_piecewise3(t28, -0.5e1 / 0.12e2 * t31 * t33 * t83 * t91, 0);
  t98 = t8 * t18 * t96;
  t99 = 0.3e1 / 0.8e1 * t98;
  t100 = t43 * t17;
  t101 = -t71;
  t102 = t60 * t101;
  t104 = t8 * t100 * t102;
  t105 = t104 / 0.2e1;
  t106 = t44 * t77;
  t108 = t8 * t106 * t60;
  t109 = t108 / 0.8e1;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t64 - t65 + t10 * (-t75 - t81 - t99 - t105 - t109);

  t113 = -t11 / 0.2e1 - t69 / 0.2e1;
  t114 = t38 * t113;
  t116 = t8 * t66 * t114;
  t117 = t116 / 0.2e1;
  t118 = -t113;
  t119 = t60 * t118;
  t121 = t8 * t100 * t119;
  t122 = t121 / 0.2e1;
  t123 = t54 * t54;
  t124 = 0.1e1 / t123;
  t125 = rho[1] * rho[1];
  t127 = 0.1e1 / t47 / t125;
  t132 = -0.10e2 / 0.3e1 * tau[1] * t127 + 0.5e1 / 0.12e2 * lapl[1] * t127;
  t137 = my_piecewise3(t55, -0.5e1 / 0.12e2 * t31 * t33 * t124 * t132, 0);
  t139 = t8 * t45 * t137;
  t140 = 0.3e1 / 0.8e1 * t139;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = -t64 - t65 + t10 * (-t117 - t81 - t122 - t109 - t140);

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.0e0;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[1] = 0.0e0;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[2] = 0.0e0;

  t144 = t17 * t10 * t2;
  t145 = t144 * t4;
  t146 = t7 * t16;
  t149 = t31 * t33 * t83 * t22;
  t151 = my_piecewise3(t28, 0.5e1 / 0.48e2 * t149, 0);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vlapl[0] = -0.3e1 / 0.8e1 * t145 * t146 * t151;

  t155 = t7 * t44;
  t158 = t31 * t33 * t124 * t49;
  t160 = my_piecewise3(t55, 0.5e1 / 0.48e2 * t158, 0);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vlapl[1] = -0.3e1 / 0.8e1 * t145 * t155 * t160;

  t165 = my_piecewise3(t28, -0.5e1 / 0.6e1 * t149, 0);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vtau[0] = -0.3e1 / 0.8e1 * t145 * t146 * t165;

  t170 = my_piecewise3(t55, -0.5e1 / 0.6e1 * t158, 0);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vtau[1] = -0.3e1 / 0.8e1 * t145 * t155 * t170;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t174 = t80 / 0.4e1;
  t176 = t108 / 0.4e1;
  t177 = t15 * t15;
  t178 = 0.1e1 / t177;
  t179 = t178 * t17;
  t180 = t71 * t71;
  t181 = t38 * t180;
  t183 = t8 * t179 * t181;
  t184 = t183 / 0.6e1;
  t185 = t15 * t77;
  t187 = t8 * t185 * t72;
  t188 = t187 / 0.3e1;
  t189 = t96 * t71;
  t191 = t8 * t66 * t189;
  t192 = t67 * t10;
  t193 = 0.1e1 / t192;
  t194 = t9 * t193;
  t195 = -t68 + t194;
  t196 = t38 * t195;
  t198 = t8 * t66 * t196;
  t199 = t198 / 0.2e1;
  t201 = 0.1e1 / t76 / t10;
  t202 = t16 * t201;
  t204 = t8 * t202 * t38;
  t205 = t204 / 0.12e2;
  t207 = t8 * t78 * t96;
  t208 = t207 / 0.4e1;
  t210 = 0.1e1 / t82 / t27;
  t211 = t91 * t91;
  t216 = t84 * rho[0];
  t218 = 0.1e1 / t20 / t216;
  t223 = 0.80e2 / 0.9e1 * tau[0] * t218 - 0.10e2 / 0.9e1 * lapl[0] * t218;
  t229 = my_piecewise3(t28, 0.5e1 / 0.6e1 * t31 * t33 * t210 * t211 - 0.5e1 / 0.12e2 * t31 * t33 * t83 * t223, 0);
  t231 = t8 * t18 * t229;
  t232 = 0.3e1 / 0.8e1 * t231;
  t233 = t43 * t43;
  t234 = 0.1e1 / t233;
  t235 = t234 * t17;
  t236 = t101 * t101;
  t237 = t60 * t236;
  t239 = t8 * t235 * t237;
  t240 = t239 / 0.6e1;
  t241 = t43 * t77;
  t243 = t8 * t241 * t102;
  t244 = t243 / 0.3e1;
  t245 = -t195;
  t246 = t60 * t245;
  t248 = t8 * t100 * t246;
  t249 = t248 / 0.2e1;
  t250 = t44 * t201;
  t252 = t8 * t250 * t60;
  t253 = t252 / 0.12e2;
  t254 = -t184 - t188 - t191 - t199 + t205 - t208 - t232 - t240 - t244 - t249 + t253;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t74 - t174 - 0.3e1 / 0.4e1 * t98 - t104 - t176 + t10 * t254;

  t256 = t7 * t178;
  t257 = t5 * t256;
  t258 = t17 * t38;
  t259 = t113 * t71;
  t261 = t257 * t258 * t259;
  t264 = t8 * t185 * t114;
  t266 = t96 * t113;
  t268 = t8 * t66 * t266;
  t271 = 0.1e1 / t76 / t67;
  t272 = t15 * t271;
  t273 = t38 * t9;
  t275 = t8 * t272 * t273;
  t279 = t7 * t234;
  t280 = t5 * t279;
  t281 = t17 * t60;
  t282 = t118 * t101;
  t284 = t280 * t281 * t282;
  t287 = t8 * t241 * t119;
  t289 = t43 * t271;
  t290 = t60 * t9;
  t292 = t8 * t289 * t290;
  t295 = t137 * t101;
  t297 = t8 * t100 * t295;
  t300 = t8 * t106 * t137;
  t302 = -t261 / 0.6e1 - t264 / 0.6e1 - t268 / 0.2e1 - t275 / 0.2e1 - t187 / 0.6e1 + t205 - t207 / 0.8e1 - t284 / 0.6e1 - t287 / 0.6e1 + t292 / 0.2e1 - t243 / 0.6e1 + t253 - t297 / 0.2e1 - t300 / 0.8e1;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = t10 * t302 - t105 - t117 - t122 - t140 - t174 - t176 - t75 - t99;

  t305 = t113 * t113;
  t306 = t38 * t305;
  t308 = t8 * t179 * t306;
  t309 = t308 / 0.6e1;
  t310 = t264 / 0.3e1;
  t311 = t68 + t194;
  t312 = t38 * t311;
  t314 = t8 * t66 * t312;
  t315 = t314 / 0.2e1;
  t316 = t118 * t118;
  t317 = t60 * t316;
  t319 = t8 * t235 * t317;
  t320 = t319 / 0.6e1;
  t321 = t287 / 0.3e1;
  t322 = t137 * t118;
  t324 = t8 * t100 * t322;
  t325 = -t311;
  t326 = t60 * t325;
  t328 = t8 * t100 * t326;
  t329 = t328 / 0.2e1;
  t330 = t300 / 0.4e1;
  t332 = 0.1e1 / t123 / t54;
  t333 = t132 * t132;
  t338 = t125 * rho[1];
  t340 = 0.1e1 / t47 / t338;
  t345 = 0.80e2 / 0.9e1 * tau[1] * t340 - 0.10e2 / 0.9e1 * lapl[1] * t340;
  t351 = my_piecewise3(t55, 0.5e1 / 0.6e1 * t31 * t33 * t332 * t333 - 0.5e1 / 0.12e2 * t31 * t33 * t124 * t345, 0);
  t353 = t8 * t45 * t351;
  t354 = 0.3e1 / 0.8e1 * t353;
  t355 = -t309 - t310 - t315 + t205 - t320 - t321 - t324 - t329 + t253 - t330 - t354;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = -t116 - t174 - t121 - t176 - 0.3e1 / 0.4e1 * t139 + t10 * t355;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[4] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[5] = 0.0e0;

  t358 = t8 * t18 * t151;
  t360 = t7 * t15;
  t361 = t151 * t71;
  t366 = t29 * t30 * t32;
  t367 = t6 * t210;
  t370 = t366 * t367 * t22 * t91;
  t374 = t31 * t33 * t83 * t86;
  t377 = my_piecewise3(t28, -0.5e1 / 0.24e2 * t370 - 0.25e2 / 0.144e3 * t374, 0);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[0] = -t358 / 0.2e1 - t145 * t360 * t361 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t146 * t377;

  t382 = t8 * t45 * t160;
  t383 = t7 * t43;
  t384 = t160 * t101;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[1] = -t145 * t383 * t384 / 0.2e1 - t382 / 0.2e1;

  t389 = t360 * t151 * t113;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[2] = -t145 * t389 / 0.2e1 - t358 / 0.2e1;

  t394 = t383 * t160 * t118;
  t397 = t6 * t332;
  t400 = t366 * t397 * t49 * t132;
  t404 = t31 * t33 * t124 * t127;
  t407 = my_piecewise3(t55, -0.5e1 / 0.24e2 * t400 - 0.25e2 / 0.144e3 * t404, 0);
  t408 = t155 * t407;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[3] = -t382 / 0.2e1 - t145 * t394 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t408;

  t412 = t8 * t18 * t165;
  t414 = t165 * t71;
  t421 = my_piecewise3(t28, 0.5e1 / 0.3e1 * t370 + 0.25e2 / 0.18e2 * t374, 0);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[0] = -t412 / 0.2e1 - t145 * t360 * t414 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t146 * t421;

  t426 = t8 * t45 * t170;
  t427 = t170 * t101;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[1] = -t145 * t383 * t427 / 0.2e1 - t426 / 0.2e1;

  t432 = t360 * t165 * t113;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[2] = -t145 * t432 / 0.2e1 - t412 / 0.2e1;

  t437 = t383 * t170 * t118;
  t443 = my_piecewise3(t55, 0.5e1 / 0.3e1 * t400 + 0.25e2 / 0.18e2 * t404, 0);
  t444 = t155 * t443;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[3] = -t426 / 0.2e1 - t145 * t437 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t444;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[4] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[5] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[4] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[5] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[4] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[5] = 0.0e0;

  t448 = 0.1e1 / t19 / t216;
  t451 = t31 * t33 * t210 * t448;
  t453 = my_piecewise3(t28, 0.5e1 / 0.96e2 * t451, 0);
  t454 = t146 * t453;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[0] = -0.3e1 / 0.8e1 * t145 * t454;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[1] = 0.0e0;

  t458 = 0.1e1 / t46 / t338;
  t461 = t31 * t33 * t332 * t458;
  t463 = my_piecewise3(t55, 0.5e1 / 0.96e2 * t461, 0);
  t464 = t155 * t463;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[2] = -0.3e1 / 0.8e1 * t145 * t464;

  t468 = my_piecewise3(t28, -0.5e1 / 0.12e2 * t451, 0);
  t469 = t146 * t468;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[0] = -0.3e1 / 0.8e1 * t145 * t469;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[2] = 0.0e0;

  t473 = my_piecewise3(t55, -0.5e1 / 0.12e2 * t461, 0);
  t474 = t155 * t473;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[3] = -0.3e1 / 0.8e1 * t145 * t474;

  t478 = my_piecewise3(t28, 0.10e2 / 0.3e1 * t451, 0);
  t479 = t146 * t478;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[0] = -0.3e1 / 0.8e1 * t145 * t479;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[1] = 0.0e0;

  t483 = my_piecewise3(t55, 0.10e2 / 0.3e1 * t461, 0);
  t484 = t155 * t483;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[2] = -0.3e1 / 0.8e1 * t145 * t484;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t491 = t204 / 0.4e1;
  t493 = t252 / 0.4e1;
  t497 = t8 * t202 * t96;
  t500 = t8 * t78 * t229;
  t502 = t82 * t82;
  t503 = 0.1e1 / t502;
  t513 = t84 * t84;
  t515 = 0.1e1 / t20 / t513;
  t526 = my_piecewise3(t28, -0.5e1 / 0.2e1 * t31 * t33 * t503 * t211 * t91 + 0.5e1 / 0.2e1 * t366 * t367 * t91 * t223 - 0.5e1 / 0.12e2 * t31 * t33 * t83 * (-0.880e3 / 0.27e2 * tau[0] * t515 + 0.110e3 / 0.27e2 * lapl[0] * t515), 0);
  t531 = 0.1e1 / t177 / t14;
  t532 = t531 * t17;
  t538 = t178 * t77;
  t540 = t8 * t538 * t181;
  t546 = t15 * t201;
  t548 = t8 * t546 * t72;
  t551 = 0.1e1 / t233 / t42;
  t552 = t551 * t17;
  t558 = t234 * t77;
  t560 = t8 * t558 * t237;
  t567 = t43 * t201;
  t569 = t8 * t567 * t102;
  t576 = t8 * t185 * t189;
  t578 = t8 * t185 * t196;
  t588 = t67 * t67;
  t590 = t9 / t588;
  t592 = 0.3e1 * t193 - 0.3e1 * t590;
  t600 = 0.5e1 / 0.36e2 * t8 * t16 * t271 * t38;
  t602 = t8 * t241 * t246;
  t612 = 0.5e1 / 0.36e2 * t8 * t44 * t271 * t60;
  t613 = t569 / 0.3e1 - t8 * t179 * t96 * t180 / 0.2e1 - t576 - t578 / 0.2e1 - 0.3e1 / 0.2e1 * t8 * t66 * t229 * t71 - 0.3e1 / 0.2e1 * t8 * t66 * t96 * t195 - t8 * t66 * t38 * t592 / 0.2e1 - t600 - t602 / 0.2e1 + t8 * t100 * t60 * t592 / 0.2e1 - t612;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = -t183 / 0.2e1 - t187 - t239 / 0.2e1 - t243 - 0.3e1 * t191 - 0.3e1 / 0.2e1 * t198 + t491 - 0.3e1 / 0.2e1 * t248 + t493 - 0.3e1 / 0.4e1 * t207 - 0.9e1 / 0.8e1 * t231 + t10 * (t497 / 0.4e1 - 0.3e1 / 0.8e1 * t500 - 0.3e1 / 0.8e1 * t8 * t18 * t526 + t8 * t532 * t38 * t180 * t71 / 0.9e1 - t540 / 0.6e1 - t257 * t258 * t71 * t195 / 0.2e1 + t548 / 0.3e1 + t8 * t552 * t60 * t236 * t101 / 0.9e1 - t560 / 0.6e1 - t280 * t281 * t101 * t245 / 0.2e1 + t613);

  t620 = t261 / 0.3e1;
  t621 = t284 / 0.3e1;
  t626 = t271 * t60;
  t632 = t5 * t7 * t531;
  t640 = t257 * t77 * t38 * t259 / 0.9e1;
  t641 = t271 * t38;
  t647 = t5 * t7 * t551;
  t655 = t280 * t77 * t60 * t282 / 0.9e1;
  t665 = t8 * t546 * t114;
  t668 = 0.1e1 / t76 / t192;
  t671 = t8 * t15 * t668 * t273;
  t677 = t8 * t567 * t119;
  t685 = t8 * t241 * t295 / 0.3e1;
  t688 = t8 * t185 * t266 / 0.3e1;
  t689 = -t280 * t281 * t118 * t245 / 0.6e1 + t280 * t626 * t9 * t101 / 0.3e1 + t632 * t258 * t113 * t180 / 0.9e1 - t640 - t257 * t641 * t9 * t71 / 0.3e1 + t647 * t281 * t118 * t236 / 0.9e1 - t655 - t257 * t17 * t96 * t259 / 0.3e1 - t257 * t258 * t113 * t195 / 0.6e1 + t665 / 0.9e1 + 0.7e1 / 0.6e1 * t671 - t8 * t272 * t96 * t9 + t677 / 0.9e1 - t8 * t235 * t137 * t236 / 0.6e1 - t685 - t688;
  t696 = t8 * t43 * t668 * t290;
  t718 = t8 * t250 * t137;
  t720 = -t8 * t66 * t229 * t113 / 0.2e1 - 0.7e1 / 0.6e1 * t696 - t8 * t100 * t137 * t245 / 0.2e1 - t540 / 0.18e2 + 0.2e1 / 0.9e1 * t548 - t560 / 0.18e2 + 0.2e1 / 0.9e1 * t569 - t576 / 0.3e1 - t578 / 0.6e1 - t602 / 0.6e1 + t497 / 0.6e1 - t500 / 0.8e1 - t600 - t612 - t8 * t272 * t38 / 0.2e1 + t8 * t289 * t60 / 0.2e1 + t718 / 0.12e2;
  t723 = t292 - t297 - t330 - t207 / 0.2e1 - t232 - t620 - t310 - t275 - t621 - t321 + t10 * (t689 + t720);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[1] = -t184 - 0.2e1 / 0.3e1 * t187 - t240 - 0.2e1 / 0.3e1 * t243 - t191 - t199 + t491 - t249 + t493 - t268 + t723;

  t765 = -t193 - 0.3e1 * t590;
  t783 = t8 * t538 * t306;
  t785 = -t257 * t258 * t311 * t71 / 0.6e1 + t647 * t281 * t316 * t101 / 0.9e1 + t280 * t626 * t118 * t9 / 0.3e1 - t280 * t17 * t137 * t282 / 0.3e1 - t280 * t281 * t325 * t101 / 0.6e1 - t257 * t641 * t113 * t9 / 0.3e1 + t632 * t258 * t305 * t71 / 0.9e1 - t640 - t655 - t8 * t179 * t96 * t305 / 0.6e1 - t8 * t66 * t96 * t311 / 0.2e1 - t8 * t66 * t38 * t765 / 0.2e1 + t8 * t289 * t137 * t9 + t8 * t100 * t60 * t765 / 0.2e1 - t8 * t100 * t351 * t101 / 0.2e1 - t783 / 0.18e2;
  t787 = t8 * t185 * t312;
  t790 = t8 * t558 * t317;
  t793 = t8 * t241 * t322;
  t796 = t8 * t241 * t326;
  t807 = t8 * t106 * t351;
  t809 = -t787 / 0.6e1 - t790 / 0.18e2 - t793 / 0.3e1 - t796 / 0.6e1 + 0.2e1 / 0.9e1 * t665 - t671 / 0.3e1 + 0.2e1 / 0.9e1 * t677 - t685 - t688 + t696 / 0.3e1 + t548 / 0.9e1 + t569 / 0.9e1 + t497 / 0.12e2 - t600 - t612 + t718 / 0.6e1 - t807 / 0.8e1;
  t812 = -t329 - t208 - t354 - t620 - 0.2e1 / 0.3e1 * t264 - t275 - t621 - 0.2e1 / 0.3e1 * t287 - t309 - t320 + t10 * (t785 + t809);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[2] = -t188 - t244 + t491 + t493 - t268 + t292 - t297 - t300 / 0.2e1 - t315 - t324 + t812;

  t820 = t123 * t123;
  t821 = 0.1e1 / t820;
  t831 = t125 * t125;
  t833 = 0.1e1 / t47 / t831;
  t844 = my_piecewise3(t55, -0.5e1 / 0.2e1 * t31 * t33 * t821 * t333 * t132 + 0.5e1 / 0.2e1 * t366 * t397 * t132 * t345 - 0.5e1 / 0.12e2 * t31 * t33 * t124 * (-0.880e3 / 0.27e2 * tau[1] * t833 + 0.110e3 / 0.27e2 * lapl[1] * t833), 0);
  t873 = -0.3e1 * t193 - 0.3e1 * t590;
  t898 = -t280 * t281 * t118 * t325 / 0.2e1 - t8 * t66 * t38 * t873 / 0.2e1 - t8 * t235 * t137 * t316 / 0.2e1 - 0.3e1 / 0.2e1 * t8 * t100 * t351 * t118 - 0.3e1 / 0.2e1 * t8 * t100 * t137 * t325 + t8 * t100 * t60 * t873 / 0.2e1 + t665 / 0.3e1 + t677 / 0.3e1 - t600 - t612 + t718 / 0.4e1;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[3] = t491 + t493 - 0.3e1 / 0.4e1 * t300 - 0.3e1 / 0.2e1 * t314 - 0.3e1 * t324 - 0.3e1 / 0.2e1 * t328 - 0.9e1 / 0.8e1 * t353 - t264 - t287 - t308 / 0.2e1 - t319 / 0.2e1 + t10 * (-0.3e1 / 0.8e1 * t8 * t45 * t844 - 0.3e1 / 0.8e1 * t807 - t783 / 0.6e1 - t787 / 0.2e1 - t790 / 0.6e1 - t793 - t796 / 0.2e1 + t8 * t532 * t38 * t305 * t113 / 0.9e1 - t257 * t258 * t113 * t311 / 0.2e1 + t8 * t552 * t60 * t316 * t118 / 0.9e1 + t898);

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[8] = 0.0e0;

  t902 = t8 * t66 * t361;
  t906 = t8 * t78 * t151 / 0.6e1;
  t908 = t8 * t18 * t377;
  t920 = t6 * t503;
  t923 = t366 * t920 * t22 * t211;
  t927 = t366 * t367 * t86 * t91;
  t931 = t366 * t367 * t22 * t223;
  t935 = t31 * t33 * t83 * t218;
  t938 = my_piecewise3(t28, 0.5e1 / 0.8e1 * t923 + 0.25e2 / 0.36e2 * t927 - 0.5e1 / 0.24e2 * t931 + 0.25e2 / 0.54e2 * t935, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[0] = -0.4e1 / 0.3e1 * t902 - t906 - t908 - t145 * t256 * t151 * t180 / 0.6e1 - t145 * t360 * t377 * t71 - t145 * t360 * t151 * t195 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t146 * t938;

  t943 = t8 * t100 * t384;
  t947 = t8 * t106 * t160 / 0.6e1;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[1] = -0.4e1 / 0.3e1 * t943 - t947 - t145 * t279 * t160 * t236 / 0.6e1 - t145 * t383 * t160 * t245 / 0.2e1;

  t959 = t17 * t2 * t4;
  t960 = t959 * t389;
  t963 = t144 * t4 * t7;
  t973 = t201 * t2 * t4;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[2] = -0.2e1 / 0.3e1 * t902 - t906 - t908 / 0.2e1 - 0.2e1 / 0.3e1 * t960 - t963 * t178 * t151 * t259 / 0.6e1 - t145 * t360 * t377 * t113 / 0.2e1 - t973 * t360 * t151 * t9 / 0.2e1;

  t979 = t959 * t394;
  t989 = t959 * t408;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[3] = -0.2e1 / 0.3e1 * t943 - t947 - 0.2e1 / 0.3e1 * t979 - t963 * t234 * t160 * t282 / 0.6e1 + t973 * t383 * t160 * t9 / 0.2e1 - t989 / 0.2e1 - t145 * t383 * t407 * t101 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[4] = -0.4e1 / 0.3e1 * t960 - t906 - t145 * t256 * t151 * t305 / 0.6e1 - t145 * t360 * t151 * t311 / 0.2e1;

  t1016 = t6 * t821;
  t1019 = t366 * t1016 * t49 * t333;
  t1023 = t366 * t397 * t127 * t132;
  t1027 = t366 * t397 * t49 * t345;
  t1031 = t31 * t33 * t124 * t340;
  t1034 = my_piecewise3(t55, 0.5e1 / 0.8e1 * t1019 + 0.25e2 / 0.36e2 * t1023 - 0.5e1 / 0.24e2 * t1027 + 0.25e2 / 0.54e2 * t1031, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2lapl[5] = -0.4e1 / 0.3e1 * t979 - t947 - t989 - t145 * t279 * t160 * t316 / 0.6e1 - t145 * t383 * t407 * t118 - t145 * t383 * t160 * t325 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t155 * t1034;

  t1039 = t8 * t66 * t414;
  t1043 = t8 * t78 * t165 / 0.6e1;
  t1045 = t8 * t18 * t421;
  t1062 = my_piecewise3(t28, -0.5e1 * t923 - 0.50e2 / 0.9e1 * t927 + 0.5e1 / 0.3e1 * t931 - 0.100e3 / 0.27e2 * t935, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[0] = -0.4e1 / 0.3e1 * t1039 - t1043 - t1045 - t145 * t256 * t165 * t180 / 0.6e1 - t145 * t360 * t421 * t71 - t145 * t360 * t165 * t195 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t146 * t1062;

  t1067 = t8 * t100 * t427;
  t1071 = t8 * t106 * t170 / 0.6e1;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[1] = -0.4e1 / 0.3e1 * t1067 - t1071 - t145 * t279 * t170 * t236 / 0.6e1 - t145 * t383 * t170 * t245 / 0.2e1;

  t1082 = t959 * t432;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[2] = -0.2e1 / 0.3e1 * t1039 - t1043 - t1045 / 0.2e1 - 0.2e1 / 0.3e1 * t1082 - t963 * t178 * t165 * t259 / 0.6e1 - t145 * t360 * t421 * t113 / 0.2e1 - t973 * t360 * t165 * t9 / 0.2e1;

  t1097 = t959 * t437;
  t1107 = t959 * t444;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[3] = -0.2e1 / 0.3e1 * t1067 - t1071 - 0.2e1 / 0.3e1 * t1097 - t963 * t234 * t170 * t282 / 0.6e1 + t973 * t383 * t170 * t9 / 0.2e1 - t1107 / 0.2e1 - t145 * t383 * t443 * t101 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[4] = -0.4e1 / 0.3e1 * t1082 - t1043 - t145 * t256 * t165 * t305 / 0.6e1 - t145 * t360 * t165 * t311 / 0.2e1;

  t1139 = my_piecewise3(t55, -0.5e1 * t1019 - 0.50e2 / 0.9e1 * t1023 + 0.5e1 / 0.3e1 * t1027 - 0.100e3 / 0.27e2 * t1031, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2tau[5] = -0.4e1 / 0.3e1 * t1097 - t1071 - t1107 - t145 * t279 * t170 * t316 / 0.6e1 - t145 * t383 * t443 * t118 - t145 * t383 * t170 * t325 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t155 * t1139;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[10] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[11] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[10] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmalapl[11] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[10] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigmatau[11] = 0.0e0;

  t1143 = t959 * t454;
  t1151 = t366 * t920 * t448 * t91;
  t1157 = t31 * t33 * t210 / t19 / t513;
  t1160 = my_piecewise3(t28, -0.5e1 / 0.32e2 * t1151 - 0.25e2 / 0.144e3 * t1157, 0);
  t1164 = t959 * t464;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapl2[0] = -t145 * t360 * t453 * t113 / 0.2e1 - t1143 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapl2[1] = 0.0e0;

  t1180 = t366 * t1016 * t458 * t132;
  t1186 = t31 * t33 * t332 / t46 / t831;
  t1189 = my_piecewise3(t55, -0.5e1 / 0.32e2 * t1180 - 0.25e2 / 0.144e3 * t1186, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapl2[2] = -t1164 / 0.2e1 - t145 * t383 * t463 * t118 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t155 * t1189;

  t1193 = t959 * t469;
  t1202 = my_piecewise3(t28, 0.5e1 / 0.4e1 * t1151 + 0.25e2 / 0.18e2 * t1157, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[0] = -t1193 / 0.2e1 - t145 * t360 * t468 * t71 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t146 * t1202;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[2] = 0.0e0;

  t1206 = t959 * t474;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[3] = -t145 * t383 * t473 * t101 / 0.2e1 - t1206 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[4] = -t145 * t360 * t468 * t113 / 0.2e1 - t1193 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[6] = 0.0e0;

  t1223 = my_piecewise3(t55, 0.5e1 / 0.4e1 * t1180 + 0.25e2 / 0.18e2 * t1186, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rholapltau[7] = -t1206 / 0.2e1 - t145 * t383 * t473 * t118 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t155 * t1223;

  t1227 = t959 * t479;
  t1236 = my_piecewise3(t28, -0.10e2 * t1151 - 0.100e3 / 0.9e1 * t1157, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[0] = -t1227 / 0.2e1 - t145 * t360 * t478 * t71 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t146 * t1236;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[1] = 0.0e0;

  t1240 = t959 * t484;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[2] = -t145 * t383 * t483 * t101 / 0.2e1 - t1240 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[3] = -t145 * t360 * t478 * t113 / 0.2e1 - t1227 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[4] = 0.0e0;

  t1257 = my_piecewise3(t55, -0.10e2 * t1180 - 0.100e3 / 0.9e1 * t1186, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhotau2[5] = -t1240 / 0.2e1 - t145 * t383 * t483 * t118 / 0.2e1 - 0.3e1 / 0.8e1 * t145 * t155 * t1257;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[10] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2lapl[11] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[10] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma2tau[11] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapl2[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[10] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmalapltau[11] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[0] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigmatau2[8] = 0.0e0;

  t1265 = t31 * t33 * t503 / t513 / rho[0];
  t1267 = my_piecewise3(t28, 0.5e1 / 0.128e3 * t1265, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl3[0] = -0.3e1 / 0.8e1 * t145 * t146 * t1267;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl3[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl3[2] = 0.0e0;

  t1275 = t31 * t33 * t821 / t831 / rho[1];
  t1277 = my_piecewise3(t55, 0.5e1 / 0.128e3 * t1275, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl3[3] = -0.3e1 / 0.8e1 * t145 * t155 * t1277;

  t1282 = my_piecewise3(t28, -0.5e1 / 0.16e2 * t1265, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[0] = -0.3e1 / 0.8e1 * t145 * t146 * t1282;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[4] = 0.0e0;

  t1287 = my_piecewise3(t55, -0.5e1 / 0.16e2 * t1275, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapl2tau[5] = -0.3e1 / 0.8e1 * t145 * t155 * t1287;

  t1292 = my_piecewise3(t28, 0.5e1 / 0.2e1 * t1265, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[0] = -0.3e1 / 0.8e1 * t145 * t146 * t1292;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[4] = 0.0e0;

  t1297 = my_piecewise3(t55, 0.5e1 / 0.2e1 * t1275, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3lapltau2[5] = -0.3e1 / 0.8e1 * t145 * t155 * t1297;

  t1302 = my_piecewise3(t28, -0.20e2 * t1265, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3tau3[0] = -0.3e1 / 0.8e1 * t145 * t146 * t1302;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3tau3[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3tau3[2] = 0.0e0;

  t1307 = my_piecewise3(t55, -0.20e2 * t1275, 0);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3tau3[3] = -0.3e1 / 0.8e1 * t145 * t155 * t1307;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


#endif

#endif

#endif

#endif


}

