/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2020 (X86 64 LINUX)
  Maple source      : ./maple/gga_exc/gga_c_chachiyo.mpl
  Type of functional: gga_exc
*/

#define maple2c_order 4
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC | XC_FLAGS_I_HAVE_KXC | XC_FLAGS_I_HAVE_LXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t5, t7, t8, t9, t13;
  double t14, t16, t17, t18, t22, t23, t24, t25;
  double t26, t27, t29, t33, t34, t35, t36, t37;
  double t38;

#ifndef XC_DONT_COMPILE_VXC
  double t39, t48, t49, t50, t53, t54, t55, t56;
  double t57, t61, t62, t64, t66, t67, t71, t75;
  double t76, t78;

#ifndef XC_DONT_COMPILE_FXC
  double t80, t81, t84, t94, t95, t98, t99, t100;
  double t101, t104, t105, t108, t112, t113, t114, t120;
  double t122, t125, t128, t130, t135, t136, t137, t138;
  double t140, t142, t143, t144, t145, t149, t152, t159;
  double t164, t165, t166, t168, t172, t173, t174, t175;
  double t177, t178, t181;

#ifndef XC_DONT_COMPILE_KXC
  double t184, t187, t193, t194, t195, t200, t202, t203;
  double t207, t208, t211, t214, t215, t218, t221, t226;
  double t237, t238, t241, t242, t243, t244, t247, t248;
  double t249, t256, t263, t265, t272, t277, t282, t285;
  double t287, t292, t294, t299, t300, t301, t303, t305;
  double t306, t310, t313, t322, t323, t332, t337, t338;
  double t339, t340, t346, t348, t349, t352, t353, t355;
  double t356, t360, t363, t364, t371, t375, t379, t380;
  double t382, t383, t385, t389, t392, t393;

#ifndef XC_DONT_COMPILE_LXC
  double t405, t410, t411, t412, t415, t416, t418, t419;
  double t439, t440, t445, t447, t448, t449, t460, t468;
  double t473, t474, t532, t543, t556, t563, t578, t581;
  double t586, t626, t675, t680, t706, t760, t774, t778;
  double t784, t786, t787, t818, t819;
#endif

#endif

#endif

#endif

#endif


  gga_c_chachiyo_params *params;

  assert(p->params != NULL);
  params = (gga_c_chachiyo_params * )(p->params);

  t1 = M_CBRT3;
  t2 = t1 * t1;
  t3 = params->bp * t2;
  t5 = POW_1_3(0.1e1 / M_PI);
  t7 = M_CBRT4;
  t8 = 0.1e1 / t5 * t7;
  t9 = POW_1_3(rho[0]);
  t13 = params->bp * t1;
  t14 = t5 * t5;
  t16 = t7 * t7;
  t17 = 0.1e1 / t14 * t16;
  t18 = t9 * t9;
  t22 = 0.1e1 + t3 * t8 * t9 / 0.3e1 + t13 * t17 * t18 / 0.3e1;
  t23 = log(t22);
  t24 = params->ap * t23;
  t25 = M_CBRTPI;
  t26 = t2 * t25;
  t27 = rho[0] * rho[0];
  t29 = 0.1e1 / t9 / t27;
  t33 = 0.1e1 + t26 * t29 * sigma[0] / 0.48e2;
  t34 = 0.1e1 / params->ap;
  t35 = params->h * t34;
  t36 = 0.1e1 / t23;
  t37 = t35 * t36;
  t38 = pow(t33, t37);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = t24 * t38;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t39 = rho[0] * params->ap;
  t48 = t3 * t8 / t18 / 0.9e1 + 0.2e1 / 0.9e1 * t13 * t17 / t9;
  t49 = 0.1e1 / t22;
  t50 = t48 * t49;
  t53 = t23 * t38;
  t54 = t23 * t23;
  t55 = 0.1e1 / t54;
  t56 = t35 * t55;
  t57 = log(t33);
  t61 = t35 * t36 * t2;
  t62 = t27 * rho[0];
  t64 = 0.1e1 / t9 / t62;
  t66 = 0.1e1 / t33;
  t67 = sigma[0] * t66;
  t71 = -t56 * t50 * t57 - 0.7e1 / 0.144e3 * t61 * t25 * t64 * t67;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t39 * t50 * t38 + t39 * t53 * t71 + (t24 * t38);

  t75 = 0.1e1 / t9 / rho[0];
  t76 = t75 * t38;
  t78 = t26 * t66;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = t76 * params->h * t78 / 0.48e2;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t80 = params->ap * t48;
  t81 = t49 * t38;
  t84 = t38 * t71;
  t94 = -0.2e1 / 0.27e2 * t3 * t8 / t18 / rho[0] - 0.2e1 / 0.27e2 * t13 * t17 * t75;
  t95 = t94 * t49;
  t98 = t48 * t48;
  t99 = t22 * t22;
  t100 = 0.1e1 / t99;
  t101 = t98 * t100;
  t104 = t39 * t48;
  t105 = t81 * t71;
  t108 = t71 * t71;
  t112 = 0.1e1 / t54 / t23;
  t113 = t35 * t112;
  t114 = t101 * t57;
  t120 = t55 * t48;
  t122 = t35 * t120 * t49;
  t125 = t26 * t64 * sigma[0] * t66;
  t128 = t27 * t27;
  t130 = 0.1e1 / t9 / t128;
  t135 = t36 * t1;
  t136 = t35 * t135;
  t137 = t25 * t25;
  t138 = t128 * t27;
  t140 = 0.1e1 / t18 / t138;
  t142 = sigma[0] * sigma[0];
  t143 = t33 * t33;
  t144 = 0.1e1 / t143;
  t145 = t142 * t144;
  t149 = 0.2e1 * t113 * t114 - t56 * t95 * t57 + t56 * t114 + 0.7e1 / 0.72e2 * t122 * t125 + 0.35e2 / 0.216e3 * t61 * t25 * t130 * t67 - 0.49e2 / 0.6912e4 * t136 * t137 * t140 * t145;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t39 * t101 * t38 + t39 * t53 * t108 + t39 * t53 * t149 + t39 * t95 * t38 + 0.2e1 * t104 * t105 + 0.2e1 * t24 * t84 + 0.2e1 * t80 * t81;

  t152 = t29 * t38;
  t159 = params->h * t2 * t25 * t66;
  t164 = 0.1e1 / t18 / t128 * t38;
  t165 = t164 * params->h;
  t166 = t1 * t137;
  t168 = t166 * t144 * sigma[0];
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = -t152 * params->h * t78 / 0.36e2 + t76 * t71 * t159 / 0.48e2 + 0.7e1 / 0.2304e4 * t165 * t168;

  t172 = 0.1e1 / t18 / t62;
  t173 = t172 * t38;
  t174 = params->h * params->h;
  t175 = t174 * t34;
  t177 = t137 * t144;
  t178 = t135 * t177;
  t181 = t166 * t144;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = t173 * t175 * t178 / 0.768e3 - t173 * params->h * t181 / 0.768e3;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t184 = t81 * t108;
  t187 = params->ap * t94;
  t193 = t39 * t94;
  t194 = t100 * t38;
  t195 = t194 * t48;
  t200 = t98 * t48;
  t202 = 0.1e1 / t99 / t22;
  t203 = t200 * t202;
  t207 = t39 * t98;
  t208 = t194 * t71;
  t211 = t81 * t149;
  t214 = t39 * t23;
  t215 = t84 * t149;
  t218 = t108 * t71;
  t221 = params->ap * t98;
  t226 = t38 * t108;
  t237 = 0.10e2 / 0.81e2 * t3 * t8 / t18 / t27 + 0.8e1 / 0.81e2 * t13 * t17 * t29;
  t238 = t237 * t49;
  t241 = t54 * t54;
  t242 = 0.1e1 / t241;
  t243 = t35 * t242;
  t244 = t203 * t57;
  t247 = t48 * t100;
  t248 = t57 * t94;
  t249 = t247 * t248;
  t256 = t35 * t112 * t98 * t100;
  t263 = t55 * t94;
  t265 = t35 * t263 * t49;
  t272 = t35 * t55 * t98 * t100;
  t277 = t26 * t130 * sigma[0] * t66;
  t282 = t166 * t140 * t142 * t144;
  t285 = t128 * rho[0];
  t287 = 0.1e1 / t9 / t285;
  t292 = t128 * t62;
  t294 = 0.1e1 / t18 / t292;
  t299 = t128 * t128;
  t300 = t299 * t27;
  t301 = 0.1e1 / t300;
  t303 = t142 * sigma[0];
  t305 = 0.1e1 / t143 / t33;
  t306 = t303 * t305;
  t310 = -0.6e1 * t243 * t244 + 0.6e1 * t113 * t249 - 0.6e1 * t113 * t244 - 0.7e1 / 0.24e2 * t256 * t125 - t56 * t238 * t57 + 0.3e1 * t56 * t249 + 0.7e1 / 0.48e2 * t265 * t125 - 0.2e1 * t56 * t244 - 0.7e1 / 0.48e2 * t272 * t125 - 0.35e2 / 0.72e2 * t122 * t277 + 0.49e2 / 0.2304e4 * t122 * t282 - 0.455e3 / 0.648e3 * t61 * t25 * t287 * t67 + 0.245e3 / 0.3456e4 * t136 * t137 * t294 * t145 - 0.343e3 / 0.165888e6 * t37 * M_PI * t301 * t306;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = 0.3e1 * t24 * t38 * t149 + 0.2e1 * t39 * t203 * t38 + t39 * t53 * t218 + t39 * t238 * t38 + t39 * t53 * t310 + 0.3e1 * t104 * t184 + 0.3e1 * t104 * t211 + 0.3e1 * t193 * t105 + 0.6e1 * t80 * t105 + 0.3e1 * t187 * t81 - 0.3e1 * t193 * t195 - 0.3e1 * t221 * t194 - 0.3e1 * t207 * t208 + 0.3e1 * t214 * t215 + 0.3e1 * t24 * t226;

  t313 = t64 * t38;
  t322 = 0.1e1 / t18 / t285 * t38;
  t323 = t322 * params->h;
  t332 = t71 * params->h;
  t337 = 0.1e1 / t299 * t38;
  t338 = t337 * params->h;
  t339 = M_PI * t305;
  t340 = t339 * t142;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = 0.7e1 / 0.108e3 * t313 * params->h * t78 - t152 * t71 * t159 / 0.18e2 - 0.7e1 / 0.384e3 * t323 * t168 + t76 * t108 * t159 / 0.48e2 + t76 * t149 * t159 / 0.48e2 + 0.7e1 / 0.1152e4 * t164 * t332 * t168 + 0.49e2 / 0.55296e5 * t338 * t340;

  t346 = t71 * t174;
  t348 = t34 * t36;
  t349 = t348 * t181;
  t352 = t175 * t55;
  t353 = t173 * t352;
  t355 = t144 * t48 * t49;
  t356 = t166 * t355;
  t360 = 0.1e1 / t292 * t38;
  t363 = t305 * sigma[0];
  t364 = t36 * M_PI * t363;
  t371 = params->h * t1 * t177;
  t375 = t339 * sigma[0];
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = -0.11e2 / 0.2304e4 * t164 * t175 * t178 + t173 * t346 * t349 / 0.768e3 - t353 * t356 / 0.768e3 + 0.7e1 / 0.18432e5 * t360 * t175 * t364 + 0.11e2 / 0.2304e4 * t165 * t181 - t173 * t71 * t371 / 0.768e3 - 0.7e1 / 0.18432e5 * t360 * params->h * t375;

  t379 = 0.1e1 / t138 * t38;
  t380 = t174 * params->h;
  t382 = params->ap * params->ap;
  t383 = 0.1e1 / t382;
  t385 = t383 * t55 * t339;
  t389 = t348 * t339;
  t392 = params->h * M_PI;
  t393 = t392 * t305;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = t379 * t380 * t385 / 0.12288e5 - t379 * t174 * t389 / 0.4096e4 + t379 * t393 / 0.6144e4;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t405 = (-0.80e2 / 0.243e3 * t3 * t8 * t172 - 0.56e2 / 0.243e3 * t13 * t17 * t64) * t49;
  t410 = t94 * t94;
  t411 = t410 * t100;
  t412 = t411 * t57;
  t415 = t98 * t98;
  t416 = t99 * t99;
  t418 = t415 / t416;
  t419 = t418 * t57;
  t439 = t25 * M_PI;
  t440 = t36 * t439;
  t445 = t142 * t142;
  t447 = t143 * t143;
  t448 = 0.1e1 / t447;
  t449 = t448 * t2;
  t460 = t98 * t202 * t248;
  t468 = t247 * t57 * t237;
  t473 = -t56 * t405 * t57 + 0.3e1 * t56 * t412 + 0.6e1 * t56 * t419 + 0.36e2 * t243 * t419 + 0.6e1 * t113 * t412 + 0.22e2 * t113 * t419 + 0.24e2 * t35 / t241 / t23 * t419 - 0.10045e5 / 0.15552e5 * t136 * t137 / t18 / t299 * t145 - 0.2401e4 / 0.7962624e7 * t35 * t440 / t9 / t299 / t285 * t445 * t449 + 0.910e3 / 0.243e3 * t61 * t25 / t9 / t138 * t67 - 0.36e2 * t113 * t460 - 0.12e2 * t56 * t460 - 0.36e2 * t243 * t460 + 0.8e1 * t113 * t468 + 0.4e1 * t56 * t468;
  t474 = t299 * t62;
  t532 = t26 * t64;
  t543 = 0.1715e4 / 0.41472e5 * t37 * M_PI / t474 * t306 + 0.7e1 / 0.6e1 * t35 * t242 * t200 * t202 * t125 + 0.7e1 / 0.6e1 * t35 * t112 * t200 * t202 * t125 - 0.49e2 / 0.576e3 * t256 * t282 + 0.7e1 / 0.36e2 * t35 * t55 * t237 * t49 * t125 + 0.49e2 / 0.1152e4 * t265 * t282 + 0.7e1 / 0.18e2 * t35 * t55 * t200 * t202 * t125 - 0.49e2 / 0.1152e4 * t272 * t282 - 0.245e3 / 0.864e3 * t122 * t166 * t294 * t142 * t144 + 0.35e2 / 0.18e2 * t256 * t277 - 0.35e2 / 0.36e2 * t265 * t277 + 0.35e2 / 0.36e2 * t272 * t277 + 0.455e3 / 0.162e3 * t122 * t26 * t287 * sigma[0] * t66 + 0.343e3 / 0.41472e5 * t35 * t120 * t49 * M_PI * t301 * t303 * t305 - 0.7e1 / 0.6e1 * t35 * t112 * t48 * t100 * t532 * t67 * t94 - 0.7e1 / 0.12e2 * t35 * t263 * t100 * t532 * t67 * t48;
  t556 = t202 * t38;
  t563 = t39 * t237;
  t578 = t108 * t108;
  t581 = 0.12e2 * t24 * t215 + t39 * t405 * t38 + t39 * t53 * (t473 + t543) + 0.12e2 * t80 * t211 + 0.4e1 * t214 * t84 * t310 + 0.4e1 * t104 * t81 * t310 + 0.8e1 * t39 * t200 * t556 * t71 - 0.6e1 * t207 * t194 * t149 + 0.4e1 * t563 * t105 + 0.6e1 * t193 * t211 + 0.6e1 * t193 * t184 - 0.4e1 * t563 * t195 + 0.12e2 * t193 * t556 * t98 + 0.6e1 * t214 * t226 * t149 + t39 * t53 * t578;
  t586 = t149 * t149;
  t626 = 0.12e2 * t104 * t81 * t71 * t149 - 0.12e2 * t193 * t194 * t71 * t48 + 0.4e1 * t104 * t81 * t218 - 0.6e1 * t207 * t194 * t108 + 0.8e1 * params->ap * t200 * t556 + 0.4e1 * t24 * t38 * t218 + 0.4e1 * params->ap * t237 * t81 + 0.4e1 * t24 * t38 * t310 - 0.3e1 * t39 * t411 * t38 - 0.6e1 * t39 * t418 * t38 + 0.3e1 * t39 * t53 * t586 + 0.12e2 * t187 * t105 + 0.12e2 * t80 * t184 - 0.12e2 * t187 * t195 - 0.12e2 * t221 * t208;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = t581 + t626;

  t675 = t439 * t448;
  t680 = t299 * rho[0];
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[0] = -t152 * t108 * t159 / 0.12e2 - 0.7e1 / 0.128e3 * t322 * t332 * t168 + t76 * t332 * t26 * t66 * t149 / 0.16e2 + t76 * t218 * t159 / 0.48e2 + 0.7e1 / 0.768e3 * t164 * t108 * params->h * t168 + 0.7e1 / 0.768e3 * t164 * t149 * params->h * t168 - 0.35e2 / 0.162e3 * t130 * t38 * params->h * t78 + 0.7e1 / 0.36e2 * t313 * t71 * t159 + 0.1169e4 / 0.10368e5 * t140 * t38 * params->h * t168 - t152 * t149 * t159 / 0.12e2 + t76 * t310 * t159 / 0.48e2 + 0.49e2 / 0.18432e5 * t337 * t71 * t392 * t305 * t142 + 0.343e3 / 0.2654208e7 / t9 / t474 * t38 * params->h * t675 * t303 * t2 - 0.343e3 / 0.27648e5 / t680 * t38 * params->h * t340;

  t706 = 0.1e1 / t9 / t300 * t38;
  t760 = t166 * t144 * t98 * t100;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[0] = -0.7e1 / 0.1728e4 * t337 * t175 * t364 - t173 * t108 * t371 / 0.768e3 - 0.77e2 / 0.3456e4 * t323 * t181 + 0.11e2 / 0.1152e4 * t164 * t71 * t371 - t173 * t149 * t371 / 0.768e3 - 0.7e1 / 0.9216e4 * t360 * t71 * t392 * t363 - 0.49e2 / 0.884736e6 * t706 * params->h * t675 * t142 * t2 + 0.11e2 / 0.1152e4 * t164 * t352 * t356 + t173 * t108 * t174 * t349 / 0.768e3 - t353 * t166 * t144 * t94 * t49 / 0.768e3 - 0.7e1 / 0.9216e4 * t360 * t352 * t339 * t50 * sigma[0] + 0.77e2 / 0.3456e4 * t322 * t175 * t178 - 0.11e2 / 0.1152e4 * t164 * t346 * t349 + t173 * t149 * t174 * t349 / 0.768e3 + 0.7e1 / 0.9216e4 * t360 * t346 * t348 * t375 + 0.49e2 / 0.884736e6 * t706 * t175 * t440 * t448 * t142 * t2 + 0.7e1 / 0.1728e4 * t338 * t375 - t173 * t346 * t34 * t55 * t1 * t137 * t355 / 0.384e3 + t353 * t760 / 0.768e3 + t173 * t175 * t112 * t760 / 0.384e3;

  t774 = t380 * t383;
  t778 = t305 * t48 * t49;
  t784 = 0.1e1 / t9 / t680 * t38;
  t786 = t55 * t439;
  t787 = t449 * sigma[0];
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[0] = -t360 * t380 * t385 / 0.2048e4 + t379 * t71 * t380 * t385 / 0.12288e5 - t379 * t774 * t112 * M_PI * t778 / 0.6144e4 + 0.7e1 / 0.589824e6 * t784 * t774 * t786 * t787 + 0.3e1 / 0.2048e4 * t360 * t174 * t389 - t379 * t346 * t389 / 0.4096e4 + t379 * t175 * t55 * M_PI * t778 / 0.4096e4 - 0.7e1 / 0.196608e6 * t784 * t175 * t440 * t787 - t360 * t393 / 0.1024e4 + t379 * t71 * t393 / 0.6144e4 + 0.7e1 / 0.294912e6 * t784 * params->h * t675 * t2 * sigma[0];

  t818 = 0.1e1 / t9 / t299 * t38;
  t819 = t174 * t174;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[0] = t818 * t819 / t382 / params->ap * t112 * t2 * t675 / 0.589824e6 - t818 * t774 * t786 * t449 / 0.98304e5 + 0.11e2 / 0.589824e6 * t818 * t175 * t440 * t449 - t818 * params->h * t675 * t2 / 0.98304e5;

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t5, t7, t8, t9, t10;
  double t11, t14, t15, t17, t18, t19, t20, t23;
  double t24, t25, t26, t29, t32, t33, t35, t36;
  double t37, t38, t39, t40, t41, t42, t43, t44;
  double t46, t47, t50, t52, t53, t54, t55, t57;
  double t59, t63, t64, t65, t66;

#ifndef XC_DONT_COMPILE_VXC
  double t68, t72, t75, t77, t78, t83, t85, t87;
  double t88, t89, t90, t91, t92, t93, t95, t96;
  double t99, t102, t103, t105, t106, t107, t108, t109;
  double t110, t112, t113, t115, t116, t117, t118, t119;
  double t121, t122, t123, t125, t127, t130, t133, t134;
  double t136, t138, t139, t142, t143, t145, t146;

#ifndef XC_DONT_COMPILE_FXC
  double t147, t149, t150, t154, t156, t159, t160, t161;
  double t162, t164, t165, t166, t170, t171, t173, t175;
  double t176, t178, t179, t180, t181, t183, t184, t188;
  double t189, t192, t193, t195, t199, t200, t203, t206;
  double t209, t210, t214, t215, t218, t219, t220, t221;
  double t226, t227, t228, t230, t232, t233, t234, t236;
  double t237, t238, t239, t241, t242, t243, t244, t245;
  double t246, t247, t249, t250, t251, t253, t255, t257;
  double t260, t263, t266, t269, t272, t275, t276, t279;
  double t281, t286, t288, t289, t290, t293, t294, t299;
  double t302, t306, t309, t312, t315, t318, t319, t323;
  double t324, t326, t327, t330, t333, t334, t336, t338;
  double t339, t343, t344, t348, t349, t350, t352, t353;
  double t354, t355, t357, t359, t363, t364, t365, t368;
  double t369, t372, t374;

#ifndef XC_DONT_COMPILE_KXC
  double t375, t377, t379, t381, t385, t388, t392, t393;
  double t394, t396, t400, t402, t408, t410, t416, t419;
  double t420, t421, t422, t424, t425, t427, t429, t432;
  double t435, t437, t438, t441, t444, t445, t447, t450;
  double t452, t453, t456, t459, t462, t465, t466, t474;
  double t475, t477, t480, t482, t483, t487, t491, t492;
  double t497, t498, t500, t503, t504, t506, t510, t512;
  double t513, t517, t519, t520, t521, t522, t523, t524;
  double t527, t530, t531, t532, t537, t539, t546, t549;
  double t550, t551, t553, t560, t563, t565, t566, t569;
  double t572, t575, t578, t588, t591, t601, t604, t605;
  double t607, t608, t610, t611, t613, t614, t615, t621;
  double t622, t625, t627, t628, t632, t634, t638, t639;
  double t642, t644, t645, t648, t650, t653, t656, t658;
  double t661, t666, t671, t674, t679, t682, t685, t688;
  double t689, t692, t700, t702, t704, t707, t709, t717;
  double t718, t719, t721, t724, t726, t727, t728, t734;
  double t735, t744, t747, t750, t756, t759, t764, t767;
  double t770, t771, t779, t780, t782, t785, t786, t793;
  double t798, t799, t801, t803, t804, t806, t807, t810;
  double t811, t812, t813, t815, t818, t820, t822, t823;
  double t825, t826, t827, t828, t829, t830, t831, t833;
  double t837, t840, t843, t846, t848, t850, t853, t856;
  double t858, t861, t868, t869, t870, t871, t872, t874;
  double t875, t877, t878, t881, t882, t883, t884, t885;
  double t886, t887, t888, t889, t891, t892, t893, t896;
  double t897, t898, t899, t902, t903, t905, t906, t909;
  double t910, t912, t913, t914, t915, t917, t918, t919;
  double t922, t930, t931, t932, t933, t934, t935, t936;
  double t938, t939, t940, t942, t943, t944;

#ifndef XC_DONT_COMPILE_LXC
  double t955, t958, t960, t969, t970, t973, t974, t976;
  double t979, t980, t981, t983, t985, t991, t994, t999;
  double t1000, t1001, t1003, t1005, t1007, t1013, t1014, t1020;
  double t1025, t1026, t1028, t1033, t1034, t1040, t1063, t1067;
  double t1069, t1075, t1077, t1078, t1084, t1085, t1092, t1093;
  double t1098, t1100, t1101, t1102, t1105, t1108, t1112, t1116;
  double t1120, t1122, t1129, t1132, t1133, t1135, t1137, t1139;
  double t1141, t1146, t1149, t1150, t1157, t1164, t1167, t1169;
  double t1171, t1175, t1186, t1189, t1202, t1208, t1209, t1212;
  double t1214, t1215, t1232, t1234, t1245, t1249, t1251, t1268;
  double t1299, t1317, t1332, t1335, t1337, t1338, t1339, t1342;
  double t1343, t1344, t1346, t1347, t1365, t1367, t1368, t1371;
  double t1374, t1378, t1379, t1380, t1382, t1383, t1386, t1388;
  double t1394, t1397, t1399, t1404, t1405, t1407, t1408, t1409;
  double t1415, t1416, t1421, t1423, t1425, t1428, t1436, t1448;
  double t1455, t1465, t1468, t1471, t1476, t1478, t1479, t1490;
  double t1530, t1540, t1541, t1546, t1550, t1554, t1556, t1558;
  double t1572, t1579, t1590, t1594, t1597, t1613, t1617, t1619;
  double t1624, t1634, t1645, t1656, t1666, t1668, t1669, t1671;
  double t1673, t1674, t1680, t1685, t1688, t1690, t1692, t1694;
  double t1696, t1701, t1726, t1730, t1747, t1757, t1761, t1763;
  double t1766, t1786, t1808, t1812, t1813, t1823, t1833, t1838;
  double t1844, t1845, t1849, t1859, t1877, t1883, t1896, t1909;
  double t1914, t1920, t1923, t1928, t1939, t1952, t1959, t1966;
  double t1980, t1983, t1994, t1995, t1997, t2001, t2002, t2004;
  double t2007, t2011, t2012, t2018, t2021, t2022, t2024, t2027;
  double t2032, t2035, t2039, t2043, t2045, t2049, t2050, t2051;
  double t2053, t2057, t2064, t2065, t2067, t2069, t2070, t2072;
  double t2075, t2078, t2079, t2083, t2086, t2087, t2089, t2092;
  double t2095, t2099, t2100, t2102, t2107, t2108, t2109, t2113;
  double t2115, t2118, t2121, t2122, t2123, t2126, t2128, t2129;
  double t2133, t2136, t2138, t2140, t2143, t2146, t2150, t2153;
  double t2156, t2160, t2162, t2166, t2175, t2178, t2188, t2191;
  double t2205, t2208, t2209, t2212, t2214, t2217, t2218, t2221;
  double t2222, t2225, t2226, t2227, t2229, t2232, t2233, t2234;
  double t2235, t2237, t2238, t2240, t2243, t2244, t2245, t2247;
  double t2248, t2250, t2251, t2252, t2253, t2254, t2256, t2257;
  double t2258, t2260, t2261, t2265, t2268, t2271, t2273, t2274;
  double t2276, t2278, t2279, t2281, t2282, t2283, t2285, t2286;
  double t2287, t2288, t2289, t2293, t2298, t2300, t2301, t2305;
  double t2306, t2312, t2315, t2318, t2322, t2326, t2332, t2333;
  double t2336, t2338, t2340, t2344, t2347, t2350, t2352, t2355;
  double t2359, t2362, t2363, t2365, t2367, t2369, t2371, t2372;
  double t2373, t2375, t2376, t2381, t2383, t2385, t2387, t2388;
  double t2389, t2391, t2392, t2397, t2399, t2403, t2407, t2410;
  double t2412, t2416, t2420, t2443, t2444, t2445, t2446, t2447;
  double t2448, t2450, t2451, t2453, t2457, t2460, t2461, t2462;
  double t2463, t2464, t2465, t2466, t2469, t2472, t2473, t2474;
  double t2475, t2476, t2479, t2480, t2481, t2484, t2485, t2488;
  double t2489, t2491, t2492, t2495, t2496, t2499, t2500, t2502;
  double t2503, t2506, t2507, t2510, t2511, t2513, t2514, t2515;
  double t2517, t2519, t2521, t2524, t2526, t2545, t2546, t2550;
  double t2555, t2560, t2564;
#endif

#endif

#endif

#endif

#endif


  gga_c_chachiyo_params *params;

  assert(p->params != NULL);
  params = (gga_c_chachiyo_params * )(p->params);

  t1 = M_CBRT3;
  t2 = t1 * t1;
  t3 = params->bp * t2;
  t5 = POW_1_3(0.1e1 / M_PI);
  t7 = M_CBRT4;
  t8 = 0.1e1 / t5 * t7;
  t9 = rho[0] + rho[1];
  t10 = POW_1_3(t9);
  t11 = t8 * t10;
  t14 = params->bp * t1;
  t15 = t5 * t5;
  t17 = t7 * t7;
  t18 = 0.1e1 / t15 * t17;
  t19 = t10 * t10;
  t20 = t18 * t19;
  t23 = 0.1e1 + t3 * t11 / 0.3e1 + t14 * t20 / 0.3e1;
  t24 = log(t23);
  t25 = params->ap * t24;
  t26 = params->bf * t2;
  t29 = params->bf * t1;
  t32 = 0.1e1 + t26 * t11 / 0.3e1 + t29 * t20 / 0.3e1;
  t33 = log(t32);
  t35 = params->af * t33 - t25;
  t36 = rho[0] - rho[1];
  t37 = 0.1e1 / t9;
  t38 = t36 * t37;
  t39 = 0.1e1 + t38;
  t40 = POW_1_3(t39);
  t41 = t40 * t40;
  t42 = 0.1e1 - t38;
  t43 = POW_1_3(t42);
  t44 = t43 * t43;
  t46 = t41 / 0.2e1 + t44 / 0.2e1;
  t47 = t46 * t46;
  t50 = -0.2e1 * t47 * t46 + 0.2e1;
  t52 = t35 * t50 + t25;
  t53 = M_CBRTPI;
  t54 = t2 * t53;
  t55 = t9 * t9;
  t57 = 0.1e1 / t10 / t55;
  t59 = sigma[0] + 0.2e1 * sigma[1] + sigma[2];
  t63 = 0.1e1 + t54 * t57 * t59 / 0.48e2;
  t64 = 0.1e1 / t52;
  t65 = params->h * t64;
  t66 = pow(t63, t65);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = t52 * t66;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t68 = t8 / t19;
  t72 = t18 / t10;
  t75 = t3 * t68 / 0.9e1 + 0.2e1 / 0.9e1 * t14 * t72;
  t77 = 0.1e1 / t23;
  t78 = params->ap * t75 * t77;
  t83 = t26 * t68 / 0.9e1 + 0.2e1 / 0.9e1 * t29 * t72;
  t85 = 0.1e1 / t32;
  t87 = params->af * t83 * t85 - t78;
  t88 = t87 * t50;
  t89 = t35 * t47;
  t90 = 0.1e1 / t40;
  t91 = 0.1e1 / t55;
  t92 = t36 * t91;
  t93 = t37 - t92;
  t95 = 0.1e1 / t43;
  t96 = -t93;
  t99 = t90 * t93 / 0.3e1 + t95 * t96 / 0.3e1;
  t102 = -0.6e1 * t89 * t99 + t78 + t88;
  t103 = t9 * t102;
  t105 = t9 * t52;
  t106 = t52 * t52;
  t107 = 0.1e1 / t106;
  t108 = params->h * t107;
  t109 = log(t63);
  t110 = t102 * t109;
  t112 = t65 * t2;
  t113 = t55 * t9;
  t115 = 0.1e1 / t10 / t113;
  t116 = t53 * t115;
  t117 = 0.1e1 / t63;
  t118 = t59 * t117;
  t119 = t116 * t118;
  t121 = 0.7e1 / 0.144e3 * t112 * t119;
  t122 = -t108 * t110 - t121;
  t123 = t66 * t122;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t103 * t66 + t105 * t123 + (t52 * t66);

  t125 = -t37 - t92;
  t127 = -t125;
  t130 = t90 * t125 / 0.3e1 + t95 * t127 / 0.3e1;
  t133 = -0.6e1 * t89 * t130 + t78 + t88;
  t134 = t9 * t133;
  t136 = t133 * t109;
  t138 = -t108 * t136 - t121;
  t139 = t66 * t138;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = t105 * t139 + t134 * t66 + (t52 * t66);

  t142 = 0.1e1 / t10 / t9;
  t143 = t142 * t66;
  t145 = t54 * t117;
  t146 = t143 * params->h * t145;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = t146 / 0.48e2;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[1] = t146 / 0.24e2;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[2] = vsigma[0];

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t147 = t102 * t66;
  t149 = t52 * t66;
  t150 = t149 * t122;
  t154 = t8 / t19 / t9;
  t156 = t18 * t142;
  t159 = -0.2e1 / 0.27e2 * t14 * t156 - 0.2e1 / 0.27e2 * t3 * t154;
  t160 = params->ap * t159;
  t161 = t160 * t77;
  t162 = t75 * t75;
  t164 = t23 * t23;
  t165 = 0.1e1 / t164;
  t166 = params->ap * t162 * t165;
  t170 = -0.2e1 / 0.27e2 * t26 * t154 - 0.2e1 / 0.27e2 * t29 * t156;
  t171 = params->af * t170;
  t173 = t83 * t83;
  t175 = t32 * t32;
  t176 = 0.1e1 / t175;
  t178 = -params->af * t173 * t176 + t171 * t85 - t161 + t166;
  t179 = t178 * t50;
  t180 = t87 * t47;
  t181 = t180 * t99;
  t183 = t35 * t46;
  t184 = t99 * t99;
  t188 = 0.1e1 / t40 / t39;
  t189 = t93 * t93;
  t192 = 0.1e1 / t113;
  t193 = t36 * t192;
  t195 = -0.2e1 * t91 + 0.2e1 * t193;
  t199 = 0.1e1 / t43 / t42;
  t200 = t96 * t96;
  t203 = -t195;
  t206 = -t188 * t189 / 0.9e1 + t90 * t195 / 0.3e1 - t199 * t200 / 0.9e1 + t95 * t203 / 0.3e1;
  t209 = -0.12e2 * t183 * t184 - 0.6e1 * t89 * t206 + t161 - t166 + t179 - 0.12e2 * t181;
  t210 = t9 * t209;
  t214 = t122 * t122;
  t215 = t66 * t214;
  t218 = 0.1e1 / t106 / t52;
  t219 = params->h * t218;
  t220 = t102 * t102;
  t221 = t220 * t109;
  t226 = t102 * t2;
  t227 = t108 * t226;
  t228 = t227 * t119;
  t230 = t55 * t55;
  t232 = 0.1e1 / t10 / t230;
  t233 = t53 * t232;
  t234 = t233 * t118;
  t236 = 0.35e2 / 0.216e3 * t112 * t234;
  t237 = t65 * t1;
  t238 = t53 * t53;
  t239 = t230 * t55;
  t241 = 0.1e1 / t19 / t239;
  t242 = t238 * t241;
  t243 = t59 * t59;
  t244 = t63 * t63;
  t245 = 0.1e1 / t244;
  t246 = t243 * t245;
  t247 = t242 * t246;
  t249 = 0.49e2 / 0.6912e4 * t237 * t247;
  t250 = 0.2e1 * t219 * t221 - t108 * t209 * t109 + 0.7e1 / 0.72e2 * t228 + t236 - t249;
  t251 = t66 * t250;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * t103 * t123 + t105 * t215 + t105 * t251 + t210 * t66 + 0.2e1 * t147 + 0.2e1 * t150;

  t253 = t133 * t66;
  t255 = t180 * t130;
  t257 = t130 * t99;
  t260 = t188 * t125;
  t263 = t90 * t36;
  t266 = t199 * t127;
  t269 = t95 * t36;
  t272 = -t260 * t93 / 0.9e1 + 0.2e1 / 0.3e1 * t263 * t192 - t266 * t96 / 0.9e1 - 0.2e1 / 0.3e1 * t269 * t192;
  t275 = -0.12e2 * t183 * t257 - 0.6e1 * t89 * t272 + t161 - t166 + t179 - 0.6e1 * t181 - 0.6e1 * t255;
  t276 = t9 * t275;
  t279 = t149 * t138;
  t281 = t123 * t138;
  t286 = t275 * t109;
  t288 = t133 * t2;
  t289 = t108 * t288;
  t290 = t289 * t119;
  t293 = 0.2e1 * t219 * t136 * t102 - t108 * t286 + 0.7e1 / 0.144e3 * t290 + 0.7e1 / 0.144e3 * t228 + t236 - t249;
  t294 = t66 * t293;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = t103 * t139 + t105 * t281 + t105 * t294 + t134 * t123 + t276 * t66 + t147 + t150 + t253 + t279;

  t299 = t130 * t130;
  t302 = t125 * t125;
  t306 = 0.2e1 * t91 + 0.2e1 * t193;
  t309 = t127 * t127;
  t312 = -t306;
  t315 = -t188 * t302 / 0.9e1 + t90 * t306 / 0.3e1 - t199 * t309 / 0.9e1 + t95 * t312 / 0.3e1;
  t318 = -0.12e2 * t183 * t299 - 0.6e1 * t89 * t315 + t161 - t166 + t179 - 0.12e2 * t255;
  t319 = t9 * t318;
  t323 = t138 * t138;
  t324 = t66 * t323;
  t326 = t133 * t133;
  t327 = t326 * t109;
  t330 = t318 * t109;
  t333 = 0.2e1 * t219 * t327 - t108 * t330 + 0.7e1 / 0.72e2 * t290 + t236 - t249;
  t334 = t66 * t333;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = t105 * t324 + t105 * t334 + 0.2e1 * t134 * t139 + t319 * t66 + 0.2e1 * t253 + 0.2e1 * t279;

  t336 = t57 * t66;
  t338 = t336 * params->h * t145;
  t339 = t338 / 0.36e2;
  t343 = params->h * t2 * t53 * t117;
  t344 = t143 * t122 * t343;
  t348 = 0.1e1 / t19 / t230 * t66;
  t349 = t348 * params->h;
  t350 = t1 * t238;
  t352 = t350 * t245 * t59;
  t353 = t349 * t352;
  t354 = 0.7e1 / 0.2304e4 * t353;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = -t339 + t344 / 0.48e2 + t354;

  t355 = t338 / 0.18e2;
  t357 = 0.7e1 / 0.1152e4 * t353;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[1] = -t355 + t344 / 0.24e2 + t357;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[2] = v2rhosigma[0];

  t359 = t143 * t138 * t343;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[3] = -t339 + t359 / 0.48e2 + t354;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[4] = -t355 + t359 / 0.24e2 + t357;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[5] = v2rhosigma[3];

  t363 = 0.1e1 / t19 / t113;
  t364 = t363 * t66;
  t365 = params->h * params->h;
  t368 = t238 * t245;
  t369 = t64 * t1 * t368;
  t372 = t350 * t245;
  t374 = t364 * t365 * t369 - t364 * params->h * t372;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = t374 / 0.768e3;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[1] = t374 / 0.384e3;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[2] = v2sigma2[0];

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[3] = t374 / 0.192e3;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[4] = v2sigma2[1];

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[5] = v2sigma2[2];

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t375 = t209 * t66;
  t377 = t147 * t122;
  t379 = t149 * t214;
  t381 = t149 * t250;
  t385 = t8 / t19 / t55;
  t388 = t18 * t57;
  t392 = params->ap * (0.10e2 / 0.81e2 * t3 * t385 + 0.8e1 / 0.81e2 * t14 * t388);
  t393 = t392 * t77;
  t394 = t165 * t75;
  t396 = 0.3e1 * t160 * t394;
  t400 = 0.1e1 / t164 / t23;
  t402 = 0.2e1 * params->ap * t162 * t75 * t400;
  t408 = params->af * (0.10e2 / 0.81e2 * t26 * t385 + 0.8e1 / 0.81e2 * t29 * t388);
  t410 = t176 * t83;
  t416 = 0.1e1 / t175 / t32;
  t419 = 0.2e1 * params->af * t173 * t83 * t416 - 0.3e1 * t171 * t410 + t408 * t85 - t393 + t396 - t402;
  t420 = t419 * t50;
  t421 = t178 * t47;
  t422 = t421 * t99;
  t424 = t87 * t46;
  t425 = t424 * t184;
  t427 = t180 * t206;
  t429 = t184 * t99;
  t432 = t99 * t206;
  t435 = t39 * t39;
  t437 = 0.1e1 / t40 / t435;
  t438 = t189 * t93;
  t441 = t188 * t93;
  t444 = 0.1e1 / t230;
  t445 = t36 * t444;
  t447 = 0.6e1 * t192 - 0.6e1 * t445;
  t450 = t42 * t42;
  t452 = 0.1e1 / t43 / t450;
  t453 = t200 * t96;
  t456 = t199 * t96;
  t459 = -t447;
  t462 = 0.4e1 / 0.27e2 * t437 * t438 - t441 * t195 / 0.3e1 + t90 * t447 / 0.3e1 + 0.4e1 / 0.27e2 * t452 * t453 - t456 * t203 / 0.3e1 + t95 * t459 / 0.3e1;
  t465 = -0.36e2 * t183 * t432 - 0.12e2 * t35 * t429 - 0.6e1 * t89 * t462 + t393 - t396 + t402 + t420 - 0.18e2 * t422 - 0.36e2 * t425 - 0.18e2 * t427;
  t466 = t9 * t465;
  t474 = t214 * t122;
  t475 = t66 * t474;
  t477 = t123 * t250;
  t480 = t106 * t106;
  t482 = params->h / t480;
  t483 = t220 * t102;
  t487 = t110 * t209;
  t491 = t219 * t220 * t2;
  t492 = t491 * t119;
  t497 = t108 * t209 * t2;
  t498 = t497 * t119;
  t500 = t227 * t234;
  t503 = t108 * t102 * t1;
  t504 = t503 * t247;
  t506 = t230 * t9;
  t510 = t53 / t10 / t506 * t118;
  t512 = 0.455e3 / 0.648e3 * t112 * t510;
  t513 = t230 * t113;
  t517 = t238 / t19 / t513 * t246;
  t519 = 0.245e3 / 0.3456e4 * t237 * t517;
  t520 = t65 * M_PI;
  t521 = t230 * t230;
  t522 = t521 * t55;
  t523 = 0.1e1 / t522;
  t524 = t243 * t59;
  t527 = 0.1e1 / t244 / t63;
  t530 = 0.343e3 / 0.165888e6 * t520 * t523 * t524 * t527;
  t531 = -0.6e1 * t482 * t483 * t109 + 0.6e1 * t219 * t487 - 0.7e1 / 0.24e2 * t492 - t108 * t465 * t109 + 0.7e1 / 0.48e2 * t498 - 0.35e2 / 0.72e2 * t500 + 0.49e2 / 0.2304e4 * t504 - t512 + t519 - t530;
  t532 = t66 * t531;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = 0.3e1 * t103 * t215 + 0.3e1 * t103 * t251 + t105 * t475 + 0.3e1 * t105 * t477 + t105 * t532 + 0.3e1 * t210 * t123 + t466 * t66 + 0.3e1 * t375 + 0.6e1 * t377 + 0.3e1 * t379 + 0.3e1 * t381;

  t537 = t122 * t138;
  t539 = 0.2e1 * (t52 * t66) * t537;
  t546 = t286 * t102;
  t549 = t219 * t288;
  t550 = t118 * t102;
  t551 = t116 * t550;
  t553 = 0.7e1 / 0.36e2 * t549 * t551;
  t560 = t421 * t130;
  t563 = 0.24e2 * t424 * t257;
  t565 = 0.12e2 * t180 * t272;
  t566 = t35 * t184;
  t569 = t272 * t99;
  t572 = t130 * t206;
  t575 = t437 * t125;
  t578 = t188 * t36;
  t588 = t452 * t127;
  t591 = t199 * t36;
  t601 = 0.4e1 / 0.27e2 * t575 * t189 - 0.4e1 / 0.9e1 * t578 * t192 * t93 - t260 * t195 / 0.9e1 + 0.2e1 / 0.3e1 * t90 * t192 - 0.2e1 * t263 * t444 + 0.4e1 / 0.27e2 * t588 * t200 + 0.4e1 / 0.9e1 * t591 * t192 * t96 - t266 * t203 / 0.9e1 - 0.2e1 / 0.3e1 * t95 * t192 + 0.2e1 * t269 * t444;
  t604 = -0.12e2 * t566 * t130 - 0.24e2 * t183 * t569 - 0.12e2 * t183 * t572 - 0.6e1 * t89 * t601 + t393 - t396 + t402 + t420 - 0.12e2 * t422 - 0.12e2 * t425 - 0.6e1 * t427 - 0.6e1 * t560 - t563 - t565;
  t605 = t604 * t109;
  t607 = t275 * t2;
  t608 = t108 * t607;
  t610 = 0.7e1 / 0.72e2 * t608 * t119;
  t611 = t289 * t234;
  t613 = t133 * t1;
  t614 = t108 * t613;
  t615 = t614 * t247;
  t621 = -0.6e1 * t482 * t136 * t220 + 0.4e1 * t219 * t546 - t553 + 0.2e1 * t219 * t136 * t209 - t108 * t605 + t610 - 0.35e2 / 0.216e3 * t611 + 0.49e2 / 0.6912e4 * t615 - 0.7e1 / 0.72e2 * t492 + 0.7e1 / 0.144e3 * t498 - 0.35e2 / 0.108e3 * t500 + 0.49e2 / 0.3456e4 * t504 - t512 + t519 - t530;
  t622 = t66 * t621;
  t625 = t215 * t138;
  t627 = t275 * t66;
  t628 = 0.2e1 * t627;
  t632 = t251 * t138;
  t634 = t123 * t293;
  t638 = 0.2e1 * t253 * t122;
  t639 = t9 * t604;
  t642 = 0.2e1 * t147 * t138;
  t644 = 0.2e1 * t149 * t293;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[1] = 0.2e1 * t103 * t281 + 0.2e1 * t103 * t294 + t105 * t622 + t105 * t625 + t105 * t632 + 0.2e1 * t105 * t634 + 0.2e1 * t276 * t123 + t134 * t215 + t134 * t251 + t210 * t139 + t639 * t66 + t375 + 0.2e1 * t377 + t379 + t381 + t539 + t628 + t638 + t642 + t644;

  t645 = t318 * t66;
  t648 = t424 * t299;
  t650 = t35 * t99;
  t653 = t130 * t272;
  t656 = t180 * t315;
  t658 = t315 * t99;
  t661 = t437 * t302;
  t666 = t188 * t306;
  t671 = -0.2e1 * t192 - 0.6e1 * t445;
  t674 = t452 * t309;
  t679 = t199 * t312;
  t682 = -t671;
  t685 = 0.4e1 / 0.27e2 * t661 * t93 - 0.4e1 / 0.9e1 * t260 * t193 - t666 * t93 / 0.9e1 + t90 * t671 / 0.3e1 + 0.4e1 / 0.27e2 * t674 * t96 + 0.4e1 / 0.9e1 * t266 * t193 - t679 * t96 / 0.9e1 + t95 * t682 / 0.3e1;
  t688 = -0.24e2 * t183 * t653 - 0.12e2 * t183 * t658 - 0.12e2 * t650 * t299 - 0.6e1 * t89 * t685 + t393 - t396 + t402 + t420 - 0.6e1 * t422 - 0.12e2 * t560 - t563 - t565 - 0.12e2 * t648 - 0.6e1 * t656;
  t689 = t9 * t688;
  t692 = t253 * t138;
  t700 = t149 * t323;
  t702 = t123 * t323;
  t704 = t139 * t293;
  t707 = t149 * t333;
  t709 = t123 * t333;
  t717 = t326 * t2;
  t718 = t219 * t717;
  t719 = t718 * t119;
  t721 = t330 * t102;
  t724 = t688 * t109;
  t726 = t318 * t2;
  t727 = t108 * t726;
  t728 = t727 * t119;
  t734 = -0.6e1 * t482 * t327 * t102 + 0.4e1 * t219 * t136 * t275 - 0.7e1 / 0.72e2 * t719 + 0.2e1 * t219 * t721 - t108 * t724 + 0.7e1 / 0.144e3 * t728 - t553 + t610 - 0.35e2 / 0.108e3 * t611 + 0.49e2 / 0.3456e4 * t615 - 0.35e2 / 0.216e3 * t500 - t512 + t519 + 0.49e2 / 0.6912e4 * t504 - t530;
  t735 = t66 * t734;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[2] = t103 * t324 + t103 * t334 + t105 * t702 + 0.2e1 * t105 * t704 + t105 * t709 + t105 * t735 + t319 * t123 + 0.2e1 * t134 * t281 + 0.2e1 * t134 * t294 + 0.2e1 * t276 * t139 + t689 * t66 + t539 + t628 + t638 + t642 + t644 + t645 + 0.2e1 * t692 + t700 + t707;

  t744 = t299 * t130;
  t747 = t130 * t315;
  t750 = t302 * t125;
  t756 = -0.6e1 * t192 - 0.6e1 * t445;
  t759 = t309 * t127;
  t764 = -t756;
  t767 = 0.4e1 / 0.27e2 * t437 * t750 - t260 * t306 / 0.3e1 + t90 * t756 / 0.3e1 + 0.4e1 / 0.27e2 * t452 * t759 - t266 * t312 / 0.3e1 + t95 * t764 / 0.3e1;
  t770 = -0.36e2 * t183 * t747 - 0.12e2 * t35 * t744 - 0.6e1 * t89 * t767 + t393 - t396 + t402 + t420 - 0.18e2 * t560 - 0.36e2 * t648 - 0.18e2 * t656;
  t771 = t9 * t770;
  t779 = t323 * t138;
  t780 = t66 * t779;
  t782 = t139 * t333;
  t785 = t326 * t133;
  t786 = t785 * t109;
  t793 = t770 * t109;
  t798 = -0.6e1 * t482 * t786 + 0.6e1 * t219 * t136 * t318 - 0.7e1 / 0.24e2 * t719 - t108 * t793 + 0.7e1 / 0.48e2 * t728 - 0.35e2 / 0.72e2 * t611 + 0.49e2 / 0.2304e4 * t615 - t512 + t519 - t530;
  t799 = t66 * t798;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[3] = t105 * t780 + 0.3e1 * t105 * t782 + t105 * t799 + 0.3e1 * t134 * t324 + 0.3e1 * t134 * t334 + 0.3e1 * t319 * t139 + t771 * t66 + 0.3e1 * t645 + 0.6e1 * t692 + 0.3e1 * t700 + 0.3e1 * t707;

  t801 = t115 * t66;
  t803 = t801 * params->h * t145;
  t804 = 0.7e1 / 0.108e3 * t803;
  t806 = t336 * t122 * t343;
  t807 = t806 / 0.18e2;
  t810 = 0.1e1 / t19 / t506 * t66;
  t811 = t810 * params->h;
  t812 = t811 * t352;
  t813 = 0.7e1 / 0.384e3 * t812;
  t815 = t143 * t214 * t343;
  t818 = t143 * t250 * t343;
  t820 = t122 * params->h;
  t822 = t348 * t820 * t352;
  t823 = 0.7e1 / 0.1152e4 * t822;
  t825 = 0.1e1 / t521 * t66;
  t826 = t825 * params->h;
  t827 = M_PI * t527;
  t828 = t827 * t243;
  t829 = t826 * t828;
  t830 = 0.49e2 / 0.55296e5 * t829;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = t804 - t807 - t813 + t815 / 0.48e2 + t818 / 0.48e2 + t823 + t830;

  t831 = 0.7e1 / 0.54e2 * t803;
  t833 = 0.7e1 / 0.192e3 * t812;
  t837 = 0.49e2 / 0.27648e5 * t829;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[1] = t831 - t806 / 0.9e1 - t833 + t815 / 0.24e2 + t818 / 0.24e2 + 0.7e1 / 0.576e3 * t822 + t837;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[2] = v3rho2sigma[0];

  t840 = t336 * t138 * t343;
  t843 = t143 * t537 * t343;
  t846 = t143 * t293 * t343;
  t848 = t138 * params->h;
  t850 = t348 * t848 * t352;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[3] = t804 - t806 / 0.36e2 - t813 - t840 / 0.36e2 + t843 / 0.48e2 + t846 / 0.48e2 + 0.7e1 / 0.2304e4 * t850 + 0.7e1 / 0.2304e4 * t822 + t830;

  t853 = t840 / 0.18e2;
  t856 = 0.7e1 / 0.1152e4 * t850;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[4] = t831 - t807 - t833 - t853 + t843 / 0.24e2 + t846 / 0.24e2 + t856 + t823 + t837;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[5] = v3rho2sigma[3];

  t858 = t143 * t323 * t343;
  t861 = t143 * t333 * t343;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[6] = t804 - t853 - t813 + t858 / 0.48e2 + t861 / 0.48e2 + t856 + t830;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[7] = t831 - t840 / 0.9e1 - t833 + t858 / 0.24e2 + t861 / 0.24e2 + 0.7e1 / 0.576e3 * t850 + t837;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[8] = v3rho2sigma[6];

  t868 = t348 * t365 * t369;
  t869 = 0.11e2 / 0.2304e4 * t868;
  t870 = t122 * t365;
  t871 = t364 * t870;
  t872 = t871 * t369;
  t874 = t365 * t107;
  t875 = t364 * t874;
  t877 = t350 * t245 * t102;
  t878 = t875 * t877;
  t881 = 0.1e1 / t513 * t66;
  t882 = t881 * t365;
  t883 = t64 * M_PI;
  t884 = t527 * t59;
  t885 = t883 * t884;
  t886 = t882 * t885;
  t887 = 0.7e1 / 0.18432e5 * t886;
  t888 = t349 * t372;
  t889 = 0.11e2 / 0.2304e4 * t888;
  t891 = params->h * t1;
  t892 = t891 * t368;
  t893 = t364 * t122 * t892;
  t896 = t827 * t59;
  t897 = t881 * params->h * t896;
  t898 = 0.7e1 / 0.18432e5 * t897;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = -t869 + t872 / 0.768e3 - t878 / 0.768e3 + t887 + t889 - t893 / 0.768e3 - t898;

  t899 = 0.11e2 / 0.1152e4 * t868;
  t902 = 0.7e1 / 0.9216e4 * t886;
  t903 = 0.11e2 / 0.1152e4 * t888;
  t905 = 0.7e1 / 0.9216e4 * t897;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[1] = -t899 + t872 / 0.384e3 - t878 / 0.384e3 + t902 + t903 - t893 / 0.384e3 - t905;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[2] = v3rhosigma2[0];

  t906 = 0.11e2 / 0.576e3 * t868;
  t909 = 0.7e1 / 0.4608e4 * t886;
  t910 = 0.11e2 / 0.576e3 * t888;
  t912 = 0.7e1 / 0.4608e4 * t897;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[3] = -t906 + t872 / 0.192e3 - t878 / 0.192e3 + t909 + t910 - t893 / 0.192e3 - t912;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[4] = v3rhosigma2[1];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[5] = v3rhosigma2[2];

  t913 = t138 * t365;
  t914 = t364 * t913;
  t915 = t914 * t369;
  t917 = t245 * t133;
  t918 = t350 * t917;
  t919 = t875 * t918;
  t922 = t364 * t138 * t892;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[6] = -t869 + t915 / 0.768e3 - t919 / 0.768e3 + t887 + t889 - t922 / 0.768e3 - t898;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[7] = -t899 + t915 / 0.384e3 - t919 / 0.384e3 + t902 + t903 - t922 / 0.384e3 - t905;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[8] = v3rhosigma2[6];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[9] = -t906 + t915 / 0.192e3 - t919 / 0.192e3 + t909 + t910 - t922 / 0.192e3 - t912;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[10] = v3rhosigma2[7];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[11] = v3rhosigma2[8];

  t930 = 0.1e1 / t239;
  t931 = t930 * t66;
  t932 = t365 * params->h;
  t933 = t931 * t932;
  t934 = t107 * M_PI;
  t935 = t934 * t527;
  t936 = t933 * t935;
  t938 = t931 * t365;
  t939 = t883 * t527;
  t940 = t938 * t939;
  t942 = params->h * M_PI;
  t943 = t942 * t527;
  t944 = t931 * t943;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = t936 / 0.12288e5 - t940 / 0.4096e4 + t944 / 0.6144e4;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[1] = t936 / 0.6144e4 - t940 / 0.2048e4 + t944 / 0.3072e4;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[2] = v3sigma3[0];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[3] = t936 / 0.3072e4 - t940 / 0.1024e4 + t944 / 0.1536e4;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[4] = v3sigma3[1];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[5] = v3sigma3[2];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[6] = t936 / 0.1536e4 - t940 / 0.512e3 + t944 / 0.768e3;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[7] = v3sigma3[3];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[8] = v3sigma3[4];

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[9] = v3sigma3[5];

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t955 = t147 * t214;
  t958 = (t52 * t66) * t122 * t250;
  t960 = t149 * t474;
  t969 = 0.4e1 * t392 * t394;
  t970 = t159 * t159;
  t973 = 0.3e1 * params->ap * t970 * t165;
  t974 = t162 * t162;
  t976 = t164 * t164;
  t979 = 0.6e1 * params->ap * t974 / t976;
  t980 = t178 * t46;
  t981 = t980 * t184;
  t983 = t424 * t432;
  t985 = t206 * t206;
  t991 = t8 * t363;
  t994 = t18 * t115;
  t999 = params->ap * (-0.80e2 / 0.243e3 * t3 * t991 - 0.56e2 / 0.243e3 * t14 * t994) * t77;
  t1000 = t419 * t47;
  t1001 = t1000 * t99;
  t1003 = t421 * t206;
  t1005 = t87 * t429;
  t1007 = t180 * t462;
  t1013 = 0.1e1 / t40 / t435 / t39;
  t1014 = t189 * t189;
  t1020 = t195 * t195;
  t1025 = 0.1e1 / t506;
  t1026 = t36 * t1025;
  t1028 = -0.24e2 * t444 + 0.24e2 * t1026;
  t1033 = 0.1e1 / t43 / t450 / t42;
  t1034 = t200 * t200;
  t1040 = t203 * t203;
  t1063 = t170 * t170;
  t1067 = t173 * t173;
  t1069 = t175 * t175;
  t1075 = 0.12e2 * t160 * t400 * t162;
  t1077 = (params->af * (-0.80e2 / 0.243e3 * t26 * t991 - 0.56e2 / 0.243e3 * t29 * t994) * t85 - 0.4e1 * t408 * t410 + 0.12e2 * t171 * t416 * t173 - 0.3e1 * params->af * t1063 * t176 - 0.6e1 * params->af * t1067 / t1069 - t999 + t969 - t1075 + t973 + t979) * t50;
  t1078 = -t969 - t973 - t979 - 0.72e2 * t981 - 0.144e3 * t983 - 0.36e2 * t183 * t985 - 0.48e2 * t183 * t99 * t462 + t999 - 0.24e2 * t1001 - 0.36e2 * t1003 - 0.48e2 * t1005 - 0.24e2 * t1007 - 0.72e2 * t566 * t206 - 0.6e1 * t89 * (-0.28e2 / 0.81e2 * t1013 * t1014 + 0.8e1 / 0.9e1 * t437 * t189 * t195 - t188 * t1020 / 0.3e1 - 0.4e1 / 0.9e1 * t441 * t447 + t90 * t1028 / 0.3e1 - 0.28e2 / 0.81e2 * t1033 * t1034 + 0.8e1 / 0.9e1 * t452 * t200 * t203 - t199 * t1040 / 0.3e1 - 0.4e1 / 0.9e1 * t456 * t459 - t95 * t1028 / 0.3e1) + t1077 + t1075;
  t1084 = M_PI * t523 * t524 * t527;
  t1085 = t108 * t102 * t1084;
  t1092 = 0.10045e5 / 0.15552e5 * t237 * t238 / t19 / t521 * t246;
  t1093 = t53 * M_PI;
  t1098 = t243 * t243;
  t1100 = t244 * t244;
  t1101 = 0.1e1 / t1100;
  t1102 = t1101 * t2;
  t1105 = 0.2401e4 / 0.7962624e7 * t65 * t1093 / t10 / t521 / t506 * t1098 * t1102;
  t1108 = t482 * t483 * t2 * t119;
  t1112 = t219 * t220 * t1 * t247;
  t1116 = t108 * t465 * t2 * t119;
  t1120 = t108 * t209 * t1 * t247;
  t1122 = t503 * t517;
  t1129 = 0.910e3 / 0.243e3 * t112 * t53 / t10 / t239 * t118;
  t1132 = t116 * t118 * t209;
  t1133 = t219 * t226 * t1132;
  t1135 = t491 * t234;
  t1137 = t497 * t234;
  t1139 = t227 * t510;
  t1141 = t521 * t113;
  t1146 = 0.1715e4 / 0.41472e5 * t520 / t1141 * t524 * t527;
  t1149 = params->h / t480 / t52;
  t1150 = t220 * t220;
  t1157 = t209 * t209;
  t1164 = -t108 * t1078 * t109 + 0.343e3 / 0.41472e5 * t1085 - t1092 - t1105 + 0.7e1 / 0.6e1 * t1108 - 0.49e2 / 0.576e3 * t1112 + 0.7e1 / 0.36e2 * t1116 + 0.49e2 / 0.1152e4 * t1120 - 0.245e3 / 0.864e3 * t1122 + t1129 - 0.7e1 / 0.6e1 * t1133 + 0.35e2 / 0.18e2 * t1135 - 0.35e2 / 0.36e2 * t1137 + 0.455e3 / 0.162e3 * t1139 + t1146 + 0.24e2 * t1149 * t1150 * t109 - 0.36e2 * t482 * t221 * t209 + 0.6e1 * t219 * t1157 * t109 + 0.8e1 * t219 * t110 * t465;
  t1167 = t375 * t122;
  t1169 = t147 * t250;
  t1171 = t149 * t531;
  t1175 = t465 * t66;
  t1186 = t214 * t214;
  t1189 = t250 * t250;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = t105 * t66 * t1164 + t105 * t66 * t1186 + 0.3e1 * t105 * t66 * t1189 + 0.4e1 * t105 * t123 * t531 + 0.6e1 * t105 * t215 * t250 + t9 * t1078 * t66 + 0.4e1 * t103 * t475 + 0.12e2 * t103 * t477 + 0.4e1 * t103 * t532 + 0.4e1 * t466 * t123 + 0.6e1 * t210 * t215 + 0.6e1 * t210 * t251 + 0.12e2 * t1167 + 0.12e2 * t1169 + 0.4e1 * t1171 + 0.4e1 * t1175 + 0.12e2 * t955 + 0.12e2 * t958 + 0.4e1 * t960;

  t1202 = t604 * t66;
  t1208 = t122 * t293;
  t1209 = (t52 * t66) * t1208;
  t1212 = t147 * t537;
  t1214 = t250 * t138;
  t1215 = (t52 * t66) * t1214;
  t1232 = 0.3e1 * t105 * t123 * t621 + t105 * t532 * t138 + 0.3e1 * t105 * t215 * t293 + 0.3e1 * t103 * t622 + 0.3e1 * t103 * t632 + 0.3e1 * t639 * t123 + t134 * t475 + 0.3e1 * t134 * t477 + t134 * t532 + t466 * t139 + 0.3e1 * t210 * t281 + 0.3e1 * t210 * t294 + 0.3e1 * t276 * t251 + 0.3e1 * t1169 + t1171 + 0.3e1 * t1202 + 0.6e1 * t1209 + 0.6e1 * t1212 + 0.3e1 * t1215;
  t1234 = t253 * t250;
  t1245 = t105 * t66;
  t1249 = t253 * t214;
  t1251 = t375 * t138;
  t1268 = t482 * t133;
  t1299 = 0.8e1 * t263 * t1025;
  t1317 = 0.8e1 * t269 * t1025;
  t1332 = -0.28e2 / 0.81e2 * t1013 * t125 * t438 + 0.4e1 / 0.9e1 * t575 * t93 * t195 + 0.8e1 / 0.9e1 * t437 * t36 * t192 * t189 - 0.2e1 / 0.3e1 * t188 * t192 * t93 - 0.2e1 / 0.3e1 * t578 * t192 * t195 + t1299 - 0.28e2 / 0.81e2 * t1033 * t127 * t453 + 0.4e1 / 0.9e1 * t588 * t96 * t203 - 0.8e1 / 0.9e1 * t452 * t36 * t192 * t200 + 0.2e1 / 0.3e1 * t199 * t192 * t96 + 0.2e1 / 0.3e1 * t591 * t192 * t203 - t1317 - t260 * t447 / 0.9e1 - 0.4e1 * t90 * t444 - t266 * t459 / 0.9e1 + 0.4e1 * t95 * t444 + 0.2e1 * t578 * t444 * t93 - 0.2e1 * t591 * t444 * t96;
  t1335 = t1000 * t130;
  t1337 = t421 * t272;
  t1338 = 0.18e2 * t1337;
  t1339 = t180 * t601;
  t1342 = t980 * t257;
  t1343 = 0.36e2 * t1342;
  t1344 = t424 * t569;
  t1346 = -0.6e1 * t89 * t1332 - 0.36e2 * t566 * t272 - 0.12e2 * t1005 + t1075 + t1077 - 0.6e1 * t1335 - t1338 - 0.18e2 * t1339 - t1343 - 0.72e2 * t1344 - t969 - 0.36e2 * t983;
  t1347 = t424 * t572;
  t1365 = t87 * t184 * t130;
  t1367 = -0.12e2 * t183 * t130 * t462 - 0.36e2 * t183 * t272 * t206 - 0.36e2 * t183 * t601 * t99 - 0.36e2 * t650 * t572 - 0.18e2 * t1001 - 0.18e2 * t1003 - 0.6e1 * t1007 - 0.36e2 * t1347 - 0.36e2 * t1365 - t973 - t979 - 0.36e2 * t981 + t999;
  t1368 = t1346 + t1367;
  t1371 = 0.6e1 * t219 * t286 * t209 + 0.6e1 * t219 * t605 * t102 - 0.18e2 * t482 * t286 * t220 + 0.24e2 * t1149 * t136 * t483 + 0.2e1 * t219 * t136 * t465 - 0.18e2 * t1268 * t487 + t1146 + 0.7e1 / 0.24e2 * t1108 - 0.49e2 / 0.1152e4 * t1112 + 0.7e1 / 0.144e3 * t1116 + 0.49e2 / 0.2304e4 * t1120 - 0.245e3 / 0.1152e4 * t1122 + 0.35e2 / 0.36e2 * t1135 - 0.35e2 / 0.72e2 * t1137 + 0.455e3 / 0.216e3 * t1139 - t108 * t1368 * t109;
  t1374 = t108 * t604 * t2 * t119;
  t1378 = t108 * t275 * t1 * t247;
  t1379 = 0.49e2 / 0.2304e4 * t1378;
  t1380 = t614 * t517;
  t1382 = t608 * t234;
  t1383 = 0.35e2 / 0.72e2 * t1382;
  t1386 = t108 * t133 * t1084;
  t1388 = t289 * t510;
  t1394 = t482 * t288 * t116 * t118 * t220;
  t1397 = t219 * t607 * t551;
  t1399 = t549 * t1132;
  t1404 = t219 * t613 * t242 * t246 * t102;
  t1405 = 0.49e2 / 0.1152e4 * t1404;
  t1407 = t549 * t233 * t550;
  t1408 = 0.35e2 / 0.36e2 * t1407;
  t1409 = 0.7e1 / 0.48e2 * t1374 + t1379 - 0.245e3 / 0.3456e4 * t1380 - t1383 + 0.343e3 / 0.55296e5 * t1085 - t1092 - t1105 + t1129 + 0.343e3 / 0.165888e6 * t1386 + 0.455e3 / 0.648e3 * t1388 - 0.7e1 / 0.24e2 * t1133 + 0.7e1 / 0.8e1 * t1394 - 0.7e1 / 0.12e2 * t1397 - 0.7e1 / 0.24e2 * t1399 - t1405 + t1408;
  t1415 = t214 * t138;
  t1416 = (t52 * t66) * t1415;
  t1421 = t147 * t293;
  t1423 = t627 * t122;
  t1425 = t149 * t621;
  t1428 = 0.3e1 * t958 + 0.3e1 * t1234 + 0.3e1 * t105 * t251 * t293 + 0.3e1 * t103 * t625 + 0.6e1 * t103 * t634 + t105 * t475 * t138 + t1175 + 0.3e1 * t1245 * t537 * t250 + 0.3e1 * t1249 + 0.3e1 * t1251 + t105 * t66 * (t1371 + t1409) + 0.3e1 * t276 * t215 + 0.3e1 * t1416 + 0.3e1 * t955 + t9 * t1368 * t66 + t960 + 0.6e1 * t1421 + 0.6e1 * t1423 + 0.3e1 * t1425 + 0.3e1 * t1167;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[1] = t1232 + t1428;

  t1436 = t147 * t333;
  t1448 = t424 * t653;
  t1455 = t424 * t658;
  t1465 = t272 * t272;
  t1468 = t980 * t299;
  t1471 = t87 * t99 * t299;
  t1476 = t421 * t315;
  t1478 = -0.24e2 * t183 * t130 * t601 - 0.12e2 * t183 * t315 * t206 - 0.24e2 * t183 * t685 * t99 - 0.12e2 * t35 * t206 * t299 - 0.24e2 * t183 * t1465 - 0.12e2 * t566 * t315 - 0.48e2 * t650 * t653 - 0.12e2 * t1335 - 0.24e2 * t1337 - 0.12e2 * t1339 - 0.48e2 * t1448 - 0.24e2 * t1455 - 0.12e2 * t1468 - 0.24e2 * t1471 - 0.6e1 * t1476;
  t1479 = t180 * t685;
  t1490 = t36 * t36;
  t1530 = -0.28e2 / 0.81e2 * t1013 * t302 * t189 + 0.32e2 / 0.27e2 * t575 * t93 * t36 * t192 + 0.4e1 / 0.27e2 * t661 * t195 - 0.8e1 / 0.9e1 * t188 * t1490 * t930 - 0.4e1 / 0.9e1 * t260 * t192 + 0.4e1 / 0.3e1 * t260 * t445 + 0.4e1 / 0.27e2 * t437 * t306 * t189 - 0.2e1 / 0.9e1 * t188 * t671 * t93 - t666 * t195 / 0.9e1 + t1299 - 0.28e2 / 0.81e2 * t1033 * t309 * t200 - 0.32e2 / 0.27e2 * t588 * t96 * t36 * t192 + 0.4e1 / 0.27e2 * t674 * t203 - 0.8e1 / 0.9e1 * t199 * t1490 * t930 + 0.4e1 / 0.9e1 * t266 * t192 - 0.4e1 / 0.3e1 * t266 * t445 + 0.4e1 / 0.27e2 * t452 * t312 * t200 - 0.2e1 / 0.9e1 * t199 * t682 * t96 - t679 * t203 / 0.9e1 - t1317;
  t1540 = -0.6e1 * t89 * t1530 - 0.12e2 * t1001 - 0.6e1 * t1003 + t1075 + t1077 - 0.48e2 * t1342 - 0.48e2 * t1344 - 0.24e2 * t1347 - 0.24e2 * t1365 - 0.12e2 * t1479 - t969 - t973 - t979 - 0.12e2 * t981 + t999;
  t1541 = t1478 + t1540;
  t1546 = t219 * t326 * t1 * t247;
  t1550 = t108 * t688 * t2 * t119;
  t1554 = t108 * t318 * t1 * t247;
  t1556 = t718 * t234;
  t1558 = t727 * t234;
  t1572 = t275 * t275;
  t1579 = -t108 * t1541 * t109 - 0.49e2 / 0.3456e4 * t1546 + 0.7e1 / 0.72e2 * t1550 + 0.49e2 / 0.6912e4 * t1554 + 0.35e2 / 0.108e3 * t1556 - 0.35e2 / 0.216e3 * t1558 + 0.2e1 * t219 * t330 * t209 + 0.4e1 * t219 * t724 * t102 + t1146 - 0.49e2 / 0.3456e4 * t1112 + 0.49e2 / 0.6912e4 * t1120 - 0.245e3 / 0.1728e4 * t1122 + 0.35e2 / 0.108e3 * t1135 - 0.35e2 / 0.216e3 * t1137 + 0.455e3 / 0.324e3 * t1139 + 0.4e1 * t219 * t1572 * t109 + 0.7e1 / 0.72e2 * t1374 + 0.49e2 / 0.1728e4 * t1378 - 0.245e3 / 0.1728e4 * t1380;
  t1590 = t482 * t717 * t551;
  t1594 = t549 * t116 * t118 * t275;
  t1597 = t219 * t726 * t551;
  t1613 = -0.35e2 / 0.54e2 * t1382 - 0.24e2 * t1268 * t546 + 0.24e2 * t1149 * t327 * t220 + 0.343e3 / 0.82944e5 * t1085 - t1092 - t1105 + t1129 + 0.343e3 / 0.82944e5 * t1386 + 0.455e3 / 0.324e3 * t1388 + 0.7e1 / 0.12e2 * t1590 - 0.7e1 / 0.18e2 * t1594 - 0.7e1 / 0.36e2 * t1597 + 0.7e1 / 0.12e2 * t1394 - 0.7e1 / 0.18e2 * t1397 - 0.7e1 / 0.36e2 * t1399 - 0.49e2 / 0.864e3 * t1404 + 0.35e2 / 0.27e2 * t1407 - 0.6e1 * t482 * t330 * t220 - 0.6e1 * t482 * t327 * t209 + 0.4e1 * t219 * t136 * t604;
  t1617 = t149 * t734;
  t1619 = 0.2e1 * t105 * t123 * t734 + 0.2e1 * t134 * t632 + 0.4e1 * t276 * t281 + 0.2e1 * t1436 + 0.2e1 * t1202 + t319 * t215 + 0.4e1 * t1209 + 0.4e1 * t1212 + 0.2e1 * t1215 + 0.2e1 * t103 * t735 + t105 * t66 * (t1579 + t1613) + 0.2e1 * t1617;
  t1624 = t293 * t293;
  t1634 = t688 * t66;
  t1645 = 0.2e1 * t105 * t139 * t621 + 0.2e1 * t105 * t66 * t1624 + t105 * t215 * t323 + t105 * t215 * t333 + t105 * t251 * t333 + 0.4e1 * t1245 * t537 * t293 + 0.2e1 * t103 * t709 + 0.2e1 * t134 * t625 + 0.2e1 * t1234 + 0.2e1 * t1249 + 0.2e1 * t1251 + 0.2e1 * t1634;
  t1656 = t253 * t537;
  t1666 = (t52 * t66) * t138 * t293;
  t1668 = t122 * t323;
  t1669 = (t52 * t66) * t1668;
  t1671 = t105 * t251 * t323 + 0.2e1 * t103 * t702 + 0.4e1 * t103 * t704 + 0.2e1 * t689 * t123 + 0.2e1 * t134 * t622 + 0.2e1 * t639 * t139 + t319 * t251 + 0.4e1 * t276 * t294 + 0.2e1 * t1416 + 0.4e1 * t1656 + 0.4e1 * t1666 + 0.2e1 * t1669;
  t1673 = t122 * t333;
  t1674 = (t52 * t66) * t1673;
  t1680 = t645 * t122;
  t1685 = t627 * t138;
  t1688 = t253 * t293;
  t1690 = t147 * t323;
  t1692 = t9 * t1541 * t66 + 0.4e1 * t134 * t634 + t210 * t324 + t210 * t334 + 0.4e1 * t1421 + 0.4e1 * t1423 + 0.2e1 * t1425 + 0.2e1 * t1674 + 0.2e1 * t1680 + 0.4e1 * t1685 + 0.4e1 * t1688 + 0.2e1 * t1690;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[2] = t1619 + t1645 + t1671 + t1692;

  t1694 = t253 * t333;
  t1696 = t253 * t323;
  t1701 = t770 * t66;
  t1726 = t482 * t785 * t2 * t119;
  t1730 = t108 * t770 * t2 * t119;
  t1747 = t424 * t747;
  t1757 = -0.36e2 * t183 * t130 * t685 - 0.36e2 * t183 * t272 * t315 - 0.36e2 * t650 * t747 - 0.18e2 * t1335 - t1338 - 0.72e2 * t1448 - 0.36e2 * t1455 - 0.36e2 * t1468 - 0.36e2 * t1471 - 0.18e2 * t1476 - 0.18e2 * t1479 - 0.36e2 * t1747;
  t1761 = t87 * t744;
  t1763 = t35 * t299;
  t1766 = t180 * t767;
  t1786 = 0.12e2 * t444 + 0.24e2 * t1026;
  t1808 = -0.28e2 / 0.81e2 * t1013 * t750 * t93 + 0.8e1 / 0.9e1 * t661 * t193 + 0.4e1 / 0.9e1 * t575 * t306 * t93 - 0.2e1 / 0.3e1 * t578 * t192 * t306 - t260 * t671 / 0.3e1 - t188 * t756 * t93 / 0.9e1 + t90 * t1786 / 0.3e1 - 0.28e2 / 0.81e2 * t1033 * t759 * t96 - 0.8e1 / 0.9e1 * t674 * t193 + 0.4e1 / 0.9e1 * t588 * t312 * t96 + 0.2e1 / 0.3e1 * t591 * t192 * t312 - t266 * t682 / 0.3e1 - t199 * t764 * t96 / 0.9e1 - t95 * t1786 / 0.3e1;
  t1812 = -0.12e2 * t183 * t767 * t99 - 0.36e2 * t1763 * t272 - 0.6e1 * t89 * t1808 - 0.6e1 * t1001 + t1075 + t1077 - t1343 - 0.12e2 * t1761 - 0.6e1 * t1766 - t969 - t973 - t979 + t999;
  t1813 = t1757 + t1812;
  t1823 = 0.2e1 * t219 * t793 * t102 + 0.6e1 * t219 * t136 * t688 + 0.7e1 / 0.24e2 * t1726 + 0.7e1 / 0.144e3 * t1730 - 0.49e2 / 0.1152e4 * t1546 + 0.7e1 / 0.48e2 * t1550 + 0.49e2 / 0.2304e4 * t1554 + 0.35e2 / 0.36e2 * t1556 - 0.35e2 / 0.72e2 * t1558 + 0.6e1 * t219 * t286 * t318 - t108 * t1813 * t109 - 0.18e2 * t1268 * t721 + t1146 - 0.18e2 * t482 * t327 * t275 - 0.245e3 / 0.3456e4 * t1122 + 0.455e3 / 0.648e3 * t1139;
  t1833 = t549 * t116 * t118 * t318;
  t1838 = t1379 - 0.245e3 / 0.1152e4 * t1380 - t1383 + 0.343e3 / 0.165888e6 * t1085 - t1092 - t1105 + t1129 + 0.343e3 / 0.55296e5 * t1386 + 0.455e3 / 0.216e3 * t1388 + 0.7e1 / 0.8e1 * t1590 - 0.7e1 / 0.12e2 * t1594 - 0.7e1 / 0.24e2 * t1597 - 0.7e1 / 0.24e2 * t1833 - t1405 + t1408 + 0.24e2 * t1149 * t786 * t102;
  t1844 = t149 * t779;
  t1845 = t149 * t798;
  t1849 = 0.3e1 * t1694 + 0.3e1 * t1696 + 0.3e1 * t1436 + 0.3e1 * t319 * t281 + t1701 + t103 * t799 + 0.3e1 * t134 * t735 + t103 * t780 + 0.3e1 * t276 * t334 + 0.3e1 * t319 * t294 + 0.3e1 * t276 * t324 + 0.3e1 * t689 * t139 + 0.3e1 * t1617 + 0.3e1 * t1245 * t537 * t333 + t105 * t66 * (t1823 + t1838) + t9 * t1813 * t66 + t1844 + t1845 + 0.3e1 * t105 * t139 * t734;
  t1859 = (t52 * t66) * t138 * t333;
  t1877 = t645 * t138;
  t1883 = t105 * t123 * t779 + t105 * t123 * t798 + 0.3e1 * t105 * t324 * t293 + 0.3e1 * t105 * t294 * t333 + 0.3e1 * t103 * t782 + t771 * t123 + 0.3e1 * t134 * t702 + 0.6e1 * t134 * t704 + 0.3e1 * t134 * t709 + 0.3e1 * t1634 + 0.6e1 * t1656 + 0.6e1 * t1666 + 0.3e1 * t1669 + 0.3e1 * t1674 + 0.3e1 * t1680 + 0.6e1 * t1685 + 0.6e1 * t1688 + 0.3e1 * t1690 + 0.3e1 * t1859 + 0.3e1 * t1877;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[3] = t1849 + t1883;

  t1896 = t315 * t315;
  t1909 = t302 * t302;
  t1914 = t306 * t306;
  t1920 = 0.24e2 * t444 + 0.24e2 * t1026;
  t1923 = t309 * t309;
  t1928 = t312 * t312;
  t1939 = -t969 - t973 - t979 - 0.144e3 * t1747 - 0.36e2 * t183 * t1896 - 0.48e2 * t183 * t130 * t767 + t999 - 0.24e2 * t1335 - 0.72e2 * t1468 - 0.36e2 * t1476 - 0.24e2 * t1766 + t1077 - 0.48e2 * t1761 + t1075 - 0.72e2 * t1763 * t315 - 0.6e1 * t89 * (-0.28e2 / 0.81e2 * t1013 * t1909 + 0.8e1 / 0.9e1 * t661 * t306 - t188 * t1914 / 0.3e1 - 0.4e1 / 0.9e1 * t260 * t756 + t90 * t1920 / 0.3e1 - 0.28e2 / 0.81e2 * t1033 * t1923 + 0.8e1 / 0.9e1 * t674 * t312 - t199 * t1928 / 0.3e1 - 0.4e1 / 0.9e1 * t266 * t764 - t95 * t1920 / 0.3e1);
  t1952 = t326 * t326;
  t1959 = t318 * t318;
  t1966 = -t108 * t1939 * t109 - t1092 - t1105 + 0.343e3 / 0.41472e5 * t1386 + t1129 - 0.245e3 / 0.864e3 * t1380 - 0.49e2 / 0.576e3 * t1546 + 0.49e2 / 0.1152e4 * t1554 + 0.7e1 / 0.6e1 * t1726 + 0.7e1 / 0.36e2 * t1730 + 0.455e3 / 0.162e3 * t1388 + 0.35e2 / 0.18e2 * t1556 - 0.35e2 / 0.36e2 * t1558 - 0.7e1 / 0.6e1 * t1833 + t1146 + 0.24e2 * t1149 * t1952 * t109 - 0.36e2 * t482 * t327 * t318 + 0.6e1 * t219 * t1959 * t109 + 0.8e1 * t219 * t136 * t770;
  t1980 = t323 * t323;
  t1983 = t333 * t333;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[4] = 0.4e1 * t105 * t139 * t798 + t105 * t66 * t1966 + t105 * t66 * t1980 + 0.3e1 * t105 * t66 * t1983 + 0.6e1 * t105 * t324 * t333 + t9 * t1939 * t66 + 0.4e1 * t134 * t780 + 0.12e2 * t134 * t782 + 0.4e1 * t134 * t799 + 0.4e1 * t771 * t139 + 0.6e1 * t319 * t324 + 0.6e1 * t319 * t334 + 0.12e2 * t1694 + 0.12e2 * t1696 + 0.4e1 * t1701 + 0.4e1 * t1844 + 0.4e1 * t1845 + 0.12e2 * t1859 + 0.12e2 * t1877;

  t1994 = t232 * t66 * params->h * t145;
  t1995 = 0.35e2 / 0.162e3 * t1994;
  t1997 = t801 * t122 * t343;
  t2001 = t241 * t66 * params->h * t352;
  t2002 = 0.1169e4 / 0.10368e5 * t2001;
  t2004 = t336 * t250 * t343;
  t2007 = t143 * t531 * t343;
  t2011 = t942 * t527 * t243;
  t2012 = t825 * t122 * t2011;
  t2018 = t1093 * t1101;
  t2021 = 0.1e1 / t10 / t1141 * t66 * params->h * t2018 * t524 * t2;
  t2022 = 0.343e3 / 0.2654208e7 * t2021;
  t2024 = t336 * t214 * t343;
  t2027 = t810 * t820 * t352;
  t2032 = t143 * t820 * t54 * t117 * t250;
  t2035 = t143 * t474 * t343;
  t2039 = t348 * t214 * params->h * t352;
  t2043 = t348 * t250 * params->h * t352;
  t2045 = t521 * t9;
  t2049 = 0.1e1 / t2045 * t66 * params->h * t828;
  t2050 = 0.343e3 / 0.27648e5 * t2049;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[0] = -t1995 + 0.7e1 / 0.36e2 * t1997 + t2002 - t2004 / 0.12e2 + t2007 / 0.48e2 + 0.49e2 / 0.18432e5 * t2012 + t2022 - t2024 / 0.12e2 - 0.7e1 / 0.128e3 * t2027 + t2032 / 0.16e2 + t2035 / 0.48e2 + 0.7e1 / 0.768e3 * t2039 + 0.7e1 / 0.768e3 * t2043 - t2050;

  t2051 = 0.35e2 / 0.81e2 * t1994;
  t2053 = 0.1169e4 / 0.5184e4 * t2001;
  t2057 = 0.343e3 / 0.1327104e7 * t2021;
  t2064 = 0.343e3 / 0.13824e5 * t2049;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[1] = -t2051 + 0.7e1 / 0.18e2 * t1997 + t2053 - t2004 / 0.6e1 + t2007 / 0.24e2 + 0.49e2 / 0.9216e4 * t2012 + t2057 - t2024 / 0.6e1 - 0.7e1 / 0.64e2 * t2027 + t2032 / 0.8e1 + t2035 / 0.24e2 + 0.7e1 / 0.384e3 * t2039 + 0.7e1 / 0.384e3 * t2043 - t2064;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[2] = v4rho3sigma[0];

  t2065 = 0.7e1 / 0.54e2 * t1997;
  t2067 = 0.49e2 / 0.27648e5 * t2012;
  t2069 = t336 * t293 * t343;
  t2070 = t2069 / 0.18e2;
  t2072 = t143 * t621 * t343;
  t2075 = t825 * t138 * t2011;
  t2078 = 0.7e1 / 0.192e3 * t2027;
  t2079 = -t1995 + t2065 + t2002 - t2004 / 0.36e2 + t2067 + t2022 - t2070 + t2072 / 0.48e2 + 0.49e2 / 0.55296e5 * t2075 - t2024 / 0.36e2 - t2078;
  t2083 = t801 * t138 * t343;
  t2086 = t336 * t537 * t343;
  t2087 = t2086 / 0.18e2;
  t2089 = t810 * t848 * t352;
  t2092 = t143 * t1214 * t343;
  t2095 = t143 * t1208 * t343;
  t2099 = t348 * t293 * params->h * t352;
  t2100 = 0.7e1 / 0.1152e4 * t2099;
  t2102 = t143 * t1415 * t343;
  t2107 = t348 * t537 * t891 * t368 * t59;
  t2108 = 0.7e1 / 0.1152e4 * t2107;
  t2109 = 0.7e1 / 0.2304e4 * t2039 + 0.7e1 / 0.2304e4 * t2043 + 0.7e1 / 0.108e3 * t2083 - t2087 - 0.7e1 / 0.384e3 * t2089 + t2092 / 0.48e2 + t2095 / 0.24e2 + t2100 + t2102 / 0.48e2 + t2108 - t2050;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[3] = t2079 + t2109;

  t2113 = t2069 / 0.9e1;
  t2115 = 0.49e2 / 0.27648e5 * t2075;
  t2118 = -t2051 + 0.7e1 / 0.27e2 * t1997 + t2053 - t2004 / 0.18e2 + 0.49e2 / 0.13824e5 * t2012 + t2057 - t2113 + t2072 / 0.24e2 + t2115 - t2024 / 0.18e2 - 0.7e1 / 0.96e2 * t2027;
  t2121 = 0.7e1 / 0.54e2 * t2083;
  t2122 = t2086 / 0.9e1;
  t2123 = 0.7e1 / 0.192e3 * t2089;
  t2126 = 0.7e1 / 0.576e3 * t2099;
  t2128 = 0.7e1 / 0.576e3 * t2107;
  t2129 = 0.7e1 / 0.1152e4 * t2039 + 0.7e1 / 0.1152e4 * t2043 + t2121 - t2122 - t2123 + t2092 / 0.24e2 + t2095 / 0.12e2 + t2126 + t2102 / 0.24e2 + t2128 - t2064;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[4] = t2118 + t2129;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[5] = v4rho3sigma[3];

  t2133 = t143 * t734 * t343;
  t2136 = -t1995 + 0.7e1 / 0.108e3 * t1997 + t2002 + 0.49e2 / 0.55296e5 * t2012 + t2022 - t2070 + t2115 + t2133 / 0.48e2 - 0.7e1 / 0.384e3 * t2027 + t2121 - t2087;
  t2138 = t336 * t323 * t343;
  t2140 = t143 * t848;
  t2143 = t2140 * t54 * t117 * t293;
  t2146 = t143 * t1668 * t343;
  t2150 = t348 * t323 * params->h * t352;
  t2153 = t336 * t333 * t343;
  t2156 = t143 * t1673 * t343;
  t2160 = t348 * t333 * params->h * t352;
  t2162 = -t2123 + t2100 - t2138 / 0.36e2 + t2143 / 0.24e2 + t2146 / 0.48e2 + 0.7e1 / 0.2304e4 * t2150 - t2153 / 0.36e2 + t2156 / 0.48e2 + 0.7e1 / 0.2304e4 * t2160 + t2108 - t2050;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[6] = t2136 + t2162;

  t2166 = -t2051 + t2065 + t2053 + t2067 + t2057 - t2113 + 0.49e2 / 0.13824e5 * t2075 + t2133 / 0.24e2 - t2078 + 0.7e1 / 0.27e2 * t2083 - t2122;
  t2175 = -0.7e1 / 0.96e2 * t2089 + t2126 - t2138 / 0.18e2 + t2143 / 0.12e2 + t2146 / 0.24e2 + 0.7e1 / 0.1152e4 * t2150 - t2153 / 0.18e2 + t2156 / 0.24e2 + 0.7e1 / 0.1152e4 * t2160 + t2128 - t2064;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[7] = t2166 + t2175;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[8] = v4rho3sigma[6];

  t2178 = t143 * t798 * t343;
  t2188 = t2140 * t54 * t117 * t333;
  t2191 = t143 * t779 * t343;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[9] = -t1995 + t2002 + t2022 + 0.49e2 / 0.18432e5 * t2075 + t2178 / 0.48e2 + 0.7e1 / 0.36e2 * t2083 - 0.7e1 / 0.128e3 * t2089 - t2138 / 0.12e2 + 0.7e1 / 0.768e3 * t2150 - t2153 / 0.12e2 + 0.7e1 / 0.768e3 * t2160 + t2188 / 0.16e2 + t2191 / 0.48e2 - t2050;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[10] = -t2051 + t2053 + t2057 + 0.49e2 / 0.9216e4 * t2075 + t2178 / 0.24e2 + 0.7e1 / 0.18e2 * t2083 - 0.7e1 / 0.64e2 * t2089 - t2138 / 0.6e1 + 0.7e1 / 0.384e3 * t2150 - t2153 / 0.6e1 + 0.7e1 / 0.384e3 * t2160 + t2188 / 0.8e1 + t2191 / 0.24e2 - t2064;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[11] = v4rho3sigma[9];

  t2205 = t364 * t250 * t365 * t369;
  t2208 = t881 * t870 * t885;
  t2209 = 0.7e1 / 0.9216e4 * t2208;
  t2212 = t875 * t350 * t245 * t209;
  t2214 = t881 * t874;
  t2217 = t2214 * t827 * t102 * t59;
  t2218 = 0.7e1 / 0.9216e4 * t2217;
  t2221 = 0.1e1 / t10 / t522 * t66;
  t2222 = t365 * t64;
  t2225 = t2018 * t243 * t2;
  t2226 = t2221 * t2222 * t2225;
  t2227 = 0.49e2 / 0.884736e6 * t2226;
  t2229 = t364 * t214 * t892;
  t2232 = t825 * t365 * t885;
  t2233 = 0.7e1 / 0.1728e4 * t2232;
  t2234 = t811 * t372;
  t2235 = 0.77e2 / 0.3456e4 * t2234;
  t2237 = t348 * t122 * t892;
  t2238 = 0.11e2 / 0.1152e4 * t2237;
  t2240 = t364 * t250 * t892;
  t2243 = t942 * t884;
  t2244 = t881 * t122 * t2243;
  t2245 = 0.7e1 / 0.9216e4 * t2244;
  t2247 = t2221 * params->h * t2225;
  t2248 = 0.49e2 / 0.884736e6 * t2247;
  t2250 = t810 * t365 * t369;
  t2251 = 0.77e2 / 0.3456e4 * t2250;
  t2252 = t348 * t874;
  t2253 = t2252 * t877;
  t2254 = 0.11e2 / 0.1152e4 * t2253;
  t2256 = t348 * t870 * t369;
  t2257 = 0.11e2 / 0.1152e4 * t2256;
  t2258 = t107 * t1;
  t2260 = t2258 * t368 * t102;
  t2261 = t871 * t2260;
  t2265 = t364 * t214 * t365 * t369;
  t2268 = t364 * t365 * t218;
  t2271 = t2268 * t350 * t245 * t220;
  t2273 = t826 * t896;
  t2274 = 0.7e1 / 0.1728e4 * t2273;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[0] = t2205 / 0.768e3 + t2209 - t2212 / 0.768e3 - t2218 + t2227 - t2229 / 0.768e3 - t2233 - t2235 + t2238 - t2240 / 0.768e3 - t2245 - t2248 + t2251 + t2254 - t2257 - t2261 / 0.384e3 + t2265 / 0.768e3 + t2271 / 0.384e3 + t2274;

  t2276 = 0.7e1 / 0.4608e4 * t2208;
  t2278 = 0.7e1 / 0.4608e4 * t2217;
  t2279 = 0.49e2 / 0.442368e6 * t2226;
  t2281 = 0.7e1 / 0.864e3 * t2232;
  t2282 = 0.77e2 / 0.1728e4 * t2234;
  t2283 = 0.11e2 / 0.576e3 * t2237;
  t2285 = 0.7e1 / 0.4608e4 * t2244;
  t2286 = 0.49e2 / 0.442368e6 * t2247;
  t2287 = 0.77e2 / 0.1728e4 * t2250;
  t2288 = 0.11e2 / 0.576e3 * t2253;
  t2289 = 0.11e2 / 0.576e3 * t2256;
  t2293 = 0.7e1 / 0.864e3 * t2273;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[1] = t2205 / 0.384e3 + t2276 - t2212 / 0.384e3 - t2278 + t2279 - t2229 / 0.384e3 - t2281 - t2282 + t2283 - t2240 / 0.384e3 - t2285 - t2286 + t2287 + t2288 - t2289 - t2261 / 0.192e3 + t2265 / 0.384e3 + t2271 / 0.192e3 + t2293;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[2] = v4rho2sigma2[0];

  t2298 = 0.49e2 / 0.221184e6 * t2226;
  t2300 = 0.7e1 / 0.432e3 * t2232;
  t2301 = 0.77e2 / 0.864e3 * t2234;
  t2305 = 0.49e2 / 0.221184e6 * t2247;
  t2306 = 0.77e2 / 0.864e3 * t2250;
  t2312 = 0.7e1 / 0.432e3 * t2273;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[3] = t2205 / 0.192e3 + 0.7e1 / 0.2304e4 * t2208 - t2212 / 0.192e3 - 0.7e1 / 0.2304e4 * t2217 + t2298 - t2229 / 0.192e3 - t2300 - t2301 + 0.11e2 / 0.288e3 * t2237 - t2240 / 0.192e3 - 0.7e1 / 0.2304e4 * t2244 - t2305 + t2306 + 0.11e2 / 0.288e3 * t2253 - 0.11e2 / 0.288e3 * t2256 - t2261 / 0.96e2 + t2265 / 0.192e3 + t2271 / 0.96e2 + t2312;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[4] = v4rho2sigma2[1];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[5] = v4rho2sigma2[2];

  t2315 = t364 * t293 * t365 * t369;
  t2318 = t881 * t913 * t885;
  t2322 = t875 * t350 * t245 * t275;
  t2326 = t2214 * t827 * t133 * t59;
  t2332 = t364 * t537;
  t2333 = t2332 * t892;
  t2336 = t348 * t913 * t369;
  t2338 = t2252 * t918;
  t2340 = t2274 + t2315 / 0.768e3 + 0.7e1 / 0.18432e5 * t2318 - t2322 / 0.768e3 - 0.7e1 / 0.18432e5 * t2326 + 0.11e2 / 0.2304e4 * t2253 - 0.11e2 / 0.2304e4 * t2256 + 0.7e1 / 0.18432e5 * t2208 - 0.7e1 / 0.18432e5 * t2217 + t2227 - t2333 / 0.768e3 - 0.11e2 / 0.2304e4 * t2336 + 0.11e2 / 0.2304e4 * t2338;
  t2344 = t364 * t293 * t892;
  t2347 = t881 * t138 * t2243;
  t2350 = t348 * t138 * t892;
  t2352 = t914 * t2260;
  t2355 = t2332 * t2222 * t372;
  t2359 = t2268 * t350 * t917 * t102;
  t2362 = t2258 * t368 * t133;
  t2363 = t871 * t2362;
  t2365 = -t2235 - t2233 + 0.11e2 / 0.2304e4 * t2237 - 0.7e1 / 0.18432e5 * t2244 - t2248 + t2251 - t2344 / 0.768e3 - 0.7e1 / 0.18432e5 * t2347 + 0.11e2 / 0.2304e4 * t2350 - t2352 / 0.768e3 + t2355 / 0.768e3 + t2359 / 0.384e3 - t2363 / 0.768e3;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[6] = t2340 + t2365;

  t2367 = 0.7e1 / 0.9216e4 * t2318;
  t2369 = 0.7e1 / 0.9216e4 * t2326;
  t2371 = 0.11e2 / 0.1152e4 * t2336;
  t2372 = 0.11e2 / 0.1152e4 * t2338;
  t2373 = t2293 + t2315 / 0.384e3 + t2367 - t2322 / 0.384e3 - t2369 + t2254 - t2257 + t2209 - t2218 + t2279 - t2333 / 0.384e3 - t2371 + t2372;
  t2375 = 0.7e1 / 0.9216e4 * t2347;
  t2376 = 0.11e2 / 0.1152e4 * t2350;
  t2381 = -t2282 - t2281 + t2238 - t2245 - t2286 + t2287 - t2344 / 0.384e3 - t2375 + t2376 - t2352 / 0.384e3 + t2355 / 0.384e3 + t2359 / 0.192e3 - t2363 / 0.384e3;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[7] = t2373 + t2381;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[8] = v4rho2sigma2[6];

  t2383 = 0.7e1 / 0.4608e4 * t2318;
  t2385 = 0.7e1 / 0.4608e4 * t2326;
  t2387 = 0.11e2 / 0.576e3 * t2336;
  t2388 = 0.11e2 / 0.576e3 * t2338;
  t2389 = t2312 + t2315 / 0.192e3 + t2383 - t2322 / 0.192e3 - t2385 + t2288 - t2289 + t2276 - t2278 + t2298 - t2333 / 0.192e3 - t2387 + t2388;
  t2391 = 0.7e1 / 0.4608e4 * t2347;
  t2392 = 0.11e2 / 0.576e3 * t2350;
  t2397 = -t2301 - t2300 + t2283 - t2285 - t2305 + t2306 - t2344 / 0.192e3 - t2391 + t2392 - t2352 / 0.192e3 + t2355 / 0.192e3 + t2359 / 0.96e2 - t2363 / 0.192e3;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[9] = t2389 + t2397;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[10] = v4rho2sigma2[7];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[11] = v4rho2sigma2[8];

  t2399 = t364 * t333 * t892;
  t2403 = t364 * t333 * t365 * t369;
  t2407 = t875 * t350 * t245 * t318;
  t2410 = t364 * t323 * t892;
  t2412 = t914 * t2362;
  t2416 = t364 * t323 * t365 * t369;
  t2420 = t2268 * t350 * t245 * t326;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[12] = t2227 + t2367 - t2369 - t2233 - t2235 - t2248 - t2375 - t2399 / 0.768e3 + t2376 + t2403 / 0.768e3 - t2407 / 0.768e3 - t2410 / 0.768e3 + t2251 - t2371 + t2372 - t2412 / 0.384e3 + t2416 / 0.768e3 + t2420 / 0.384e3 + t2274;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[13] = t2279 + t2383 - t2385 - t2281 - t2282 - t2286 - t2391 - t2399 / 0.384e3 + t2392 + t2403 / 0.384e3 - t2407 / 0.384e3 - t2410 / 0.384e3 + t2287 - t2387 + t2388 - t2412 / 0.192e3 + t2416 / 0.384e3 + t2420 / 0.192e3 + t2293;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[14] = v4rho2sigma2[12];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[15] = t2298 + 0.7e1 / 0.2304e4 * t2318 - 0.7e1 / 0.2304e4 * t2326 - t2300 - t2301 - t2305 - 0.7e1 / 0.2304e4 * t2347 - t2399 / 0.192e3 + 0.11e2 / 0.288e3 * t2350 + t2403 / 0.192e3 - t2407 / 0.192e3 - t2410 / 0.192e3 + t2306 - 0.11e2 / 0.288e3 * t2336 + 0.11e2 / 0.288e3 * t2338 - t2412 / 0.96e2 + t2416 / 0.192e3 + t2420 / 0.96e2 + t2312;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[16] = v4rho2sigma2[13];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[17] = v4rho2sigma2[14];

  t2443 = t881 * t932 * t935;
  t2444 = t2443 / 0.2048e4;
  t2445 = t931 * t122;
  t2446 = t932 * t107;
  t2447 = t2446 * t827;
  t2448 = t2445 * t2447;
  t2450 = t218 * M_PI;
  t2451 = t527 * t102;
  t2453 = t933 * t2450 * t2451;
  t2457 = 0.1e1 / t10 / t2045 * t66;
  t2460 = t2018 * t2 * t59;
  t2461 = t2457 * t2446 * t2460;
  t2462 = 0.7e1 / 0.589824e6 * t2461;
  t2463 = t882 * t939;
  t2464 = 0.3e1 / 0.2048e4 * t2463;
  t2465 = t2222 * t827;
  t2466 = t2445 * t2465;
  t2469 = t938 * t934 * t2451;
  t2472 = t2457 * t2222 * t2460;
  t2473 = 0.7e1 / 0.196608e6 * t2472;
  t2474 = t881 * t943;
  t2475 = t2474 / 0.1024e4;
  t2476 = t2445 * t943;
  t2479 = t2457 * params->h * t2460;
  t2480 = 0.7e1 / 0.294912e6 * t2479;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[0] = -t2444 + t2448 / 0.12288e5 - t2453 / 0.6144e4 + t2462 + t2464 - t2466 / 0.4096e4 + t2469 / 0.4096e4 - t2473 - t2475 + t2476 / 0.6144e4 + t2480;

  t2481 = t2443 / 0.1024e4;
  t2484 = 0.7e1 / 0.294912e6 * t2461;
  t2485 = 0.3e1 / 0.1024e4 * t2463;
  t2488 = 0.7e1 / 0.98304e5 * t2472;
  t2489 = t2474 / 0.512e3;
  t2491 = 0.7e1 / 0.147456e6 * t2479;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[1] = -t2481 + t2448 / 0.6144e4 - t2453 / 0.3072e4 + t2484 + t2485 - t2466 / 0.2048e4 + t2469 / 0.2048e4 - t2488 - t2489 + t2476 / 0.3072e4 + t2491;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[2] = v4rhosigma3[0];

  t2492 = t2443 / 0.512e3;
  t2495 = 0.7e1 / 0.147456e6 * t2461;
  t2496 = 0.3e1 / 0.512e3 * t2463;
  t2499 = 0.7e1 / 0.49152e5 * t2472;
  t2500 = t2474 / 0.256e3;
  t2502 = 0.7e1 / 0.73728e5 * t2479;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[3] = -t2492 + t2448 / 0.3072e4 - t2453 / 0.1536e4 + t2495 + t2496 - t2466 / 0.1024e4 + t2469 / 0.1024e4 - t2499 - t2500 + t2476 / 0.1536e4 + t2502;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[4] = v4rhosigma3[1];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[5] = v4rhosigma3[2];

  t2503 = t2443 / 0.256e3;
  t2506 = 0.7e1 / 0.73728e5 * t2461;
  t2507 = 0.3e1 / 0.256e3 * t2463;
  t2510 = 0.7e1 / 0.24576e5 * t2472;
  t2511 = t2474 / 0.128e3;
  t2513 = 0.7e1 / 0.36864e5 * t2479;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[6] = -t2503 + t2448 / 0.1536e4 - t2453 / 0.768e3 + t2506 + t2507 - t2466 / 0.512e3 + t2469 / 0.512e3 - t2510 - t2511 + t2476 / 0.768e3 + t2513;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[7] = v4rhosigma3[3];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[8] = v4rhosigma3[4];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[9] = v4rhosigma3[5];

  t2514 = t931 * t138;
  t2515 = t2514 * t2447;
  t2517 = t527 * t133;
  t2519 = t933 * t2450 * t2517;
  t2521 = t2514 * t2465;
  t2524 = t938 * t934 * t2517;
  t2526 = t2514 * t943;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[10] = -t2444 + t2515 / 0.12288e5 - t2519 / 0.6144e4 + t2462 + t2464 - t2521 / 0.4096e4 + t2524 / 0.4096e4 - t2473 - t2475 + t2526 / 0.6144e4 + t2480;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[11] = -t2481 + t2515 / 0.6144e4 - t2519 / 0.3072e4 + t2484 + t2485 - t2521 / 0.2048e4 + t2524 / 0.2048e4 - t2488 - t2489 + t2526 / 0.3072e4 + t2491;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[12] = v4rhosigma3[10];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[13] = -t2492 + t2515 / 0.3072e4 - t2519 / 0.1536e4 + t2495 + t2496 - t2521 / 0.1024e4 + t2524 / 0.1024e4 - t2499 - t2500 + t2526 / 0.1536e4 + t2502;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[14] = v4rhosigma3[11];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[15] = v4rhosigma3[12];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[16] = -t2503 + t2515 / 0.1536e4 - t2519 / 0.768e3 + t2506 + t2507 - t2521 / 0.512e3 + t2524 / 0.512e3 - t2510 - t2511 + t2526 / 0.768e3 + t2513;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[17] = v4rhosigma3[13];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[18] = v4rhosigma3[14];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[19] = v4rhosigma3[15];

  t2545 = 0.1e1 / t10 / t521 * t66;
  t2546 = t365 * t365;
  t2550 = t2545 * t2546 * t218 * t2 * t2018;
  t2555 = t2545 * t932 * t107 * t1093 * t1102;
  t2560 = t2545 * t365 * t64 * t1093 * t1102;
  t2564 = t2545 * params->h * t2018 * t2;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[0] = t2550 / 0.589824e6 - t2555 / 0.98304e5 + 0.11e2 / 0.589824e6 * t2560 - t2564 / 0.98304e5;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[1] = t2550 / 0.294912e6 - t2555 / 0.49152e5 + 0.11e2 / 0.294912e6 * t2560 - t2564 / 0.49152e5;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[2] = v4sigma4[0];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[3] = t2550 / 0.147456e6 - t2555 / 0.24576e5 + 0.11e2 / 0.147456e6 * t2560 - t2564 / 0.24576e5;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[4] = v4sigma4[1];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[5] = v4sigma4[2];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[6] = t2550 / 0.73728e5 - t2555 / 0.12288e5 + 0.11e2 / 0.73728e5 * t2560 - t2564 / 0.12288e5;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[7] = v4sigma4[3];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[8] = v4sigma4[4];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[9] = v4sigma4[5];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[10] = t2550 / 0.36864e5 - t2555 / 0.6144e4 + 0.11e2 / 0.36864e5 * t2560 - t2564 / 0.6144e4;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[11] = v4sigma4[6];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[12] = v4sigma4[7];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[13] = v4sigma4[8];

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[14] = v4sigma4[9];

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}

