/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ./maple/gga_exc/gga_k_llp.mpl
  Type of functional: gga_exc
*/

#define maple2c_order 4
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC | XC_FLAGS_I_HAVE_KXC | XC_FLAGS_I_HAVE_LXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, const double *sigma, double *zk, GGA_OUT_PARAMS_NO_EXC(double *))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t4, t5, t6, t7, t8;
  double t9, t10, t11, t12, t13, t15, t16, t17;
  double t18, t19, t20, t21, t22, t24, t25, t26;
  double t27, t29, t30, t33, t34, t36, t37, t38;
  double t42, t44;

#ifndef XC_DONT_COMPILE_VXC
  double t47, t48, t49, t51, t52, t56, t57, t58;
  double t61, t62, t64, t65, t67, t68, t69, t70;
  double t73, t78, t82, t83, t87, t89, t90, t93;
  double t99;

#ifndef XC_DONT_COMPILE_FXC
  double t101, t102, t109, t111, t112, t116, t122, t123;
  double t124, t132, t135, t136, t139, t140, t143, t146;
  double t147, t150, t155, t159, t165, t174, t175, t176;
  double t177, t184, t185, t187, t192, t198, t201, t205;
  double t212, t215, t216, t219, t222, t223, t226, t232;

#ifndef XC_DONT_COMPILE_KXC
  double t244, t245, t249, t254, t263, t264, t265, t266;
  double t271, t272, t273, t279, t283, t286, t288, t293;
  double t294, t295, t297, t299, t303, t308, t312, t323;
  double t327, t335, t343, t344, t347, t348, t349, t352;
  double t353, t364, t366, t370, t375, t376, t386, t394;
  double t395, t396, t399, t400, t407, t408, t409, t417;
  double t420, t422, t426, t432, t435, t439, t443, t448;
  double t449, t454, t458, t463, t467, t473;

#ifndef XC_DONT_COMPILE_LXC
  double t486, t491, t496, t505, t518, t519, t520, t530;
  double t552, t558, t565, t575, t594, t595, t687, t751;
  double t768, t793, t874, t888, t897;
#endif

#endif

#endif

#endif

#endif


  gga_k_llp_params *params;

  assert(p->params != NULL);
  params = (gga_k_llp_params * )(p->params);

  t1 = M_CBRT6;
  t2 = t1 * t1;
  t3 = M_PI * M_PI;
  t4 = POW_1_3(t3);
  t5 = t4 * t4;
  t6 = t2 * t5;
  t7 = M_CBRT2;
  t8 = POW_1_3(rho[0]);
  t9 = t8 * t8;
  t10 = t7 * t9;
  t11 = M_CBRT3;
  t12 = t11 * t11;
  t13 = params->beta * t12;
  t15 = POW_1_3(0.1e1 / M_PI);
  t16 = 0.1e1 / t15;
  t17 = M_CBRT4;
  t18 = t16 * t17;
  t19 = t13 * t18;
  t20 = t7 * t7;
  t21 = sigma[0] * t20;
  t22 = rho[0] * rho[0];
  t24 = 0.1e1 / t9 / t22;
  t25 = params->gamma * params->beta;
  t26 = sqrt(sigma[0]);
  t27 = t25 * t26;
  t29 = 0.1e1 / t8 / rho[0];
  t30 = t7 * t29;
  t33 = log(t26 * t7 * t29 + sqrt(POW_2(t26 * t7 * t29) + 0.1e1));
  t34 = t30 * t33;
  t36 = 0.10e1 + t27 * t34;
  t37 = 0.1e1 / t36;
  t38 = t24 * t37;
  t42 = 0.10e1 + 0.2e1 / 0.9e1 * t19 * t21 * t38;
  t44 = t6 * t10 * t42;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = 0.3e1 / 0.20e2 * t44;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t47 = t9 * rho[0] * t2;
  t48 = t5 * t7;
  t49 = t22 * rho[0];
  t51 = 0.1e1 / t9 / t49;
  t52 = t51 * t37;
  t56 = t36 * t36;
  t57 = 0.1e1 / t56;
  t58 = t24 * t57;
  t61 = t7 / t8 / t22;
  t62 = t61 * t33;
  t64 = t25 * sigma[0];
  t65 = t20 * t51;
  t67 = t21 * t24 + 0.1e1;
  t68 = sqrt(t67);
  t69 = 0.1e1 / t68;
  t70 = t65 * t69;
  t73 = -0.4e1 / 0.3e1 * t27 * t62 - 0.4e1 / 0.3e1 * t64 * t70;
  t78 = -0.16e2 / 0.27e2 * t19 * t21 * t52 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t73;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t44 / 0.4e1 + 0.3e1 / 0.20e2 * t47 * t48 * t78;

  t82 = t13 * t16;
  t83 = t17 * t20;
  t87 = t25 / t26;
  t89 = t20 * t24;
  t90 = t89 * t69;
  t93 = t25 * t90 / 0.2e1 + t87 * t34 / 0.2e1;
  t99 = t48 * (-0.2e1 / 0.9e1 * t19 * t21 * t58 * t93 + 0.2e1 / 0.9e1 * t82 * t83 * t38);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.3e1 / 0.20e2 * t47 * t99;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t101 = 0.1e1 / t8;
  t102 = t7 * t101;
  t109 = t22 * t22;
  t111 = 0.1e1 / t9 / t109;
  t112 = t111 * t37;
  t116 = t51 * t57;
  t122 = 0.1e1 / t56 / t36;
  t123 = t24 * t122;
  t124 = t73 * t73;
  t132 = t7 / t8 / t49 * t33;
  t135 = t20 * t111;
  t136 = t135 * t69;
  t139 = sigma[0] * sigma[0];
  t140 = t25 * t139;
  t143 = 0.1e1 / t8 / t109 / t49;
  t146 = 0.1e1 / t68 / t67;
  t147 = t7 * t143 * t146;
  t150 = 0.28e2 / 0.9e1 * t27 * t132 + 0.20e2 / 0.3e1 * t64 * t136 - 0.32e2 / 0.9e1 * t140 * t147;
  t155 = 0.176e3 / 0.81e2 * t19 * t21 * t112 + 0.32e2 / 0.27e2 * t19 * t21 * t116 * t73 + 0.4e1 / 0.9e1 * t19 * t21 * t123 * t124 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t150;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = t6 * t102 * t42 / 0.6e1 + t6 * t10 * t78 / 0.2e1 + 0.3e1 / 0.20e2 * t47 * t48 * t155;

  t159 = t9 * t2;
  t165 = t57 * t73;
  t174 = t13 * t18 * sigma[0];
  t175 = t122 * t93;
  t176 = t175 * t73;
  t177 = t89 * t176;
  t184 = t25 * t7;
  t185 = t109 * t22;
  t187 = 0.1e1 / t8 / t185;
  t192 = -0.2e1 / 0.3e1 * t87 * t62 - 0.2e1 * t25 * t70 + 0.4e1 / 0.3e1 * t184 * t187 * t146 * sigma[0];
  t198 = t48 * (-0.16e2 / 0.27e2 * t82 * t83 * t52 - 0.2e1 / 0.9e1 * t19 * t89 * t165 + 0.16e2 / 0.27e2 * t19 * t21 * t116 * t93 + 0.4e1 / 0.9e1 * t174 * t177 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t192);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t159 * t99 / 0.4e1 + 0.3e1 / 0.20e2 * t47 * t198;

  t201 = t57 * t93;
  t205 = t93 * t93;
  t212 = t25 / t26 / sigma[0];
  t215 = 0.1e1 / sigma[0];
  t216 = t25 * t215;
  t219 = t109 * rho[0];
  t222 = t7 / t8 / t219;
  t223 = t222 * t146;
  t226 = -t212 * t34 / 0.4e1 + t216 * t90 / 0.4e1 - t25 * t223 / 0.2e1;
  t232 = t48 * (-0.4e1 / 0.9e1 * t19 * t89 * t201 + 0.4e1 / 0.9e1 * t19 * t21 * t123 * t205 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t226);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.3e1 / 0.20e2 * t47 * t232;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t244 = 0.1e1 / t9 / t219;
  t245 = t244 * t37;
  t249 = t111 * t57;
  t254 = t51 * t122;
  t263 = t56 * t56;
  t264 = 0.1e1 / t263;
  t265 = t24 * t264;
  t266 = t124 * t73;
  t271 = t122 * t73;
  t272 = t271 * t150;
  t273 = t89 * t272;
  t279 = t7 / t8 / t109 * t33;
  t283 = t20 * t244 * t69;
  t286 = t109 * t109;
  t288 = 0.1e1 / t8 / t286;
  t293 = t139 * sigma[0];
  t294 = t286 * t49;
  t295 = 0.1e1 / t294;
  t297 = t67 * t67;
  t299 = 0.1e1 / t68 / t297;
  t303 = -0.280e3 / 0.27e2 * t27 * t279 - 0.952e3 / 0.27e2 * t64 * t283 + 0.1184e4 / 0.27e2 * t140 * t7 * t288 * t146 - 0.256e3 / 0.9e1 * t25 * t293 * t295 * t299;
  t308 = -0.2464e4 / 0.243e3 * t19 * t21 * t245 - 0.176e3 / 0.27e2 * t19 * t21 * t249 * t73 - 0.32e2 / 0.9e1 * t19 * t21 * t254 * t124 + 0.16e2 / 0.9e1 * t19 * t21 * t116 * t150 - 0.4e1 / 0.3e1 * t19 * t21 * t265 * t266 + 0.4e1 / 0.3e1 * t174 * t273 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t303;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = -t6 * t30 * t42 / 0.18e2 + t6 * t102 * t78 / 0.2e1 + 0.3e1 / 0.4e1 * t6 * t10 * t155 + 0.3e1 / 0.20e2 * t47 * t48 * t308;

  t312 = t101 * t2;
  t323 = t122 * t124;
  t327 = t57 * t150;
  t335 = t65 * t176;
  t343 = t264 * t93 * t124;
  t344 = t89 * t343;
  t347 = t122 * t192;
  t348 = t347 * t73;
  t349 = t89 * t348;
  t352 = t175 * t150;
  t353 = t89 * t352;
  t364 = t286 * t22;
  t366 = 0.1e1 / t364 * t299;
  t370 = 0.14e2 / 0.9e1 * t87 * t132 + 0.74e2 / 0.9e1 * t25 * t136 - 0.124e3 / 0.9e1 * t184 * t143 * t146 * sigma[0] + 0.32e2 / 0.3e1 * t25 * t366 * t139;
  t375 = 0.176e3 / 0.81e2 * t82 * t83 * t112 + 0.32e2 / 0.27e2 * t19 * t65 * t165 + 0.4e1 / 0.9e1 * t19 * t89 * t323 - 0.2e1 / 0.9e1 * t19 * t89 * t327 - 0.176e3 / 0.81e2 * t19 * t21 * t249 * t93 - 0.64e2 / 0.27e2 * t174 * t335 + 0.32e2 / 0.27e2 * t19 * t21 * t116 * t192 - 0.4e1 / 0.3e1 * t174 * t344 + 0.8e1 / 0.9e1 * t174 * t349 + 0.4e1 / 0.9e1 * t174 * t353 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t370;
  t376 = t48 * t375;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = t312 * t99 / 0.6e1 + t159 * t198 / 0.2e1 + 0.3e1 / 0.20e2 * t47 * t376;

  t386 = t57 * t192;
  t394 = t264 * t205;
  t395 = t394 * t73;
  t396 = t89 * t395;
  t399 = t175 * t192;
  t400 = t89 * t399;
  t407 = t122 * t226;
  t408 = t407 * t73;
  t409 = t89 * t408;
  t417 = t7 * t187 * t146;
  t420 = t286 * rho[0];
  t422 = 0.1e1 / t420 * t299;
  t426 = t212 * t62 / 0.3e1 - t216 * t70 / 0.3e1 + 0.10e2 / 0.3e1 * t25 * t417 - 0.4e1 * t25 * t422 * sigma[0];
  t432 = t48 * (0.32e2 / 0.27e2 * t19 * t65 * t201 + 0.8e1 / 0.9e1 * t19 * t177 - 0.4e1 / 0.9e1 * t19 * t89 * t386 - 0.32e2 / 0.27e2 * t19 * t21 * t254 * t205 - 0.4e1 / 0.3e1 * t174 * t396 + 0.8e1 / 0.9e1 * t174 * t400 + 0.16e2 / 0.27e2 * t19 * t21 * t116 * t226 + 0.4e1 / 0.9e1 * t174 * t409 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t426);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = t159 * t232 / 0.4e1 + 0.3e1 / 0.20e2 * t47 * t432;

  t435 = t122 * t205;
  t439 = t57 * t226;
  t443 = t205 * t93;
  t448 = t175 * t226;
  t449 = t89 * t448;
  t454 = t25 / t26 / t139;
  t458 = t25 / t139;
  t463 = 0.1e1 / t286;
  t467 = 0.3e1 / 0.8e1 * t454 * t34 - 0.3e1 / 0.8e1 * t458 * t90 - t216 * t223 / 0.4e1 + 0.3e1 / 0.2e1 * t25 * t463 * t299;
  t473 = t48 * (0.4e1 / 0.3e1 * t19 * t89 * t435 - 0.2e1 / 0.3e1 * t19 * t89 * t439 - 0.4e1 / 0.3e1 * t19 * t21 * t265 * t443 + 0.4e1 / 0.3e1 * t174 * t449 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * t467);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = 0.3e1 / 0.20e2 * t47 * t473;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t486 = 0.1e1 / t9 / t185;
  t491 = t244 * t57;
  t496 = t111 * t122;
  t505 = t51 * t264;
  t518 = 0.1e1 / t263 / t36;
  t519 = t24 * t518;
  t520 = t124 * t124;
  t530 = t150 * t150;
  t552 = t286 * t109;
  t558 = t139 * t139;
  t565 = 0.1e1 / t68 / t297 / t67;
  t575 = 0.41888e5 / 0.729e3 * t19 * t21 * t486 * t37 + 0.9856e4 / 0.243e3 * t19 * t21 * t491 * t73 + 0.704e3 / 0.27e2 * t19 * t21 * t496 * t124 - 0.352e3 / 0.27e2 * t19 * t21 * t249 * t150 + 0.128e3 / 0.9e1 * t19 * t21 * t505 * t266 - 0.128e3 / 0.9e1 * t174 * t65 * t272 + 0.64e2 / 0.27e2 * t19 * t21 * t116 * t303 + 0.16e2 / 0.3e1 * t19 * t21 * t519 * t520 - 0.8e1 * t174 * t89 * t264 * t124 * t150 + 0.4e1 / 0.3e1 * t19 * t21 * t123 * t530 + 0.16e2 / 0.9e1 * t174 * t89 * t271 * t303 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * (0.3640e4 / 0.81e2 * t27 * t222 * t33 + 0.5768e4 / 0.27e2 * t64 * t20 * t486 * t69 - 0.37216e5 / 0.81e2 * t140 * t7 / t8 / t420 * t146 + 0.17920e5 / 0.27e2 * t25 * t293 / t552 * t299 - 0.5120e4 / 0.27e2 * t25 * t558 / t9 / t286 / t185 * t565 * t20);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = 0.2e1 / 0.27e2 * t6 * t61 * t42 - 0.2e1 / 0.9e1 * t6 * t30 * t78 + t6 * t102 * t155 + t6 * t10 * t308 + 0.3e1 / 0.20e2 * t47 * t48 * t575;

  t594 = t89 * t264;
  t595 = t93 * t73;
  t687 = -0.176e3 / 0.27e2 * t19 * t21 * t249 * t192 + 0.16e2 / 0.9e1 * t19 * t21 * t116 * t370 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * (-0.140e3 / 0.27e2 * t87 * t279 - 0.364e3 / 0.9e1 * t25 * t283 + 0.3320e4 / 0.27e2 * t184 * t288 * t146 * sigma[0] - 0.1952e4 / 0.9e1 * t25 * t295 * t299 * t139 + 0.640e3 / 0.9e1 * t25 / t9 / t286 / t219 * t565 * t293 * t20) + 0.2464e4 / 0.243e3 * t19 * t21 * t491 * t93 + 0.352e3 / 0.27e2 * t174 * t135 * t176 - 0.64e2 / 0.9e1 * t174 * t65 * t348 - 0.32e2 / 0.9e1 * t174 * t65 * t352 - 0.4e1 * t174 * t89 * t264 * t192 * t124 + 0.4e1 / 0.3e1 * t174 * t89 * t122 * t370 * t73 + 0.4e1 / 0.3e1 * t174 * t89 * t347 * t150 + 0.4e1 / 0.9e1 * t174 * t89 * t175 * t303;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[0] = -t29 * t2 * t99 / 0.18e2 + t312 * t198 / 0.2e1 + 0.3e1 / 0.4e1 * t159 * t376 + 0.3e1 / 0.20e2 * t47 * t48 * (0.32e2 / 0.3e1 * t174 * t65 * t343 + 0.16e2 / 0.3e1 * t174 * t89 * t518 * t93 * t266 - 0.4e1 * t174 * t594 * t595 * t150 - 0.2464e4 / 0.243e3 * t82 * t83 * t245 - 0.176e3 / 0.27e2 * t19 * t135 * t165 + 0.16e2 / 0.9e1 * t19 * t65 * t327 - 0.2e1 / 0.9e1 * t19 * t89 * t57 * t303 - 0.32e2 / 0.9e1 * t19 * t65 * t323 - 0.4e1 / 0.3e1 * t19 * t89 * t264 * t266 + 0.4e1 / 0.3e1 * t19 * t273 + t687);

  t751 = 0.16e2 / 0.3e1 * t174 * t89 * t518 * t205 * t124 - 0.16e2 / 0.3e1 * t174 * t594 * t595 * t192 - 0.4e1 / 0.3e1 * t174 * t89 * t264 * t226 * t124 + 0.64e2 / 0.27e2 * t19 * t65 * t386 - 0.4e1 / 0.9e1 * t19 * t89 * t57 * t370 - 0.352e3 / 0.81e2 * t19 * t135 * t201 - 0.128e3 / 0.27e2 * t19 * t335 + 0.16e2 / 0.9e1 * t19 * t349 + 0.8e1 / 0.9e1 * t19 * t353 + 0.32e2 / 0.27e2 * t19 * t21 * t116 * t426 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * (-0.7e1 / 0.9e1 * t212 * t132 + 0.7e1 / 0.9e1 * t216 * t136 - 0.22e2 * t25 * t147 + 0.188e3 / 0.3e1 * t25 * t366 * sigma[0] - 0.80e2 / 0.3e1 * t25 / t9 / t552 * t565 * t139 * t20);
  t768 = t192 * t192;
  t793 = -0.8e1 / 0.3e1 * t19 * t344 + 0.352e3 / 0.81e2 * t19 * t21 * t496 * t205 + 0.64e2 / 0.9e1 * t174 * t65 * t395 - 0.128e3 / 0.27e2 * t174 * t65 * t399 - 0.4e1 / 0.3e1 * t174 * t89 * t394 * t150 + 0.8e1 / 0.9e1 * t19 * t21 * t123 * t768 + 0.8e1 / 0.9e1 * t174 * t89 * t175 * t370 - 0.176e3 / 0.81e2 * t19 * t21 * t249 * t226 - 0.64e2 / 0.27e2 * t174 * t65 * t408 + 0.8e1 / 0.9e1 * t174 * t89 * t122 * t426 * t73 + 0.4e1 / 0.9e1 * t174 * t89 * t407 * t150;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[0] = t312 * t232 / 0.6e1 + t159 * t432 / 0.2e1 + 0.3e1 / 0.20e2 * t47 * t48 * (t751 + t793);

  t874 = -0.32e2 / 0.9e1 * t19 * t65 * t435 - 0.4e1 * t19 * t396 + 0.8e1 / 0.3e1 * t19 * t400 + 0.16e2 / 0.9e1 * t19 * t65 * t439 + 0.4e1 / 0.3e1 * t19 * t409 - 0.2e1 / 0.3e1 * t19 * t89 * t57 * t426 + 0.32e2 / 0.9e1 * t19 * t21 * t505 * t443 + 0.16e2 / 0.3e1 * t174 * t89 * t518 * t443 * t73 - 0.4e1 * t174 * t89 * t394 * t192 - 0.32e2 / 0.9e1 * t174 * t65 * t448 - 0.4e1 * t174 * t594 * t93 * t226 * t73 + 0.4e1 / 0.3e1 * t174 * t89 * t347 * t226 + 0.4e1 / 0.3e1 * t174 * t89 * t175 * t426 + 0.16e2 / 0.27e2 * t19 * t21 * t116 * t467 + 0.4e1 / 0.9e1 * t174 * t89 * t122 * t467 * t73 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * (-t454 * t62 / 0.2e1 + t458 * t70 / 0.2e1 + t216 * t417 / 0.3e1 - 0.14e2 * t25 * t422 + 0.10e2 * t25 / t9 / t294 * t565 * sigma[0] * t20);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[0] = t159 * t473 / 0.4e1 + 0.3e1 / 0.20e2 * t47 * t48 * t874;

  t888 = t205 * t205;
  t897 = t226 * t226;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[0] = 0.3e1 / 0.20e2 * t47 * t48 * (-0.16e2 / 0.3e1 * t19 * t89 * t264 * t443 + 0.16e2 / 0.3e1 * t19 * t449 - 0.8e1 / 0.9e1 * t19 * t89 * t57 * t467 + 0.16e2 / 0.3e1 * t19 * t21 * t519 * t888 - 0.8e1 * t174 * t89 * t394 * t226 + 0.4e1 / 0.3e1 * t19 * t21 * t123 * t897 + 0.16e2 / 0.9e1 * t174 * t89 * t175 * t467 - 0.2e1 / 0.9e1 * t19 * t21 * t58 * (-0.15e2 / 0.16e2 * t25 / t26 / t293 * t34 + 0.15e2 / 0.16e2 * t25 / t293 * t90 + 0.5e1 / 0.8e1 * t458 * t223 + 0.3e1 / 0.4e1 * t25 * t215 * t463 * t299 - 0.15e2 / 0.4e1 * t25 / t9 / t364 * t565 * t20));

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}


static inline void
func_ferr(const xc_func_type *p, int order, const double *rho, const double *sigma, double *zk, GGA_OUT_PARAMS_NO_EXC(double *))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t4, t5, t6, t7, t8;
  double t9, t10, t11, t13, t14, t15, t16, t17;
  double t18, t20, t21, t22, t24, t25, t26, t29;
  double t30, t35, t37;

#ifndef XC_DONT_COMPILE_VXC
  double t40, t41, t43, t48, t49, t50, t51, t52;
  double t54, t58, t59, t60, t61, t65, t66, t70;
  double t74, t77, t84, t85, t90;

#ifndef XC_DONT_COMPILE_FXC
  double t92, t98, t100, t109, t110, t111, t116, t121;
  double t125, t128, t131, t135, t136, t140, t144, t147;
  double t157, t158, t169, t171, t172, t176, t177, t182;
  double t188, t189, t194, t198, t202, t204, t208, t209;
  double t214;

#ifndef XC_DONT_COMPILE_KXC
  double t225, t239, t240, t241, t242, t246, t247, t252;
  double t257, t261, t263, t268, t269, t270, t272, t274;
  double t278, t279, t283, t287, t291, t314, t318, t319;
  double t323, t334, t338, t340, t344, t345, t349, t350;
  double t358, t359, t369, t370, t374, t381, t382, t396;
  double t398, t401, t402, t407, t416, t417, t421, t426;
  double t431, t440, t444, t445, t450;

#ifndef XC_DONT_COMPILE_LXC
  double t465, t489, t490, t500, t523, t529, t536, t545;
  double t608, t609, t657, t688, t703, t769, t812, t858;
  double t871, t880;
#endif

#endif

#endif

#endif

#endif


  gga_k_llp_params *params;

  assert(p->params != NULL);
  params = (gga_k_llp_params * )(p->params);

  t1 = M_CBRT6;
  t2 = t1 * t1;
  t3 = M_PI * M_PI;
  t4 = POW_1_3(t3);
  t5 = t4 * t4;
  t6 = t2 * t5;
  t7 = POW_1_3(rho[0]);
  t8 = t7 * t7;
  t9 = M_CBRT3;
  t10 = t9 * t9;
  t11 = params->beta * t10;
  t13 = POW_1_3(0.1e1 / M_PI);
  t14 = 0.1e1 / t13;
  t15 = t11 * t14;
  t16 = M_CBRT4;
  t17 = t16 * sigma[0];
  t18 = rho[0] * rho[0];
  t20 = 0.1e1 / t8 / t18;
  t21 = params->gamma * params->beta;
  t22 = sqrt(sigma[0]);
  t24 = 0.1e1 / t7 / rho[0];
  t25 = t22 * t24;
  t26 = log(t25 + sqrt(t25 * t25 + 0.1e1));
  t29 = 0.10e1 + t21 * t25 * t26;
  t30 = 0.1e1 / t29;
  t35 = 0.10e1 + 0.2e1 / 0.9e1 * t15 * t17 * t20 * t30;
  t37 = t6 * t8 * t35;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = 0.3e1 / 0.10e2 * t37;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t40 = t8 * rho[0] * t2;
  t41 = t18 * rho[0];
  t43 = 0.1e1 / t8 / t41;
  t48 = t14 * t16;
  t49 = t11 * t48;
  t50 = sigma[0] * t20;
  t51 = t29 * t29;
  t52 = 0.1e1 / t51;
  t54 = 0.1e1 / t7 / t18;
  t58 = sigma[0] * t43;
  t59 = t50 + 0.1e1;
  t60 = sqrt(t59);
  t61 = 0.1e1 / t60;
  t65 = -0.4e1 / 0.3e1 * t21 * t22 * t54 * t26 - 0.4e1 / 0.3e1 * t21 * t58 * t61;
  t66 = t52 * t65;
  t70 = -0.16e2 / 0.27e2 * t15 * t17 * t43 * t30 - 0.2e1 / 0.9e1 * t49 * t50 * t66;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t37 / 0.2e1 + 0.3e1 / 0.10e2 * t40 * t5 * t70;

  t74 = t16 * t20;
  t77 = 0.1e1 / t22;
  t84 = t21 * t77 * t24 * t26 / 0.2e1 + t21 * t20 * t61 / 0.2e1;
  t85 = t52 * t84;
  t90 = t5 * (0.2e1 / 0.9e1 * t15 * t74 * t30 - 0.2e1 / 0.9e1 * t49 * t50 * t85);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.3e1 / 0.10e2 * t40 * t90;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t92 = 0.1e1 / t7;
  t98 = t18 * t18;
  t100 = 0.1e1 / t8 / t98;
  t109 = 0.1e1 / t51 / t29;
  t110 = t65 * t65;
  t111 = t109 * t110;
  t116 = 0.1e1 / t7 / t41;
  t121 = sigma[0] * t100;
  t125 = sigma[0] * sigma[0];
  t128 = 0.1e1 / t7 / t98 / t41;
  t131 = 0.1e1 / t60 / t59;
  t135 = 0.28e2 / 0.9e1 * t21 * t22 * t116 * t26 + 0.20e2 / 0.3e1 * t21 * t121 * t61 - 0.16e2 / 0.9e1 * t21 * t125 * t128 * t131;
  t136 = t52 * t135;
  t140 = 0.176e3 / 0.81e2 * t15 * t17 * t100 * t30 + 0.32e2 / 0.27e2 * t49 * t58 * t66 + 0.4e1 / 0.9e1 * t49 * t50 * t111 - 0.2e1 / 0.9e1 * t49 * t50 * t136;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = t6 * t92 * t35 / 0.3e1 + t6 * t8 * t70 + 0.3e1 / 0.10e2 * t40 * t5 * t140;

  t144 = t8 * t2;
  t147 = t16 * t43;
  t157 = t109 * t84;
  t158 = t157 * t65;
  t169 = t98 * t18;
  t171 = 0.1e1 / t7 / t169;
  t172 = t171 * t131;
  t176 = -0.2e1 / 0.3e1 * t21 * t77 * t54 * t26 - 0.2e1 * t21 * t43 * t61 + 0.2e1 / 0.3e1 * t21 * t172 * sigma[0];
  t177 = t52 * t176;
  t182 = t5 * (-0.16e2 / 0.27e2 * t15 * t147 * t30 - 0.2e1 / 0.9e1 * t15 * t74 * t66 + 0.16e2 / 0.27e2 * t49 * t58 * t85 + 0.4e1 / 0.9e1 * t49 * t50 * t158 - 0.2e1 / 0.9e1 * t49 * t50 * t177);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t144 * t90 / 0.2e1 + 0.3e1 / 0.10e2 * t40 * t182;

  t188 = t84 * t84;
  t189 = t109 * t188;
  t194 = 0.1e1 / t22 / sigma[0];
  t198 = 0.1e1 / sigma[0];
  t202 = t98 * rho[0];
  t204 = 0.1e1 / t7 / t202;
  t208 = -t21 * t194 * t24 * t26 / 0.4e1 + t21 * t198 * t20 * t61 / 0.4e1 - t21 * t204 * t131 / 0.4e1;
  t209 = t52 * t208;
  t214 = t5 * (-0.4e1 / 0.9e1 * t15 * t74 * t85 + 0.4e1 / 0.9e1 * t49 * t50 * t189 - 0.2e1 / 0.9e1 * t49 * t50 * t209);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.3e1 / 0.10e2 * t40 * t214;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t225 = 0.1e1 / t8 / t202;
  t239 = t51 * t51;
  t240 = 0.1e1 / t239;
  t241 = t110 * t65;
  t242 = t240 * t241;
  t246 = t109 * t65;
  t247 = t246 * t135;
  t252 = 0.1e1 / t7 / t98;
  t257 = sigma[0] * t225;
  t261 = t98 * t98;
  t263 = 0.1e1 / t7 / t261;
  t268 = t125 * sigma[0];
  t269 = t261 * t41;
  t270 = 0.1e1 / t269;
  t272 = t59 * t59;
  t274 = 0.1e1 / t60 / t272;
  t278 = -0.280e3 / 0.27e2 * t21 * t22 * t252 * t26 - 0.952e3 / 0.27e2 * t21 * t257 * t61 + 0.592e3 / 0.27e2 * t21 * t125 * t263 * t131 - 0.64e2 / 0.9e1 * t21 * t268 * t270 * t274;
  t279 = t52 * t278;
  t283 = -0.2464e4 / 0.243e3 * t15 * t17 * t225 * t30 - 0.176e3 / 0.27e2 * t49 * t121 * t66 - 0.32e2 / 0.9e1 * t49 * t58 * t111 + 0.16e2 / 0.9e1 * t49 * t58 * t136 - 0.4e1 / 0.3e1 * t49 * t50 * t242 + 0.4e1 / 0.3e1 * t49 * t50 * t247 - 0.2e1 / 0.9e1 * t49 * t50 * t279;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = -t6 * t24 * t35 / 0.9e1 + t6 * t92 * t70 + 0.3e1 / 0.2e1 * t6 * t8 * t140 + 0.3e1 / 0.10e2 * t40 * t5 * t283;

  t287 = t92 * t2;
  t291 = t16 * t100;
  t314 = t240 * t84 * t110;
  t318 = t109 * t176;
  t319 = t318 * t65;
  t323 = t157 * t135;
  t334 = t128 * t131;
  t338 = t261 * t18;
  t340 = 0.1e1 / t338 * t274;
  t344 = 0.14e2 / 0.9e1 * t21 * t77 * t116 * t26 + 0.74e2 / 0.9e1 * t21 * t100 * t61 - 0.62e2 / 0.9e1 * t21 * t334 * sigma[0] + 0.8e1 / 0.3e1 * t21 * t340 * t125;
  t345 = t52 * t344;
  t349 = 0.176e3 / 0.81e2 * t15 * t291 * t30 + 0.32e2 / 0.27e2 * t15 * t147 * t66 + 0.4e1 / 0.9e1 * t15 * t74 * t111 - 0.2e1 / 0.9e1 * t15 * t74 * t136 - 0.176e3 / 0.81e2 * t49 * t121 * t85 - 0.64e2 / 0.27e2 * t49 * t58 * t158 + 0.32e2 / 0.27e2 * t49 * t58 * t177 - 0.4e1 / 0.3e1 * t49 * t50 * t314 + 0.8e1 / 0.9e1 * t49 * t50 * t319 + 0.4e1 / 0.9e1 * t49 * t50 * t323 - 0.2e1 / 0.9e1 * t49 * t50 * t345;
  t350 = t5 * t349;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = t287 * t90 / 0.3e1 + t144 * t182 + 0.3e1 / 0.10e2 * t40 * t350;

  t358 = t20 * t109;
  t359 = t84 * t65;
  t369 = t240 * t188;
  t370 = t369 * t65;
  t374 = t157 * t176;
  t381 = t109 * t208;
  t382 = t381 * t65;
  t396 = t261 * rho[0];
  t398 = 0.1e1 / t396 * t274;
  t401 = t21 * t194 * t54 * t26 / 0.3e1 - t21 * t198 * t43 * t61 / 0.3e1 + 0.5e1 / 0.3e1 * t21 * t172 - t21 * t398 * sigma[0];
  t402 = t52 * t401;
  t407 = t5 * (0.32e2 / 0.27e2 * t15 * t147 * t85 + 0.8e1 / 0.9e1 * t49 * t358 * t359 - 0.4e1 / 0.9e1 * t15 * t74 * t177 - 0.32e2 / 0.27e2 * t49 * t58 * t189 - 0.4e1 / 0.3e1 * t49 * t50 * t370 + 0.8e1 / 0.9e1 * t49 * t50 * t374 + 0.16e2 / 0.27e2 * t49 * t58 * t209 + 0.4e1 / 0.9e1 * t49 * t50 * t382 - 0.2e1 / 0.9e1 * t49 * t50 * t402);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = t144 * t214 / 0.2e1 + 0.3e1 / 0.10e2 * t40 * t407;

  t416 = t188 * t84;
  t417 = t240 * t416;
  t421 = t157 * t208;
  t426 = 0.1e1 / t22 / t125;
  t431 = 0.1e1 / t125;
  t440 = 0.1e1 / t261;
  t444 = 0.3e1 / 0.8e1 * t21 * t426 * t24 * t26 - 0.3e1 / 0.8e1 * t21 * t431 * t20 * t61 - t21 * t198 * t204 * t131 / 0.8e1 + 0.3e1 / 0.8e1 * t21 * t440 * t274;
  t445 = t52 * t444;
  t450 = t5 * (0.4e1 / 0.3e1 * t15 * t74 * t189 - 0.2e1 / 0.3e1 * t15 * t74 * t209 - 0.4e1 / 0.3e1 * t49 * t50 * t417 + 0.4e1 / 0.3e1 * t49 * t50 * t421 - 0.2e1 / 0.9e1 * t49 * t50 * t445);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = 0.3e1 / 0.10e2 * t40 * t450;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t465 = 0.1e1 / t8 / t169;
  t489 = 0.1e1 / t239 / t29;
  t490 = t110 * t110;
  t500 = t135 * t135;
  t523 = t261 * t98;
  t529 = t125 * t125;
  t536 = 0.1e1 / t60 / t272 / t59;
  t545 = 0.41888e5 / 0.729e3 * t15 * t17 * t465 * t30 + 0.9856e4 / 0.243e3 * t49 * t257 * t66 + 0.704e3 / 0.27e2 * t49 * t121 * t111 - 0.352e3 / 0.27e2 * t49 * t121 * t136 + 0.128e3 / 0.9e1 * t49 * t58 * t242 - 0.128e3 / 0.9e1 * t49 * t58 * t247 + 0.64e2 / 0.27e2 * t49 * t58 * t279 + 0.16e2 / 0.3e1 * t49 * t50 * t489 * t490 - 0.8e1 * t49 * t50 * t240 * t110 * t135 + 0.4e1 / 0.3e1 * t49 * t50 * t109 * t500 + 0.16e2 / 0.9e1 * t49 * t50 * t246 * t278 - 0.2e1 / 0.9e1 * t49 * t50 * t52 * (0.3640e4 / 0.81e2 * t21 * t22 * t204 * t26 + 0.5768e4 / 0.27e2 * t21 * sigma[0] * t465 * t61 - 0.18608e5 / 0.81e2 * t21 * t125 / t7 / t396 * t131 + 0.4480e4 / 0.27e2 * t21 * t268 / t523 * t274 - 0.1280e4 / 0.27e2 * t21 * t529 / t8 / t261 / t169 * t536);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = 0.4e1 / 0.27e2 * t6 * t54 * t35 - 0.4e1 / 0.9e1 * t6 * t24 * t70 + 0.2e1 * t6 * t92 * t140 + 0.2e1 * t6 * t8 * t283 + 0.3e1 / 0.10e2 * t40 * t5 * t545;

  t608 = t11 * t48 * sigma[0];
  t609 = t20 * t240;
  t657 = 0.4e1 / 0.3e1 * t49 * t50 * t318 * t135 + 0.4e1 / 0.9e1 * t49 * t50 * t157 * t278 + 0.32e2 / 0.3e1 * t49 * t58 * t314 + 0.16e2 / 0.3e1 * t49 * t50 * t489 * t84 * t241 - 0.4e1 * t608 * t609 * t359 * t135 - 0.32e2 / 0.9e1 * t15 * t147 * t111 - 0.4e1 / 0.3e1 * t15 * t74 * t242 + 0.4e1 / 0.3e1 * t49 * t358 * t65 * t135 - 0.176e3 / 0.27e2 * t49 * t121 * t177 + 0.16e2 / 0.9e1 * t49 * t58 * t345 - 0.2e1 / 0.9e1 * t49 * t50 * t52 * (-0.140e3 / 0.27e2 * t21 * t77 * t252 * t26 - 0.364e3 / 0.9e1 * t21 * t225 * t61 + 0.1660e4 / 0.27e2 * t21 * t263 * t131 * sigma[0] - 0.488e3 / 0.9e1 * t21 * t270 * t274 * t125 + 0.160e3 / 0.9e1 * t21 / t8 / t261 / t202 * t536 * t268);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[0] = -t24 * t2 * t90 / 0.9e1 + t287 * t182 + 0.3e1 / 0.2e1 * t144 * t350 + 0.3e1 / 0.10e2 * t40 * t5 * (-0.2464e4 / 0.243e3 * t15 * t16 * t225 * t30 - 0.176e3 / 0.27e2 * t15 * t291 * t66 + 0.16e2 / 0.9e1 * t15 * t147 * t136 - 0.2e1 / 0.9e1 * t15 * t74 * t279 + 0.2464e4 / 0.243e3 * t49 * t257 * t85 + 0.352e3 / 0.27e2 * t49 * t121 * t158 - 0.64e2 / 0.9e1 * t49 * t58 * t319 - 0.32e2 / 0.9e1 * t49 * t58 * t323 - 0.4e1 * t49 * t50 * t240 * t176 * t110 + 0.4e1 / 0.3e1 * t49 * t50 * t109 * t344 * t65 + t657);

  t688 = t176 * t176;
  t703 = 0.64e2 / 0.27e2 * t15 * t147 * t177 - 0.4e1 / 0.9e1 * t15 * t74 * t345 - 0.8e1 / 0.3e1 * t49 * t609 * t84 * t110 + 0.352e3 / 0.81e2 * t49 * t121 * t189 + 0.64e2 / 0.9e1 * t49 * t58 * t370 - 0.128e3 / 0.27e2 * t49 * t58 * t374 - 0.4e1 / 0.3e1 * t49 * t50 * t369 * t135 + 0.8e1 / 0.9e1 * t49 * t50 * t109 * t688 + 0.8e1 / 0.9e1 * t49 * t50 * t157 * t344 - 0.176e3 / 0.81e2 * t49 * t121 * t209 - 0.64e2 / 0.27e2 * t49 * t58 * t382;
  t769 = 0.8e1 / 0.9e1 * t49 * t50 * t109 * t401 * t65 + 0.4e1 / 0.9e1 * t49 * t50 * t381 * t135 + 0.16e2 / 0.3e1 * t49 * t50 * t489 * t188 * t110 - 0.16e2 / 0.3e1 * t608 * t609 * t359 * t176 - 0.4e1 / 0.3e1 * t49 * t50 * t240 * t208 * t110 - 0.352e3 / 0.81e2 * t15 * t291 * t85 - 0.128e3 / 0.27e2 * t49 * t43 * t109 * t359 + 0.16e2 / 0.9e1 * t49 * t358 * t176 * t65 + 0.8e1 / 0.9e1 * t49 * t358 * t84 * t135 + 0.32e2 / 0.27e2 * t49 * t58 * t402 - 0.2e1 / 0.9e1 * t49 * t50 * t52 * (-0.7e1 / 0.9e1 * t21 * t194 * t116 * t26 + 0.7e1 / 0.9e1 * t21 * t198 * t100 * t61 - 0.11e2 * t21 * t334 + 0.47e2 / 0.3e1 * t21 * t340 * sigma[0] - 0.20e2 / 0.3e1 * t21 / t8 / t523 * t536 * t125);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[0] = t287 * t214 / 0.3e1 + t144 * t407 + 0.3e1 / 0.10e2 * t40 * t5 * (t703 + t769);

  t812 = t84 * t208;
  t858 = -0.32e2 / 0.9e1 * t15 * t147 * t189 - 0.4e1 * t49 * t609 * t188 * t65 + 0.8e1 / 0.3e1 * t49 * t358 * t84 * t176 + 0.16e2 / 0.9e1 * t15 * t147 * t209 + 0.4e1 / 0.3e1 * t49 * t358 * t208 * t65 - 0.2e1 / 0.3e1 * t15 * t74 * t402 + 0.32e2 / 0.9e1 * t49 * t58 * t417 + 0.16e2 / 0.3e1 * t49 * t50 * t489 * t416 * t65 - 0.4e1 * t49 * t50 * t369 * t176 - 0.32e2 / 0.9e1 * t49 * t58 * t421 - 0.4e1 * t608 * t609 * t812 * t65 + 0.4e1 / 0.3e1 * t49 * t50 * t318 * t208 + 0.4e1 / 0.3e1 * t49 * t50 * t157 * t401 + 0.16e2 / 0.27e2 * t49 * t58 * t445 + 0.4e1 / 0.9e1 * t49 * t50 * t109 * t444 * t65 - 0.2e1 / 0.9e1 * t49 * t50 * t52 * (-t21 * t426 * t54 * t26 / 0.2e1 + t21 * t431 * t43 * t61 / 0.2e1 + t21 * t198 * t171 * t131 / 0.6e1 - 0.7e1 / 0.2e1 * t21 * t398 + 0.5e1 / 0.2e1 * t21 / t8 / t269 * t536 * sigma[0]);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[0] = t144 * t450 / 0.2e1 + 0.3e1 / 0.10e2 * t40 * t5 * t858;

  t871 = t188 * t188;
  t880 = t208 * t208;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[0] = 0.3e1 / 0.10e2 * t40 * t5 * (-0.16e2 / 0.3e1 * t15 * t74 * t417 + 0.16e2 / 0.3e1 * t49 * t358 * t812 - 0.8e1 / 0.9e1 * t15 * t74 * t445 + 0.16e2 / 0.3e1 * t49 * t50 * t489 * t871 - 0.8e1 * t49 * t50 * t369 * t208 + 0.4e1 / 0.3e1 * t49 * t50 * t109 * t880 + 0.16e2 / 0.9e1 * t49 * t50 * t157 * t444 - 0.2e1 / 0.9e1 * t49 * t50 * t52 * (-0.15e2 / 0.16e2 * t21 / t22 / t268 * t24 * t26 + 0.15e2 / 0.16e2 * t21 / t268 * t20 * t61 + 0.5e1 / 0.16e2 * t21 * t431 * t204 * t131 + 0.3e1 / 0.16e2 * t21 * t198 * t440 * t274 - 0.15e2 / 0.16e2 * t21 / t8 / t338 * t536));

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, const double *sigma, double *zk, GGA_OUT_PARAMS_NO_EXC(double *))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t4, t5, t6, t7, t8;
  double t9, t10, t12, t13, t14, t15, t16, t17;
  double t18, t19, t20, t21, t23, t24, t25, t26;
  double t27, t28, t29, t30, t32, t33, t34, t36;
  double t37, t38, t41, t42, t47, t49, t51, t52;
  double t53, t54, t55, t56, t57, t58, t59, t61;
  double t62, t64, t65, t66, t69, t70, t75, t77;

#ifndef XC_DONT_COMPILE_VXC
  double t79, t80, t81, t82, t83, t84, t85, t87;
  double t89, t90, t91, t92, t94, t95, t96, t98;
  double t103, t104, t105, t106, t107, t109, t113, t114;
  double t115, t116, t120, t121, t125, t127, t128, t129;
  double t130, t131, t133, t134, t135, t137, t138, t142;
  double t144, t145, t146, t148, t149, t150, t152, t157;
  double t158, t159, t161, t165, t166, t167, t168, t172;
  double t173, t177, t179, t180, t184, t185, t186, t189;
  double t196, t197, t201, t204, t205, t208, t215, t216;
  double t220;

#ifndef XC_DONT_COMPILE_FXC
  double t223, t225, t226, t227, t228, t230, t231, t232;
  double t234, t235, t236, t238, t239, t240, t241, t242;
  double t244, t245, t247, t248, t250, t251, t253, t254;
  double t255, t257, t266, t267, t268, t273, t278, t282;
  double t285, t288, t292, t293, t297, t299, t300, t301;
  double t302, t303, t305, t306, t307, t309, t310, t311;
  double t313, t314, t315, t317, t318, t319, t321, t323;
  double t326, t329, t332, t333, t335, t339, t341, t344;
  double t346, t348, t351, t353, t356, t358, t361, t363;
  double t364, t365, t366, t368, t369, t370, t372, t373;
  double t374, t376, t377, t379, t380, t381, t382, t384;
  double t393, t394, t395, t400, t405, t409, t412, t415;
  double t419, t420, t424, t426, t427, t428, t431, t433;
  double t434, t438, t448, t449, t460, t462, t463, t467;
  double t468, t472, t477, t478, t482, t486, t489, t499;
  double t500, t511, t513, t514, t518, t519, t523, t524;
  double t530, t531, t536, t540, t544, t546, t550, t551;
  double t555, t556, t561, t562, t567, t571, t575, t577;
  double t581, t582, t586, t587;

#ifndef XC_DONT_COMPILE_KXC
  double t593, t595, t599, t600, t602, t605, t606, t608;
  double t609, t611, t612, t613, t614, t615, t617, t619;
  double t620, t621, t623, t624, t626, t627, t629, t630;
  double t631, t633, t634, t637, t638, t639, t641, t642;
  double t644, t646, t648, t649, t651, t652, t654, t655;
  double t656, t658, t659, t661, t663, t665, t666, t668;
  double t669, t671, t672, t674, t677, t691, t692, t693;
  double t694, t698, t699, t704, t709, t713, t715, t720;
  double t721, t722, t724, t726, t730, t731, t735, t737;
  double t738, t739, t746, t747, t749, t751, t753, t755;
  double t757, t759, t761, t763, t765, t768, t769, t770;
  double t772, t774, t776, t779, t780, t781, t783, t785;
  double t787, t790, t794, t796, t797, t799, t802, t805;
  double t807, t809, t811, t813, t815, t818, t820, t822;
  double t823, t825, t826, t828, t837, t840, t845, t847;
  double t849, t851, t853, t855, t857, t859, t862, t864;
  double t866, t868, t870, t873, t877, t879, t882, t884;
  double t886, t889, t892, t895, t898, t901, t904, t906;
  double t908, t910, t911, t913, t921, t924, t932, t933;
  double t934, t937, t939, t940, t942, t944, t945, t947;
  double t948, t950, t952, t953, t955, t969, t970, t971;
  double t972, t976, t977, t982, t987, t991, t993, t998;
  double t999, t1000, t1002, t1004, t1008, t1009, t1013, t1015;
  double t1016, t1020, t1022, t1023, t1024, t1026, t1027, t1029;
  double t1030, t1031, t1033, t1034, t1037, t1039, t1043, t1045;
  double t1046, t1050, t1056, t1079, t1083, t1084, t1088, t1099;
  double t1103, t1105, t1109, t1110, t1114, t1118, t1120, t1124;
  double t1125, t1134, t1135, t1136, t1138, t1141, t1144, t1145;
  double t1146, t1150, t1152, t1155, t1158, t1160, t1161, t1165;
  double t1168, t1172, t1175, t1177, t1180, t1203, t1207, t1208;
  double t1212, t1223, t1227, t1229, t1233, t1234, t1238, t1239;
  double t1242, t1244, t1245, t1251, t1252, t1262, t1263, t1267;
  double t1274, t1275, t1289, t1291, t1294, t1295, t1299, t1300;
  double t1303, t1304, t1305, t1308, t1312, t1318, t1319, t1329;
  double t1330, t1334, t1341, t1342, t1356, t1358, t1361, t1362;
  double t1366, t1367, t1376, t1377, t1381, t1386, t1391, t1400;
  double t1404, t1405, t1409, t1410, t1418, t1419, t1423, t1428;
  double t1433, t1442, t1446, t1447, t1451, t1452;

#ifndef XC_DONT_COMPILE_LXC
  double t1457, t1461, t1463, t1466, t1469, t1493, t1494, t1504;
  double t1527, t1533, t1540, t1549, t1554, t1557, t1559, t1561;
  double t1563, t1567, t1568, t1574, t1576, t1578, t1581, t1584;
  double t1586, t1589, t1590, t1595, t1598, t1600, t1603, t1606;
  double t1607, t1611, t1613, t1616, t1618, t1621, t1623, t1626;
  double t1629, t1631, t1645, t1646, t1659, t1666, t1676, t1685;
  double t1688, t1689, t1701, t1702, t1704, t1705, t1706, t1707;
  double t1710, t1713, t1717, t1720, t1722, t1723, t1726, t1734;
  double t1735, t1741, t1744, t1745, t1750, t1756, t1757, t1759;
  double t1768, t1775, t1782, t1789, t1795, t1803, t1806, t1820;
  double t1824, t1827, t1830, t1831, t1836, t1837, t1850, t1852;
  double t1867, t1874, t1877, t1878, t1885, t1889, t1890, t1893;
  double t1898, t1901, t1904, t1912, t1914, t1916, t1919, t1922;
  double t1924, t1941, t1944, t1947, t1952, t1956, t1959, t1964;
  double t1996, t2002, t2009, t2011, t2018, t2025, t2028, t2043;
  double t2063, t2066, t2093, t2109, t2118, t2129, t2143, t2146;
  double t2155, t2157, t2159, t2162, t2165, t2167, t2175, t2178;
  double t2185, t2196, t2211, t2215, t2221, t2265, t2281, t2286;
  double t2293, t2302, t2308, t2317, t2324, t2328, t2331, t2335;
  double t2368, t2392, t2393, t2403, t2426, t2432, t2439, t2448;
  double t2454, t2472, t2483, t2495, t2592, t2593, t2598, t2604;
  double t2606, t2614, t2617, t2623, t2626, t2630, t2635, t2637;
  double t2642, t2645, t2649, t2652, t2656, t2657, t2671, t2686;
  double t2687, t2697, t2698, t2699, t2702, t2708, t2711, t2712;
  double t2727, t2730, t2731, t2742, t2753, t2768, t2776, t2783;
  double t2791, t2793, t2915, t2916, t2921, t2937, t2938, t2940;
  double t2941, t2945, t3003, t3012, t3055, t3061, t3062, t3064;
  double t3073, t3085, t3093, t3095, t3115, t3159, t3219, t3224;
  double t3226, t3266, t3312, t3316, t3317, t3364, t3410, t3423;
  double t3432, t3482, t3491;
#endif

#endif

#endif

#endif

#endif


  gga_k_llp_params *params;

  assert(p->params != NULL);
  params = (gga_k_llp_params * )(p->params);

  t1 = M_CBRT6;
  t2 = t1 * t1;
  t3 = M_PI * M_PI;
  t4 = POW_1_3(t3);
  t5 = t4 * t4;
  t6 = t2 * t5;
  t7 = rho[0] - rho[1];
  t8 = rho[0] + rho[1];
  t9 = 0.1e1 / t8;
  t10 = t7 * t9;
  t12 = 0.1e1 / 0.2e1 + t10 / 0.2e1;
  t13 = POW_1_3(t12);
  t14 = t13 * t13;
  t15 = t14 * t12;
  t16 = POW_1_3(t8);
  t17 = t16 * t16;
  t18 = t15 * t17;
  t19 = M_CBRT3;
  t20 = t19 * t19;
  t21 = params->beta * t20;
  t23 = POW_1_3(0.1e1 / M_PI);
  t24 = 0.1e1 / t23;
  t25 = t21 * t24;
  t26 = M_CBRT4;
  t27 = t26 * sigma[0];
  t28 = rho[0] * rho[0];
  t29 = POW_1_3(rho[0]);
  t30 = t29 * t29;
  t32 = 0.1e1 / t30 / t28;
  t33 = params->gamma * params->beta;
  t34 = sqrt(sigma[0]);
  t36 = 0.1e1 / t29 / rho[0];
  t37 = t34 * t36;
  t38 = log(t37 + sqrt(t37 * t37 + 0.1e1));
  t41 = 0.10e1 + t33 * t37 * t38;
  t42 = 0.1e1 / t41;
  t47 = 0.10e1 + 0.2e1 / 0.9e1 * t25 * t27 * t32 * t42;
  t49 = t6 * t18 * t47;
  t51 = 0.1e1 / 0.2e1 - t10 / 0.2e1;
  t52 = POW_1_3(t51);
  t53 = t52 * t52;
  t54 = t53 * t51;
  t55 = t54 * t17;
  t56 = t26 * sigma[2];
  t57 = rho[1] * rho[1];
  t58 = POW_1_3(rho[1]);
  t59 = t58 * t58;
  t61 = 0.1e1 / t59 / t57;
  t62 = sqrt(sigma[2]);
  t64 = 0.1e1 / t58 / rho[1];
  t65 = t62 * t64;
  t66 = log(t65 + sqrt(t65 * t65 + 0.1e1));
  t69 = 0.10e1 + t33 * t65 * t66;
  t70 = 0.1e1 / t69;
  t75 = 0.10e1 + 0.2e1 / 0.9e1 * t25 * t56 * t61 * t70;
  t77 = t6 * t55 * t75;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = 0.3e1 / 0.10e2 * t49 + 0.3e1 / 0.10e2 * t77;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t79 = 0.3e1 / 0.10e2 * t49;
  t80 = 0.3e1 / 0.10e2 * t77;
  t81 = t6 * t14;
  t82 = t17 * t47;
  t83 = t8 * t8;
  t84 = 0.1e1 / t83;
  t85 = t7 * t84;
  t87 = t9 / 0.2e1 - t85 / 0.2e1;
  t89 = t81 * t82 * t87;
  t90 = t89 / 0.2e1;
  t91 = 0.1e1 / t16;
  t92 = t15 * t91;
  t94 = t6 * t92 * t47;
  t95 = t94 / 0.5e1;
  t96 = t28 * rho[0];
  t98 = 0.1e1 / t30 / t96;
  t103 = t24 * t26;
  t104 = t21 * t103;
  t105 = sigma[0] * t32;
  t106 = t41 * t41;
  t107 = 0.1e1 / t106;
  t109 = 0.1e1 / t29 / t28;
  t113 = sigma[0] * t98;
  t114 = t105 + 0.1e1;
  t115 = sqrt(t114);
  t116 = 0.1e1 / t115;
  t120 = -0.4e1 / 0.3e1 * t33 * t34 * t109 * t38 - 0.4e1 / 0.3e1 * t33 * t113 * t116;
  t121 = t107 * t120;
  t125 = -0.16e2 / 0.27e2 * t25 * t27 * t98 * t42 - 0.2e1 / 0.9e1 * t104 * t105 * t121;
  t127 = t6 * t18 * t125;
  t128 = 0.3e1 / 0.10e2 * t127;
  t129 = t6 * t53;
  t130 = t17 * t75;
  t131 = -t87;
  t133 = t129 * t130 * t131;
  t134 = t133 / 0.2e1;
  t135 = t54 * t91;
  t137 = t6 * t135 * t75;
  t138 = t137 / 0.5e1;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t79 + t80 + t8 * (t90 + t95 + t128 + t134 + t138);

  t142 = -t9 / 0.2e1 - t85 / 0.2e1;
  t144 = t81 * t82 * t142;
  t145 = t144 / 0.2e1;
  t146 = -t142;
  t148 = t129 * t130 * t146;
  t149 = t148 / 0.2e1;
  t150 = t57 * rho[1];
  t152 = 0.1e1 / t59 / t150;
  t157 = sigma[2] * t61;
  t158 = t69 * t69;
  t159 = 0.1e1 / t158;
  t161 = 0.1e1 / t58 / t57;
  t165 = sigma[2] * t152;
  t166 = t157 + 0.1e1;
  t167 = sqrt(t166);
  t168 = 0.1e1 / t167;
  t172 = -0.4e1 / 0.3e1 * t33 * t62 * t161 * t66 - 0.4e1 / 0.3e1 * t33 * t165 * t168;
  t173 = t159 * t172;
  t177 = -0.16e2 / 0.27e2 * t25 * t56 * t152 * t70 - 0.2e1 / 0.9e1 * t104 * t157 * t173;
  t179 = t6 * t55 * t177;
  t180 = 0.3e1 / 0.10e2 * t179;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = t79 + t80 + t8 * (t145 + t95 + t149 + t138 + t180);

  t184 = t17 * t8 * t2;
  t185 = t5 * t15;
  t186 = t26 * t32;
  t189 = 0.1e1 / t34;
  t196 = t33 * t189 * t36 * t38 / 0.2e1 + t33 * t32 * t116 / 0.2e1;
  t197 = t107 * t196;
  t201 = -0.2e1 / 0.9e1 * t104 * t105 * t197 + 0.2e1 / 0.9e1 * t25 * t186 * t42;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.3e1 / 0.10e2 * t184 * t185 * t201;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[1] = 0.0e0;

  t204 = t5 * t54;
  t205 = t26 * t61;
  t208 = 0.1e1 / t62;
  t215 = t33 * t208 * t64 * t66 / 0.2e1 + t33 * t61 * t168 / 0.2e1;
  t216 = t159 * t215;
  t220 = -0.2e1 / 0.9e1 * t104 * t157 * t216 + 0.2e1 / 0.9e1 * t25 * t205 * t70;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[2] = 0.3e1 / 0.10e2 * t184 * t204 * t220;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t223 = 0.2e1 / 0.5e1 * t94;
  t225 = 0.2e1 / 0.5e1 * t137;
  t226 = 0.1e1 / t13;
  t227 = t6 * t226;
  t228 = t87 * t87;
  t230 = t227 * t82 * t228;
  t231 = t230 / 0.3e1;
  t232 = t91 * t47;
  t234 = t81 * t232 * t87;
  t235 = 0.2e1 / 0.3e1 * t234;
  t236 = t17 * t125;
  t238 = t81 * t236 * t87;
  t239 = t83 * t8;
  t240 = 0.1e1 / t239;
  t241 = t7 * t240;
  t242 = -t84 + t241;
  t244 = t81 * t82 * t242;
  t245 = t244 / 0.2e1;
  t247 = 0.1e1 / t16 / t8;
  t248 = t15 * t247;
  t250 = t6 * t248 * t47;
  t251 = t250 / 0.15e2;
  t253 = t6 * t92 * t125;
  t254 = 0.2e1 / 0.5e1 * t253;
  t255 = t28 * t28;
  t257 = 0.1e1 / t30 / t255;
  t266 = 0.1e1 / t106 / t41;
  t267 = t120 * t120;
  t268 = t266 * t267;
  t273 = 0.1e1 / t29 / t96;
  t278 = sigma[0] * t257;
  t282 = sigma[0] * sigma[0];
  t285 = 0.1e1 / t29 / t255 / t96;
  t288 = 0.1e1 / t115 / t114;
  t292 = 0.28e2 / 0.9e1 * t33 * t34 * t273 * t38 + 0.20e2 / 0.3e1 * t33 * t278 * t116 - 0.16e2 / 0.9e1 * t33 * t282 * t285 * t288;
  t293 = t107 * t292;
  t297 = 0.176e3 / 0.81e2 * t25 * t27 * t257 * t42 + 0.32e2 / 0.27e2 * t104 * t113 * t121 + 0.4e1 / 0.9e1 * t104 * t105 * t268 - 0.2e1 / 0.9e1 * t104 * t105 * t293;
  t299 = t6 * t18 * t297;
  t300 = 0.3e1 / 0.10e2 * t299;
  t301 = 0.1e1 / t52;
  t302 = t6 * t301;
  t303 = t131 * t131;
  t305 = t302 * t130 * t303;
  t306 = t305 / 0.3e1;
  t307 = t91 * t75;
  t309 = t129 * t307 * t131;
  t310 = 0.2e1 / 0.3e1 * t309;
  t311 = -t242;
  t313 = t129 * t130 * t311;
  t314 = t313 / 0.2e1;
  t315 = t54 * t247;
  t317 = t6 * t315 * t75;
  t318 = t317 / 0.15e2;
  t319 = t231 + t235 + t238 + t245 - t251 + t254 + t300 + t306 + t310 + t314 - t318;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = t89 + t223 + 0.3e1 / 0.5e1 * t127 + t133 + t225 + t8 * t319;

  t321 = t142 * t87;
  t323 = t227 * t82 * t321;
  t326 = t81 * t232 * t142;
  t329 = t81 * t236 * t142;
  t332 = 0.1e1 / t16 / t83;
  t333 = t332 * t47;
  t335 = t81 * t333 * t7;
  t339 = t146 * t131;
  t341 = t302 * t130 * t339;
  t344 = t129 * t307 * t146;
  t346 = t332 * t75;
  t348 = t129 * t346 * t7;
  t351 = t17 * t177;
  t353 = t129 * t351 * t131;
  t356 = t6 * t135 * t177;
  t358 = t323 / 0.3e1 + t326 / 0.3e1 + t329 / 0.2e1 + t335 / 0.2e1 + t234 / 0.3e1 - t251 + t253 / 0.5e1 + t341 / 0.3e1 + t344 / 0.3e1 - t348 / 0.2e1 + t309 / 0.3e1 - t318 + t353 / 0.2e1 + t356 / 0.5e1;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = t8 * t358 + t128 + t134 + t145 + t149 + t180 + t223 + t225 + t90;

  t361 = t142 * t142;
  t363 = t227 * t82 * t361;
  t364 = t363 / 0.3e1;
  t365 = 0.2e1 / 0.3e1 * t326;
  t366 = t84 + t241;
  t368 = t81 * t82 * t366;
  t369 = t368 / 0.2e1;
  t370 = t146 * t146;
  t372 = t302 * t130 * t370;
  t373 = t372 / 0.3e1;
  t374 = 0.2e1 / 0.3e1 * t344;
  t376 = t129 * t351 * t146;
  t377 = -t366;
  t379 = t129 * t130 * t377;
  t380 = t379 / 0.2e1;
  t381 = 0.2e1 / 0.5e1 * t356;
  t382 = t57 * t57;
  t384 = 0.1e1 / t59 / t382;
  t393 = 0.1e1 / t158 / t69;
  t394 = t172 * t172;
  t395 = t393 * t394;
  t400 = 0.1e1 / t58 / t150;
  t405 = sigma[2] * t384;
  t409 = sigma[2] * sigma[2];
  t412 = 0.1e1 / t58 / t382 / t150;
  t415 = 0.1e1 / t167 / t166;
  t419 = 0.28e2 / 0.9e1 * t33 * t62 * t400 * t66 + 0.20e2 / 0.3e1 * t33 * t405 * t168 - 0.16e2 / 0.9e1 * t33 * t409 * t412 * t415;
  t420 = t159 * t419;
  t424 = 0.176e3 / 0.81e2 * t25 * t56 * t384 * t70 + 0.32e2 / 0.27e2 * t104 * t165 * t173 + 0.4e1 / 0.9e1 * t104 * t157 * t395 - 0.2e1 / 0.9e1 * t104 * t157 * t420;
  t426 = t6 * t55 * t424;
  t427 = 0.3e1 / 0.10e2 * t426;
  t428 = t364 + t365 + t369 - t251 + t373 + t374 + t376 + t380 - t318 + t381 + t427;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = t144 + t223 + t148 + t225 + 0.3e1 / 0.5e1 * t179 + t8 * t428;

  t431 = t6 * t18 * t201;
  t433 = t184 * t5;
  t434 = t14 * t201;
  t438 = t26 * t98;
  t448 = t266 * t196;
  t449 = t448 * t120;
  t460 = t255 * t28;
  t462 = 0.1e1 / t29 / t460;
  t463 = t462 * t288;
  t467 = -0.2e1 / 0.3e1 * t33 * t189 * t109 * t38 - 0.2e1 * t33 * t98 * t116 + 0.2e1 / 0.3e1 * t33 * t463 * sigma[0];
  t468 = t107 * t467;
  t472 = -0.16e2 / 0.27e2 * t25 * t438 * t42 - 0.2e1 / 0.9e1 * t25 * t186 * t121 + 0.16e2 / 0.27e2 * t104 * t113 * t197 + 0.4e1 / 0.9e1 * t104 * t105 * t449 - 0.2e1 / 0.9e1 * t104 * t105 * t468;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t431 / 0.2e1 + t433 * t434 * t87 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t185 * t472;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[1] = 0.0e0;

  t477 = t6 * t55 * t220;
  t478 = t53 * t220;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[2] = t433 * t478 * t131 / 0.2e1 + t477 / 0.2e1;

  t482 = t434 * t142;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[3] = t433 * t482 / 0.2e1 + t431 / 0.2e1;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[4] = 0.0e0;

  t486 = t478 * t146;
  t489 = t26 * t152;
  t499 = t393 * t215;
  t500 = t499 * t172;
  t511 = t382 * t57;
  t513 = 0.1e1 / t58 / t511;
  t514 = t513 * t415;
  t518 = -0.2e1 / 0.3e1 * t33 * t208 * t161 * t66 - 0.2e1 * t33 * t152 * t168 + 0.2e1 / 0.3e1 * t33 * t514 * sigma[2];
  t519 = t159 * t518;
  t523 = -0.16e2 / 0.27e2 * t25 * t489 * t70 - 0.2e1 / 0.9e1 * t25 * t205 * t173 + 0.16e2 / 0.27e2 * t104 * t165 * t216 + 0.4e1 / 0.9e1 * t104 * t157 * t500 - 0.2e1 / 0.9e1 * t104 * t157 * t519;
  t524 = t204 * t523;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[5] = t477 / 0.2e1 + t433 * t486 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t524;

  t530 = t196 * t196;
  t531 = t266 * t530;
  t536 = 0.1e1 / t34 / sigma[0];
  t540 = 0.1e1 / sigma[0];
  t544 = t255 * rho[0];
  t546 = 0.1e1 / t29 / t544;
  t550 = t33 * t540 * t32 * t116 / 0.4e1 - t33 * t536 * t36 * t38 / 0.4e1 - t33 * t546 * t288 / 0.4e1;
  t551 = t107 * t550;
  t555 = -0.4e1 / 0.9e1 * t25 * t186 * t197 + 0.4e1 / 0.9e1 * t104 * t105 * t531 - 0.2e1 / 0.9e1 * t104 * t105 * t551;
  t556 = t185 * t555;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.3e1 / 0.10e2 * t184 * t556;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[4] = 0.0e0;

  t561 = t215 * t215;
  t562 = t393 * t561;
  t567 = 0.1e1 / t62 / sigma[2];
  t571 = 0.1e1 / sigma[2];
  t575 = t382 * rho[1];
  t577 = 0.1e1 / t58 / t575;
  t581 = t33 * t571 * t61 * t168 / 0.4e1 - t33 * t567 * t64 * t66 / 0.4e1 - t33 * t577 * t415 / 0.4e1;
  t582 = t159 * t581;
  t586 = -0.4e1 / 0.9e1 * t25 * t205 * t216 + 0.4e1 / 0.9e1 * t104 * t157 * t562 - 0.2e1 / 0.9e1 * t104 * t157 * t582;
  t587 = t204 * t586;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[5] = 0.3e1 / 0.10e2 * t184 * t587;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t593 = t250 / 0.5e1;
  t595 = t317 / 0.5e1;
  t599 = t227 * t236 * t228;
  t600 = t91 * t125;
  t602 = t81 * t600 * t87;
  t605 = t81 * t232 * t242;
  t606 = t17 * t297;
  t608 = t81 * t606 * t87;
  t609 = 0.3e1 / 0.2e1 * t608;
  t611 = t81 * t236 * t242;
  t612 = 0.3e1 / 0.2e1 * t611;
  t613 = t83 * t83;
  t614 = 0.1e1 / t613;
  t615 = t7 * t614;
  t617 = 0.3e1 * t240 - 0.3e1 * t615;
  t619 = t81 * t82 * t617;
  t620 = t619 / 0.2e1;
  t621 = t15 * t332;
  t623 = t6 * t621 * t47;
  t624 = 0.4e1 / 0.45e2 * t623;
  t626 = t129 * t307 * t311;
  t627 = -t617;
  t629 = t129 * t130 * t627;
  t630 = t629 / 0.2e1;
  t631 = t54 * t332;
  t633 = t6 * t631 * t75;
  t634 = 0.4e1 / 0.45e2 * t633;
  t637 = 0.1e1 / t13 / t12;
  t638 = t6 * t637;
  t639 = t228 * t87;
  t641 = t638 * t82 * t639;
  t642 = t641 / 0.9e1;
  t644 = t227 * t232 * t228;
  t646 = t87 * t242;
  t648 = t227 * t82 * t646;
  t649 = t247 * t47;
  t651 = t81 * t649 * t87;
  t652 = t651 / 0.3e1;
  t654 = 0.1e1 / t52 / t51;
  t655 = t6 * t654;
  t656 = t303 * t131;
  t658 = t655 * t130 * t656;
  t659 = t658 / 0.9e1;
  t661 = t302 * t307 * t303;
  t663 = t131 * t311;
  t665 = t302 * t130 * t663;
  t666 = t247 * t75;
  t668 = t129 * t666 * t131;
  t669 = t668 / 0.3e1;
  t671 = t6 * t248 * t125;
  t672 = t671 / 0.5e1;
  t674 = t6 * t92 * t297;
  t677 = 0.1e1 / t30 / t544;
  t691 = t106 * t106;
  t692 = 0.1e1 / t691;
  t693 = t267 * t120;
  t694 = t692 * t693;
  t698 = t266 * t120;
  t699 = t698 * t292;
  t704 = 0.1e1 / t29 / t255;
  t709 = sigma[0] * t677;
  t713 = t255 * t255;
  t715 = 0.1e1 / t29 / t713;
  t720 = t282 * sigma[0];
  t721 = t713 * t96;
  t722 = 0.1e1 / t721;
  t724 = t114 * t114;
  t726 = 0.1e1 / t115 / t724;
  t730 = -0.280e3 / 0.27e2 * t33 * t34 * t704 * t38 - 0.952e3 / 0.27e2 * t33 * t709 * t116 + 0.592e3 / 0.27e2 * t33 * t282 * t715 * t288 - 0.64e2 / 0.9e1 * t33 * t720 * t722 * t726;
  t731 = t107 * t730;
  t735 = -0.2464e4 / 0.243e3 * t25 * t27 * t677 * t42 - 0.176e3 / 0.27e2 * t104 * t278 * t121 - 0.32e2 / 0.9e1 * t104 * t113 * t268 + 0.16e2 / 0.9e1 * t104 * t113 * t293 - 0.4e1 / 0.3e1 * t104 * t105 * t694 + 0.4e1 / 0.3e1 * t104 * t105 * t699 - 0.2e1 / 0.9e1 * t104 * t105 * t731;
  t737 = t6 * t18 * t735;
  t738 = 0.3e1 / 0.10e2 * t737;
  t739 = -t642 + 0.2e1 / 0.3e1 * t644 + t648 - t652 - t659 + 0.2e1 / 0.3e1 * t661 + t665 - t669 - t672 + 0.3e1 / 0.5e1 * t674 + t738;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = 0.6e1 / 0.5e1 * t253 + 0.9e1 / 0.10e2 * t299 + 0.3e1 * t238 + 0.3e1 / 0.2e1 * t244 - t593 + 0.3e1 / 0.2e1 * t313 - t595 + t230 + 0.2e1 * t234 + t305 + 0.2e1 * t309 + t8 * (t599 + 0.2e1 * t602 + t605 + t609 + t612 + t620 + t624 + t626 + t630 + t634 + t739);

  t746 = 0.2e1 / 0.3e1 * t323;
  t747 = 0.2e1 / 0.3e1 * t341;
  t749 = t227 * t236 * t321;
  t751 = t142 * t242;
  t753 = t227 * t82 * t751;
  t755 = t146 * t311;
  t757 = t302 * t130 * t755;
  t759 = t7 * t131;
  t761 = t302 * t346 * t759;
  t763 = t142 * t228;
  t765 = t638 * t82 * t763;
  t768 = t227 * t232 * t321;
  t769 = 0.4e1 / 0.9e1 * t768;
  t770 = t7 * t87;
  t772 = t227 * t333 * t770;
  t774 = t146 * t303;
  t776 = t655 * t130 * t774;
  t779 = t302 * t307 * t339;
  t780 = 0.4e1 / 0.9e1 * t779;
  t781 = t14 * t332;
  t783 = t6 * t781 * t47;
  t785 = t53 * t332;
  t787 = t6 * t785 * t75;
  t790 = t6 * t315 * t177;
  t794 = 0.2e1 / 0.3e1 * t749 + t753 / 0.3e1 + t757 / 0.3e1 - 0.2e1 / 0.3e1 * t761 - t765 / 0.9e1 + t769 + 0.2e1 / 0.3e1 * t772 - t776 / 0.9e1 + t780 + t783 / 0.2e1 - t787 / 0.2e1 - t790 / 0.15e2 - 0.2e1 / 0.15e2 * t671 + t674 / 0.5e1 + t624 + t634;
  t796 = 0.1e1 / t16 / t239;
  t797 = t796 * t75;
  t799 = t129 * t797 * t7;
  t802 = t129 * t351 * t311;
  t805 = t81 * t649 * t142;
  t807 = t796 * t47;
  t809 = t81 * t807 * t7;
  t811 = t332 * t125;
  t813 = t81 * t811 * t7;
  t815 = t129 * t666 * t146;
  t818 = t302 * t351 * t303;
  t820 = t91 * t177;
  t822 = t129 * t820 * t131;
  t823 = 0.2e1 / 0.3e1 * t822;
  t825 = t81 * t600 * t142;
  t826 = 0.2e1 / 0.3e1 * t825;
  t828 = t81 * t606 * t142;
  t837 = 0.5e1 / 0.6e1 * t799 + t802 / 0.2e1 - t805 / 0.9e1 - 0.5e1 / 0.6e1 * t809 + t813 - t815 / 0.9e1 + t818 / 0.3e1 + t823 + t826 + t828 / 0.2e1 + 0.2e1 / 0.9e1 * t644 - 0.2e1 / 0.9e1 * t651 + 0.2e1 / 0.9e1 * t661 - 0.2e1 / 0.9e1 * t668 + 0.2e1 / 0.3e1 * t602 + t605 / 0.3e1 + t626 / 0.3e1;
  t840 = t381 + t231 + 0.4e1 / 0.3e1 * t234 + t306 + 0.4e1 / 0.3e1 * t309 + t746 + t365 + t335 + t747 + t374 + t8 * (t794 + t837);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[1] = 0.4e1 / 0.5e1 * t253 + t300 + t238 + t245 - t593 + t314 - t595 + t329 - t348 + t353 + t840;

  t845 = t361 * t87;
  t847 = t638 * t82 * t845;
  t849 = t366 * t87;
  t851 = t227 * t82 * t849;
  t853 = t370 * t131;
  t855 = t655 * t130 * t853;
  t857 = t146 * t7;
  t859 = t302 * t346 * t857;
  t862 = t302 * t351 * t339;
  t864 = t377 * t131;
  t866 = t302 * t130 * t864;
  t868 = t142 * t7;
  t870 = t227 * t333 * t868;
  t873 = t6 * t135 * t424;
  t877 = t17 * t424;
  t879 = t129 * t877 * t131;
  t882 = t227 * t232 * t361;
  t884 = -t847 / 0.9e1 + t851 / 0.3e1 - t855 / 0.9e1 - 0.2e1 / 0.3e1 * t859 + 0.2e1 / 0.3e1 * t862 + t866 / 0.3e1 + 0.2e1 / 0.3e1 * t870 + t769 + t780 + t873 / 0.5e1 - 0.2e1 / 0.15e2 * t790 - t671 / 0.15e2 + t624 + t634 + t879 / 0.2e1 + 0.2e1 / 0.9e1 * t882;
  t886 = t81 * t232 * t366;
  t889 = t302 * t307 * t370;
  t892 = t129 * t820 * t146;
  t895 = t129 * t307 * t377;
  t898 = t227 * t236 * t361;
  t901 = t81 * t236 * t366;
  t904 = -t240 - 0.3e1 * t615;
  t906 = t81 * t82 * t904;
  t908 = t332 * t177;
  t910 = t129 * t908 * t7;
  t911 = -t904;
  t913 = t129 * t130 * t911;
  t921 = t886 / 0.3e1 + 0.2e1 / 0.9e1 * t889 + 0.2e1 / 0.3e1 * t892 + t895 / 0.3e1 + t898 / 0.3e1 + t901 / 0.2e1 + t906 / 0.2e1 - t910 + t913 / 0.2e1 - 0.2e1 / 0.3e1 * t799 - 0.2e1 / 0.9e1 * t805 + 0.2e1 / 0.3e1 * t809 - 0.2e1 / 0.9e1 * t815 + t823 + t826 - t651 / 0.9e1 - t668 / 0.9e1;
  t924 = t380 + t235 + t310 + t746 + 0.4e1 / 0.3e1 * t326 + t335 + t747 + 0.4e1 / 0.3e1 * t344 + t364 + t373 + t8 * (t884 + t921);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[2] = t254 + t427 - t593 - t595 + t329 - t348 + t353 + 0.4e1 / 0.5e1 * t356 + t369 + t376 + t924;

  t932 = t805 / 0.3e1;
  t933 = t815 / 0.3e1;
  t934 = t790 / 0.5e1;
  t937 = -0.3e1 * t240 - 0.3e1 * t615;
  t939 = t81 * t82 * t937;
  t940 = t939 / 0.2e1;
  t942 = t302 * t351 * t370;
  t944 = t129 * t877 * t146;
  t945 = 0.3e1 / 0.2e1 * t944;
  t947 = t129 * t351 * t377;
  t948 = 0.3e1 / 0.2e1 * t947;
  t950 = -t937;
  t952 = t129 * t130 * t950;
  t953 = t952 / 0.2e1;
  t955 = 0.1e1 / t59 / t575;
  t969 = t158 * t158;
  t970 = 0.1e1 / t969;
  t971 = t394 * t172;
  t972 = t970 * t971;
  t976 = t393 * t172;
  t977 = t976 * t419;
  t982 = 0.1e1 / t58 / t382;
  t987 = sigma[2] * t955;
  t991 = t382 * t382;
  t993 = 0.1e1 / t58 / t991;
  t998 = t409 * sigma[2];
  t999 = t991 * t150;
  t1000 = 0.1e1 / t999;
  t1002 = t166 * t166;
  t1004 = 0.1e1 / t167 / t1002;
  t1008 = -0.280e3 / 0.27e2 * t33 * t62 * t982 * t66 - 0.952e3 / 0.27e2 * t33 * t987 * t168 + 0.592e3 / 0.27e2 * t33 * t409 * t993 * t415 - 0.64e2 / 0.9e1 * t33 * t998 * t1000 * t1004;
  t1009 = t159 * t1008;
  t1013 = -0.2464e4 / 0.243e3 * t25 * t56 * t955 * t70 - 0.176e3 / 0.27e2 * t104 * t405 * t173 - 0.32e2 / 0.9e1 * t104 * t165 * t395 + 0.16e2 / 0.9e1 * t104 * t165 * t420 - 0.4e1 / 0.3e1 * t104 * t157 * t972 + 0.4e1 / 0.3e1 * t104 * t157 * t977 - 0.2e1 / 0.9e1 * t104 * t157 * t1009;
  t1015 = t6 * t55 * t1013;
  t1016 = 0.3e1 / 0.10e2 * t1015;
  t1020 = t361 * t142;
  t1022 = t638 * t82 * t1020;
  t1023 = t1022 / 0.9e1;
  t1024 = t142 * t366;
  t1026 = t227 * t82 * t1024;
  t1027 = t370 * t146;
  t1029 = t655 * t130 * t1027;
  t1030 = t1029 / 0.9e1;
  t1031 = t146 * t377;
  t1033 = t302 * t130 * t1031;
  t1034 = t953 + t1016 + 0.2e1 / 0.3e1 * t882 + t886 + 0.2e1 / 0.3e1 * t889 + 0.2e1 * t892 + t895 - t1023 + t1026 - t1030 + t1033;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[3] = 0.9e1 / 0.10e2 * t426 - t593 - t595 + 0.6e1 / 0.5e1 * t356 + 0.3e1 / 0.2e1 * t368 + 0.3e1 * t376 + 0.3e1 / 0.2e1 * t379 + 0.2e1 * t326 + 0.2e1 * t344 + t363 + t372 + t8 * (t624 + t634 - t932 - t933 - t934 + 0.3e1 / 0.5e1 * t873 + t940 + t942 + t945 + t948 + t1034);

  t1037 = t17 * t201;
  t1039 = t81 * t1037 * t87;
  t1043 = t6 * t92 * t201 / 0.3e1;
  t1045 = t6 * t18 * t472;
  t1046 = t226 * t201;
  t1050 = t14 * t472;
  t1056 = t26 * t257;
  t1079 = t692 * t196 * t267;
  t1083 = t266 * t467;
  t1084 = t1083 * t120;
  t1088 = t448 * t292;
  t1099 = t285 * t288;
  t1103 = t713 * t28;
  t1105 = 0.1e1 / t1103 * t726;
  t1109 = 0.14e2 / 0.9e1 * t33 * t189 * t273 * t38 + 0.74e2 / 0.9e1 * t33 * t257 * t116 - 0.62e2 / 0.9e1 * t33 * t1099 * sigma[0] + 0.8e1 / 0.3e1 * t33 * t1105 * t282;
  t1110 = t107 * t1109;
  t1114 = 0.176e3 / 0.81e2 * t25 * t1056 * t42 + 0.32e2 / 0.27e2 * t25 * t438 * t121 + 0.4e1 / 0.9e1 * t25 * t186 * t268 - 0.2e1 / 0.9e1 * t25 * t186 * t293 - 0.176e3 / 0.81e2 * t104 * t278 * t197 - 0.64e2 / 0.27e2 * t104 * t113 * t449 + 0.32e2 / 0.27e2 * t104 * t113 * t468 - 0.4e1 / 0.3e1 * t104 * t105 * t1079 + 0.8e1 / 0.9e1 * t104 * t105 * t1084 + 0.4e1 / 0.9e1 * t104 * t105 * t1088 - 0.2e1 / 0.9e1 * t104 * t105 * t1110;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[0] = 0.5e1 / 0.3e1 * t1039 + t1043 + t1045 + t433 * t1046 * t228 / 0.3e1 + t433 * t1050 * t87 + t433 * t434 * t242 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t185 * t1114;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[1] = 0.0e0;

  t1118 = t17 * t220;
  t1120 = t129 * t1118 * t131;
  t1124 = t6 * t135 * t220 / 0.3e1;
  t1125 = t301 * t220;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[2] = 0.5e1 / 0.3e1 * t1120 + t1124 + t433 * t1125 * t303 / 0.3e1 + t433 * t478 * t311 / 0.2e1;

  t1134 = t17 * t2;
  t1135 = t1134 * t5;
  t1136 = t1135 * t482;
  t1138 = t1046 * t321;
  t1141 = t1050 * t142;
  t1144 = t247 * t2;
  t1145 = t1144 * t5;
  t1146 = t434 * t7;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[3] = 0.5e1 / 0.6e1 * t1039 + t1043 + t1045 / 0.2e1 + 0.5e1 / 0.6e1 * t1136 + t433 * t1138 / 0.3e1 + t433 * t1141 / 0.2e1 + t1145 * t1146 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[4] = 0.0e0;

  t1150 = t1135 * t486;
  t1152 = t1125 * t339;
  t1155 = t478 * t7;
  t1158 = t1134 * t524;
  t1160 = t53 * t523;
  t1161 = t1160 * t131;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[5] = 0.5e1 / 0.6e1 * t1120 + t1124 + 0.5e1 / 0.6e1 * t1150 + t433 * t1152 / 0.3e1 - t1145 * t1155 / 0.2e1 + t1158 / 0.2e1 + t433 * t1161 / 0.2e1;

  t1165 = t1046 * t361;
  t1168 = t434 * t366;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[6] = 0.5e1 / 0.3e1 * t1136 + t1043 + t433 * t1165 / 0.3e1 + t433 * t1168 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[7] = 0.0e0;

  t1172 = t1125 * t370;
  t1175 = t1160 * t146;
  t1177 = t478 * t377;
  t1180 = t26 * t384;
  t1203 = t970 * t215 * t394;
  t1207 = t393 * t518;
  t1208 = t1207 * t172;
  t1212 = t499 * t419;
  t1223 = t412 * t415;
  t1227 = t991 * t57;
  t1229 = 0.1e1 / t1227 * t1004;
  t1233 = 0.14e2 / 0.9e1 * t33 * t208 * t400 * t66 + 0.74e2 / 0.9e1 * t33 * t384 * t168 - 0.62e2 / 0.9e1 * t33 * t1223 * sigma[2] + 0.8e1 / 0.3e1 * t33 * t1229 * t409;
  t1234 = t159 * t1233;
  t1238 = 0.176e3 / 0.81e2 * t25 * t1180 * t70 + 0.32e2 / 0.27e2 * t25 * t489 * t173 + 0.4e1 / 0.9e1 * t25 * t205 * t395 - 0.2e1 / 0.9e1 * t25 * t205 * t420 - 0.176e3 / 0.81e2 * t104 * t405 * t216 - 0.64e2 / 0.27e2 * t104 * t165 * t500 + 0.32e2 / 0.27e2 * t104 * t165 * t519 - 0.4e1 / 0.3e1 * t104 * t157 * t1203 + 0.8e1 / 0.9e1 * t104 * t157 * t1208 + 0.4e1 / 0.9e1 * t104 * t157 * t1212 - 0.2e1 / 0.9e1 * t104 * t157 * t1234;
  t1239 = t204 * t1238;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho2sigma[8] = 0.5e1 / 0.3e1 * t1150 + t1124 + t1158 + t433 * t1172 / 0.3e1 + t433 * t1175 + t433 * t1177 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t1239;

  t1242 = t1134 * t556;
  t1244 = t14 * t555;
  t1245 = t1244 * t87;
  t1251 = t32 * t266;
  t1252 = t196 * t120;
  t1262 = t692 * t530;
  t1263 = t1262 * t120;
  t1267 = t448 * t467;
  t1274 = t266 * t550;
  t1275 = t1274 * t120;
  t1289 = t713 * rho[0];
  t1291 = 0.1e1 / t1289 * t726;
  t1294 = t33 * t536 * t109 * t38 / 0.3e1 - t33 * t540 * t98 * t116 / 0.3e1 + 0.5e1 / 0.3e1 * t33 * t463 - t33 * t1291 * sigma[0];
  t1295 = t107 * t1294;
  t1299 = 0.32e2 / 0.27e2 * t25 * t438 * t197 + 0.8e1 / 0.9e1 * t104 * t1251 * t1252 - 0.4e1 / 0.9e1 * t25 * t186 * t468 - 0.32e2 / 0.27e2 * t104 * t113 * t531 - 0.4e1 / 0.3e1 * t104 * t105 * t1263 + 0.8e1 / 0.9e1 * t104 * t105 * t1267 + 0.16e2 / 0.27e2 * t104 * t113 * t551 + 0.4e1 / 0.9e1 * t104 * t105 * t1275 - 0.2e1 / 0.9e1 * t104 * t105 * t1295;
  t1300 = t185 * t1299;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[0] = t1242 / 0.2e1 + t433 * t1245 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t1300;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[4] = 0.0e0;

  t1303 = t1134 * t587;
  t1304 = t53 * t586;
  t1305 = t1304 * t131;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[5] = t433 * t1305 / 0.2e1 + t1303 / 0.2e1;

  t1308 = t1244 * t142;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[6] = t433 * t1308 / 0.2e1 + t1242 / 0.2e1;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[8] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[9] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[10] = 0.0e0;

  t1312 = t1304 * t146;
  t1318 = t61 * t393;
  t1319 = t215 * t172;
  t1329 = t970 * t561;
  t1330 = t1329 * t172;
  t1334 = t499 * t518;
  t1341 = t393 * t581;
  t1342 = t1341 * t172;
  t1356 = t991 * rho[1];
  t1358 = 0.1e1 / t1356 * t1004;
  t1361 = t33 * t567 * t161 * t66 / 0.3e1 - t33 * t571 * t152 * t168 / 0.3e1 + 0.5e1 / 0.3e1 * t33 * t514 - t33 * t1358 * sigma[2];
  t1362 = t159 * t1361;
  t1366 = 0.32e2 / 0.27e2 * t25 * t489 * t216 + 0.8e1 / 0.9e1 * t104 * t1318 * t1319 - 0.4e1 / 0.9e1 * t25 * t205 * t519 - 0.32e2 / 0.27e2 * t104 * t165 * t562 - 0.4e1 / 0.3e1 * t104 * t157 * t1330 + 0.8e1 / 0.9e1 * t104 * t157 * t1334 + 0.16e2 / 0.27e2 * t104 * t165 * t582 + 0.4e1 / 0.9e1 * t104 * t157 * t1342 - 0.2e1 / 0.9e1 * t104 * t157 * t1362;
  t1367 = t204 * t1366;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rhosigma2[11] = t1303 / 0.2e1 + t433 * t1312 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t1367;

  t1376 = t530 * t196;
  t1377 = t692 * t1376;
  t1381 = t448 * t550;
  t1386 = 0.1e1 / t34 / t282;
  t1391 = 0.1e1 / t282;
  t1400 = 0.1e1 / t713;
  t1404 = 0.3e1 / 0.8e1 * t33 * t1386 * t36 * t38 - 0.3e1 / 0.8e1 * t33 * t1391 * t32 * t116 - t33 * t540 * t546 * t288 / 0.8e1 + 0.3e1 / 0.8e1 * t33 * t1400 * t726;
  t1405 = t107 * t1404;
  t1409 = 0.4e1 / 0.3e1 * t25 * t186 * t531 - 0.2e1 / 0.3e1 * t25 * t186 * t551 - 0.4e1 / 0.3e1 * t104 * t105 * t1377 + 0.4e1 / 0.3e1 * t104 * t105 * t1381 - 0.2e1 / 0.9e1 * t104 * t105 * t1405;
  t1410 = t185 * t1409;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[0] = 0.3e1 / 0.10e2 * t184 * t1410;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[1] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[2] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[3] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[4] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[5] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[6] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[7] = 0.0e0;

  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[8] = 0.0e0;

  t1418 = t561 * t215;
  t1419 = t970 * t1418;
  t1423 = t499 * t581;
  t1428 = 0.1e1 / t62 / t409;
  t1433 = 0.1e1 / t409;
  t1442 = 0.1e1 / t991;
  t1446 = 0.3e1 / 0.8e1 * t33 * t1428 * t64 * t66 - 0.3e1 / 0.8e1 * t33 * t1433 * t61 * t168 - t33 * t571 * t577 * t415 / 0.8e1 + 0.3e1 / 0.8e1 * t33 * t1442 * t1004;
  t1447 = t159 * t1446;
  t1451 = 0.4e1 / 0.3e1 * t25 * t205 * t562 - 0.2e1 / 0.3e1 * t25 * t205 * t582 - 0.4e1 / 0.3e1 * t104 * t157 * t1419 + 0.4e1 / 0.3e1 * t104 * t157 * t1423 - 0.2e1 / 0.9e1 * t104 * t157 * t1447;
  t1452 = t204 * t1451;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3sigma3[9] = 0.3e1 / 0.10e2 * t184 * t1452;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t1457 = 0.28e2 / 0.135e3 * t6 * t15 * t796 * t47;
  t1461 = 0.28e2 / 0.135e3 * t6 * t54 * t796 * t75;
  t1463 = t6 * t248 * t297;
  t1466 = t6 * t621 * t125;
  t1469 = 0.1e1 / t30 / t460;
  t1493 = 0.1e1 / t691 / t41;
  t1494 = t267 * t267;
  t1504 = t292 * t292;
  t1527 = t713 * t255;
  t1533 = t282 * t282;
  t1540 = 0.1e1 / t115 / t724 / t114;
  t1549 = 0.41888e5 / 0.729e3 * t25 * t27 * t1469 * t42 + 0.9856e4 / 0.243e3 * t104 * t709 * t121 + 0.704e3 / 0.27e2 * t104 * t278 * t268 - 0.352e3 / 0.27e2 * t104 * t278 * t293 + 0.128e3 / 0.9e1 * t104 * t113 * t694 - 0.128e3 / 0.9e1 * t104 * t113 * t699 + 0.64e2 / 0.27e2 * t104 * t113 * t731 + 0.16e2 / 0.3e1 * t104 * t105 * t1493 * t1494 - 0.8e1 * t104 * t105 * t692 * t267 * t292 + 0.4e1 / 0.3e1 * t104 * t105 * t266 * t1504 + 0.16e2 / 0.9e1 * t104 * t105 * t698 * t730 - 0.2e1 / 0.9e1 * t104 * t105 * t107 * (0.3640e4 / 0.81e2 * t33 * t34 * t546 * t38 + 0.5768e4 / 0.27e2 * t33 * sigma[0] * t1469 * t116 - 0.18608e5 / 0.81e2 * t33 * t282 / t29 / t1289 * t288 + 0.4480e4 / 0.27e2 * t33 * t720 / t1527 * t726 - 0.1280e4 / 0.27e2 * t33 * t1533 / t30 / t713 / t460 * t1540);
  t1554 = t6 * t92 * t735;
  t1557 = t129 * t307 * t627;
  t1559 = t613 * t8;
  t1561 = t7 / t1559;
  t1563 = 0.12e2 * t614 - 0.12e2 * t1561;
  t1567 = t346 * t131;
  t1568 = t129 * t1567;
  t1574 = t227 * t600 * t228;
  t1576 = t247 * t125;
  t1578 = t81 * t1576 * t87;
  t1581 = t81 * t649 * t242;
  t1584 = t129 * t666 * t311;
  t1586 = t12 * t12;
  t1589 = t6 / t13 / t1586;
  t1590 = t228 * t228;
  t1595 = t638 * t232 * t639;
  t1598 = t227 * t649 * t228;
  t1600 = t242 * t242;
  t1603 = t51 * t51;
  t1606 = t6 / t52 / t1603;
  t1607 = t303 * t303;
  t1611 = -t1457 - t1461 - 0.2e1 / 0.5e1 * t1463 + 0.16e2 / 0.45e2 * t1466 + 0.3e1 / 0.10e2 * t6 * t18 * t1549 + 0.4e1 / 0.5e1 * t1554 + 0.4e1 / 0.3e1 * t1557 + t129 * t130 * t1563 / 0.2e1 + 0.16e2 / 0.27e2 * t1568 - 0.4e1 / 0.9e1 * t638 * t236 * t639 + 0.8e1 / 0.3e1 * t1574 - 0.4e1 / 0.3e1 * t1578 - 0.2e1 / 0.3e1 * t1581 - 0.2e1 / 0.3e1 * t1584 + 0.4e1 / 0.27e2 * t1589 * t82 * t1590 - 0.8e1 / 0.27e2 * t1595 - 0.4e1 / 0.9e1 * t1598 + t227 * t82 * t1600 + 0.4e1 / 0.27e2 * t1606 * t130 * t1607;
  t1613 = t655 * t307 * t656;
  t1616 = t302 * t666 * t303;
  t1618 = t311 * t311;
  t1621 = t91 * t297;
  t1623 = t81 * t1621 * t87;
  t1626 = t81 * t600 * t242;
  t1629 = t81 * t232 * t617;
  t1631 = t17 * t735;
  t1645 = t333 * t87;
  t1646 = t81 * t1645;
  t1659 = t227 * t232 * t646;
  t1666 = t302 * t307 * t663;
  t1676 = -0.8e1 / 0.27e2 * t1613 - 0.4e1 / 0.9e1 * t1616 + t302 * t130 * t1618 + 0.4e1 * t1623 + 0.4e1 * t1626 + 0.4e1 / 0.3e1 * t1629 + 0.2e1 * t81 * t1631 * t87 + 0.3e1 * t81 * t606 * t242 + 0.2e1 * t81 * t236 * t617 - t81 * t82 * t1563 / 0.2e1 + 0.16e2 / 0.27e2 * t1646 + 0.2e1 * t227 * t606 * t228 - 0.2e1 / 0.3e1 * t655 * t130 * t303 * t311 + 0.4e1 * t227 * t236 * t646 + 0.8e1 / 0.3e1 * t1659 + 0.4e1 / 0.3e1 * t227 * t82 * t617 * t87 + 0.8e1 / 0.3e1 * t1666 + 0.4e1 / 0.3e1 * t302 * t130 * t627 * t131 - 0.2e1 / 0.3e1 * t638 * t82 * t228 * t242;
  t1685 = 0.16e2 / 0.45e2 * t623;
  t1688 = 0.16e2 / 0.45e2 * t633;
  t1689 = t8 * (t1611 + t1676) + 0.4e1 * t599 + 0.8e1 * t602 + 0.4e1 * t605 + 0.6e1 * t608 + 0.6e1 * t611 + 0.2e1 * t619 + t1685 + 0.4e1 * t626 + 0.2e1 * t629 + t1688;
  t1701 = -0.4e1 / 0.9e1 * t641 + 0.8e1 / 0.3e1 * t644 + 0.4e1 * t648 - 0.4e1 / 0.3e1 * t651 - 0.4e1 / 0.9e1 * t658 + 0.8e1 / 0.3e1 * t661 + 0.4e1 * t665 - 0.4e1 / 0.3e1 * t668 - 0.4e1 / 0.5e1 * t671 + 0.12e2 / 0.5e1 * t674 + 0.6e1 / 0.5e1 * t737;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = t1689 + t1701;

  t1702 = t247 * t177;
  t1704 = t129 * t1702 * t131;
  t1705 = t1704 / 0.3e1;
  t1706 = t333 * t142;
  t1707 = t81 * t1706;
  t1710 = 0.1e1 / t16 / t613;
  t1713 = t81 * t1710 * t47 * t7;
  t1717 = t129 * t1710 * t75 * t7;
  t1720 = t129 * t820 * t311;
  t1722 = t81 * t1576 * t142;
  t1723 = t1722 / 0.3e1;
  t1726 = t81 * t796 * t125 * t7;
  t1734 = t346 * t146;
  t1735 = t129 * t1734;
  t1741 = t302 * t820 * t303;
  t1744 = t302 * t666 * t339;
  t1745 = 0.2e1 / 0.9e1 * t1744;
  t1750 = -t1705 + 0.4e1 / 0.27e2 * t1707 + 0.8e1 / 0.3e1 * t1713 - 0.8e1 / 0.3e1 * t1717 + t1720 - t1723 - 0.5e1 / 0.2e1 * t1726 + 0.3e1 / 0.2e1 * t81 * t332 * t297 * t7 + t227 * t1645 - t302 * t1567 + 0.4e1 / 0.27e2 * t1735 - t655 * t351 * t656 / 0.9e1 + 0.2e1 / 0.3e1 * t1741 - t1745 + t302 * t351 * t663 + t227 * t236 * t751;
  t1756 = t227 * t649 * t321;
  t1757 = 0.2e1 / 0.9e1 * t1756;
  t1759 = t227 * t807 * t770;
  t1768 = t655 * t307 * t774;
  t1775 = t638 * t232 * t763;
  t1782 = t302 * t307 * t755;
  t1789 = t302 * t797 * t759;
  t1795 = t227 * t232 * t751;
  t1803 = t227 * t82 * t142 * t617 / 0.3e1 - t1757 - 0.5e1 / 0.3e1 * t1759 + t227 * t606 * t321 + 0.4e1 / 0.27e2 * t1606 * t130 * t146 * t656 - 0.2e1 / 0.9e1 * t1768 + 0.4e1 / 0.27e2 * t1589 * t82 * t142 * t639 - 0.2e1 / 0.9e1 * t1775 - t638 * t333 * t7 * t228 / 0.3e1 + 0.2e1 / 0.3e1 * t1782 + t655 * t346 * t7 * t303 / 0.3e1 + 0.5e1 / 0.3e1 * t1789 + 0.2e1 * t227 * t811 * t770 + 0.2e1 / 0.3e1 * t1795 + t227 * t333 * t7 * t242 - t638 * t236 * t763 / 0.3e1;
  t1806 = t227 * t600 * t321;
  t1820 = t6 * t14 * t796 * t47;
  t1824 = t6 * t53 * t796 * t75;
  t1827 = t6 * t631 * t177;
  t1830 = t6 * t654 * t17;
  t1831 = t75 * t146;
  t1836 = t6 * t637 * t17;
  t1837 = t47 * t142;
  t1850 = 0.4e1 / 0.3e1 * t1806 + t302 * t130 * t146 * t627 / 0.3e1 - t302 * t346 * t7 * t311 + 0.3e1 / 0.2e1 * t6 * t781 * t125 - 0.2e1 * t1820 + 0.2e1 * t1824 + 0.4e1 / 0.45e2 * t1827 - t1830 * t1831 * t663 / 0.3e1 - t1836 * t1837 * t646 / 0.3e1 - t1457 - t1461 - t1463 / 0.5e1 + 0.4e1 / 0.15e2 * t1466 + t1554 / 0.5e1 + t129 * t351 * t627 / 0.2e1 + t81 * t1631 * t142 / 0.2e1;
  t1852 = t81 * t1621 * t142;
  t1867 = t1852 + t1557 / 0.3e1 + 0.4e1 / 0.9e1 * t1568 + 0.2e1 / 0.3e1 * t1574 - 0.2e1 / 0.3e1 * t1578 - t1581 / 0.3e1 - t1584 / 0.3e1 - 0.2e1 / 0.27e2 * t1595 - 0.2e1 / 0.9e1 * t1598 - 0.2e1 / 0.27e2 * t1613 - 0.2e1 / 0.9e1 * t1616 + t1623 + t1626 + t1629 / 0.3e1 + 0.4e1 / 0.9e1 * t1646 + 0.2e1 / 0.3e1 * t1659 + 0.2e1 / 0.3e1 * t1666;
  t1874 = 0.4e1 / 0.3e1 * t768;
  t1877 = 0.4e1 / 0.3e1 * t779;
  t1878 = t8 * (t1750 + t1803 + t1850 + t1867) + 0.2e1 * t749 + t753 + t757 - 0.2e1 * t761 - t765 / 0.3e1 + t1874 + 0.2e1 * t772 - t776 / 0.3e1 + t1877 + t648;
  t1885 = t665 + 0.3e1 / 0.2e1 * t783 - 0.3e1 / 0.2e1 * t787 - t934 - 0.3e1 / 0.5e1 * t671 + 0.6e1 / 0.5e1 * t674 + t738 + t1685 + t1688 + 0.5e1 / 0.2e1 * t799 + 0.3e1 / 0.2e1 * t802;
  t1889 = 0.2e1 * t822;
  t1890 = 0.2e1 * t825;
  t1893 = -t932 - 0.5e1 / 0.2e1 * t809 + 0.3e1 * t813 - t933 + t818 + t1889 + t1890 + 0.3e1 / 0.2e1 * t828 + 0.4e1 / 0.3e1 * t644 - t651 - t659;
  t1898 = 0.4e1 / 0.3e1 * t661 - t668 + t599 + 0.4e1 * t602 + 0.2e1 * t605 + t609 + t612 + t620 + 0.2e1 * t626 + t630 - t642;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[1] = t1878 + t1885 + t1893 + t1898;

  t1901 = t81 * t600 * t366;
  t1904 = t81 * t232 * t904;
  t1912 = t227 * t600 * t361;
  t1914 = t91 * t424;
  t1916 = t129 * t1914 * t131;
  t1919 = t227 * t649 * t361;
  t1922 = 0.1e1 / t16 / t1559;
  t1924 = t7 * t7;
  t1941 = t129 * t666 * t377;
  t1944 = t81 * t649 * t366;
  t1947 = t302 * t666 * t370;
  t1952 = t129 * t1702 * t146;
  t1956 = t129 * t796 * t177 * t7;
  t1959 = t129 * t307 * t911;
  t1964 = 0.2e1 / 0.3e1 * t1901 + 0.2e1 / 0.3e1 * t1904 + 0.2e1 / 0.3e1 * t227 * t1706 + t227 * t606 * t361 / 0.3e1 + 0.4e1 / 0.9e1 * t1912 + 0.2e1 / 0.3e1 * t1916 - 0.2e1 / 0.27e2 * t1919 + 0.2e1 / 0.3e1 * t227 * t1922 * t47 * t1924 + t129 * t877 * t311 / 0.2e1 + 0.2e1 / 0.3e1 * t302 * t1922 * t75 * t1924 + t81 * t606 * t366 / 0.2e1 + t81 * t236 * t904 - t1941 / 0.9e1 - t1944 / 0.9e1 - 0.2e1 / 0.27e2 * t1947 - 0.2e1 / 0.3e1 * t302 * t1734 - 0.2e1 / 0.9e1 * t1952 + 0.5e1 / 0.3e1 * t1956 + 0.2e1 / 0.3e1 * t1959 + t302 * t877 * t303 / 0.3e1;
  t1996 = t655 * t307 * t853;
  t2002 = t302 * t820 * t339;
  t2009 = t302 * t307 * t864;
  t2011 = -0.4e1 / 0.9e1 * t1704 + 0.8e1 / 0.27e2 * t1707 + 0.32e2 / 0.9e1 * t1713 - 0.32e2 / 0.9e1 * t1717 + 0.2e1 / 0.3e1 * t1720 - 0.4e1 / 0.9e1 * t1722 + 0.4e1 / 0.3e1 * t1726 + 0.8e1 / 0.27e2 * t1735 + 0.4e1 / 0.9e1 * t1741 - 0.2e1 / 0.9e1 * t638 * t236 * t845 + 0.2e1 / 0.3e1 * t227 * t236 * t849 + 0.2e1 / 0.3e1 * t227 * t82 * t904 * t87 + 0.4e1 / 0.3e1 * t227 * t811 * t868 - t638 * t82 * t361 * t242 / 0.9e1 + 0.4e1 / 0.27e2 * t1606 * t130 * t370 * t303 - 0.4e1 / 0.27e2 * t1996 - 0.2e1 / 0.9e1 * t655 * t351 * t774 + 0.8e1 / 0.9e1 * t2002 - t655 * t130 * t377 * t303 / 0.9e1 + 0.4e1 / 0.9e1 * t2009;
  t2018 = t227 * t232 * t849;
  t2025 = t638 * t232 * t845;
  t2028 = t227 * t807 * t868;
  t2043 = t302 * t797 * t857;
  t2063 = -t638 * t82 * t366 * t228 / 0.9e1 + 0.4e1 / 0.9e1 * t2018 + 0.4e1 / 0.27e2 * t1589 * t82 * t361 * t228 - 0.4e1 / 0.27e2 * t2025 - 0.10e2 / 0.9e1 * t2028 + t302 * t130 * t377 * t311 / 0.3e1 + t227 * t82 * t366 * t242 / 0.3e1 - t655 * t130 * t370 * t311 / 0.9e1 + 0.10e2 / 0.9e1 * t2043 + 0.2e1 / 0.3e1 * t302 * t351 * t755 - 0.4e1 / 0.3e1 * t302 * t908 * t759 + 0.2e1 / 0.3e1 * t302 * t130 * t911 * t131 - 0.8e1 / 0.27e2 * t1744 - 0.8e1 / 0.27e2 * t1756 + 0.8e1 / 0.9e1 * t1759 - 0.4e1 / 0.27e2 * t1768 - 0.4e1 / 0.27e2 * t1775 + 0.4e1 / 0.9e1 * t1782 - 0.8e1 / 0.9e1 * t1789 + 0.4e1 / 0.9e1 * t1795;
  t2066 = t6 * t315 * t424;
  t2093 = 0.8e1 / 0.9e1 * t1806 - t2066 / 0.15e2 - t6 * t785 * t177 + 0.2e1 / 0.3e1 * t1820 - 0.2e1 / 0.3e1 * t1824 + 0.8e1 / 0.45e2 * t1827 + 0.4e1 / 0.9e1 * t6 * t654 * t332 * t1831 * t759 - 0.4e1 / 0.9e1 * t6 * t637 * t332 * t1837 * t770 - t1457 - t1461 - t1463 / 0.15e2 + 0.8e1 / 0.45e2 * t1466 + 0.2e1 / 0.3e1 * t1852 + 0.8e1 / 0.27e2 * t1568 - 0.2e1 / 0.9e1 * t1578 - t1581 / 0.9e1 - t1584 / 0.9e1 - 0.2e1 / 0.27e2 * t1598 - 0.2e1 / 0.27e2 * t1616 + 0.8e1 / 0.27e2 * t1646;
  t2109 = t8 * (t1964 + t2011 + t2063 + t2093) - 0.2e1 / 0.9e1 * t847 + 0.2e1 / 0.3e1 * t851 - 0.2e1 / 0.9e1 * t855 - 0.4e1 / 0.3e1 * t859 + 0.4e1 / 0.3e1 * t862 + 0.2e1 / 0.3e1 * t866 + 0.4e1 / 0.3e1 * t870 + 0.4e1 / 0.3e1 * t749 + 0.2e1 / 0.3e1 * t753 + 0.2e1 / 0.3e1 * t757 - 0.4e1 / 0.3e1 * t761 - 0.2e1 / 0.9e1 * t765;
  t2118 = 0.16e2 / 0.9e1 * t768 + 0.4e1 / 0.3e1 * t772 - 0.2e1 / 0.9e1 * t776 + 0.16e2 / 0.9e1 * t779 + 0.2e1 / 0.5e1 * t873 + t783 - t787 - 0.2e1 / 0.5e1 * t790 - 0.2e1 / 0.5e1 * t671 + 0.2e1 / 0.5e1 * t674 + t1685 + t1688 + t879;
  t2129 = 0.4e1 / 0.9e1 * t882 + 0.2e1 / 0.3e1 * t886 + 0.4e1 / 0.9e1 * t889 + 0.4e1 / 0.3e1 * t892 + 0.2e1 / 0.3e1 * t895 + 0.2e1 / 0.3e1 * t898 + t901 + t906 - 0.2e1 * t910 + t913 + t799 / 0.3e1 + t802 - 0.2e1 / 0.3e1 * t805;
  t2143 = -t809 / 0.3e1 + 0.2e1 * t813 - 0.2e1 / 0.3e1 * t815 + 0.2e1 / 0.3e1 * t818 + 0.8e1 / 0.3e1 * t822 + 0.8e1 / 0.3e1 * t825 + t828 + 0.4e1 / 0.9e1 * t644 - 0.2e1 / 0.3e1 * t651 + 0.4e1 / 0.9e1 * t661 - 0.2e1 / 0.3e1 * t668 + 0.4e1 / 0.3e1 * t602 + 0.2e1 / 0.3e1 * t605 + 0.2e1 / 0.3e1 * t626;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[2] = t2109 + t2118 + t2129 + t2143;

  t2146 = t6 * t135 * t1013;
  t2155 = t129 * t1914 * t146;
  t2157 = t129 * t820 * t377;
  t2159 = t129 * t307 * t950;
  t2162 = t81 * t232 * t937;
  t2165 = t302 * t820 * t370;
  t2167 = t17 * t1013;
  t2175 = t638 * t232 * t1020;
  t2178 = t655 * t307 * t1027;
  t2185 = 0.6e1 * t614 + 0.12e2 * t1561;
  t2196 = t2146 / 0.5e1 - t1830 * t1831 * t864 / 0.3e1 - t1836 * t1837 * t849 / 0.3e1 + t2155 + t2157 + t2159 / 0.3e1 + t2162 / 0.3e1 + 0.2e1 / 0.3e1 * t2165 + t129 * t2167 * t131 / 0.2e1 + t81 * t236 * t937 / 0.2e1 - 0.2e1 / 0.27e2 * t2175 - 0.2e1 / 0.27e2 * t2178 - t638 * t236 * t1020 / 0.9e1 + t81 * t82 * t2185 / 0.2e1 - 0.3e1 / 0.2e1 * t129 * t332 * t424 * t7 + 0.3e1 / 0.2e1 * t129 * t351 * t911;
  t2211 = -t129 * t130 * t2185 / 0.2e1 + t1901 + t1904 + 0.2e1 / 0.3e1 * t1912 + t1916 - 0.2e1 / 0.9e1 * t1919 - t1941 / 0.3e1 - t1944 / 0.3e1 - 0.2e1 / 0.9e1 * t1947 - 0.2e1 / 0.3e1 * t1952 - 0.2e1 * t1956 + t1959 - t1705 + 0.4e1 / 0.9e1 * t1707 - t1713 / 0.3e1 + t1717 / 0.3e1 - t1723;
  t2215 = t227 * t232 * t1024;
  t2221 = t302 * t307 * t1031;
  t2265 = 0.4e1 / 0.9e1 * t1735 + 0.2e1 / 0.3e1 * t2215 + t227 * t333 * t7 * t366 + 0.2e1 / 0.3e1 * t2221 - t638 * t333 * t361 * t7 / 0.3e1 + 0.4e1 / 0.27e2 * t1606 * t130 * t1027 * t131 + t655 * t346 * t370 * t7 / 0.3e1 - 0.2e1 * t302 * t908 * t857 + t302 * t877 * t339 + t302 * t351 * t864 + t302 * t130 * t950 * t131 / 0.3e1 + t227 * t82 * t937 * t87 / 0.3e1 - t655 * t351 * t853 / 0.3e1 + t302 * t130 * t146 * t911 - t302 * t346 * t7 * t377 + 0.4e1 / 0.27e2 * t1589 * t82 * t1020 * t87 + t227 * t236 * t1024;
  t2281 = t227 * t82 * t142 * t904 - 0.2e1 / 0.9e1 * t1996 + 0.4e1 / 0.3e1 * t2002 + 0.2e1 / 0.3e1 * t2009 + 0.2e1 / 0.3e1 * t2018 - 0.2e1 / 0.9e1 * t2025 + 0.4e1 / 0.3e1 * t2028 - 0.4e1 / 0.3e1 * t2043 - t1745 - t1757 - t2066 / 0.5e1 + 0.4e1 / 0.15e2 * t1827 - t1457 - t1461 + 0.4e1 / 0.45e2 * t1466 + 0.4e1 / 0.27e2 * t1568 + 0.4e1 / 0.27e2 * t1646;
  t2286 = t8 * (t2196 + t2211 + t2265 + t2281) - t1023 - t1030 + t940 + t942 + t945 + t948 + t953 + t1026 + t1033 - t847 / 0.3e1;
  t2293 = t851 - t855 / 0.3e1 - 0.2e1 * t859 + 0.2e1 * t862 + t866 + 0.2e1 * t870 + t1874 + t1877 + t1016 + 0.6e1 / 0.5e1 * t873 - 0.3e1 / 0.5e1 * t790;
  t2302 = -t672 + t1685 + t1688 + 0.3e1 / 0.2e1 * t879 + 0.4e1 / 0.3e1 * t882 + 0.2e1 * t886 + 0.4e1 / 0.3e1 * t889 + 0.4e1 * t892 + 0.2e1 * t895 + t898 + 0.3e1 / 0.2e1 * t901;
  t2308 = 0.3e1 / 0.2e1 * t906 - 0.3e1 * t910 + 0.3e1 / 0.2e1 * t913 - 0.2e1 * t799 - t805 + 0.2e1 * t809 - t815 + t1889 + t1890 - t652 - t669;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[3] = t2286 + t2293 + t2302 + t2308;

  t2317 = 0.12e2 * t614 + 0.12e2 * t1561;
  t2324 = t370 * t370;
  t2328 = t377 * t377;
  t2331 = t361 * t361;
  t2335 = t366 * t366;
  t2368 = 0.1e1 / t59 / t511;
  t2392 = 0.1e1 / t969 / t69;
  t2393 = t394 * t394;
  t2403 = t419 * t419;
  t2426 = t991 * t382;
  t2432 = t409 * t409;
  t2439 = 0.1e1 / t167 / t1002 / t166;
  t2448 = 0.41888e5 / 0.729e3 * t25 * t56 * t2368 * t70 + 0.9856e4 / 0.243e3 * t104 * t987 * t173 + 0.704e3 / 0.27e2 * t104 * t405 * t395 - 0.352e3 / 0.27e2 * t104 * t405 * t420 + 0.128e3 / 0.9e1 * t104 * t165 * t972 - 0.128e3 / 0.9e1 * t104 * t165 * t977 + 0.64e2 / 0.27e2 * t104 * t165 * t1009 + 0.16e2 / 0.3e1 * t104 * t157 * t2392 * t2393 - 0.8e1 * t104 * t157 * t970 * t394 * t419 + 0.4e1 / 0.3e1 * t104 * t157 * t393 * t2403 + 0.16e2 / 0.9e1 * t104 * t157 * t976 * t1008 - 0.2e1 / 0.9e1 * t104 * t157 * t159 * (0.3640e4 / 0.81e2 * t33 * t62 * t577 * t66 + 0.5768e4 / 0.27e2 * t33 * sigma[2] * t2368 * t168 - 0.18608e5 / 0.81e2 * t33 * t409 / t58 / t1356 * t415 + 0.4480e4 / 0.27e2 * t33 * t998 / t2426 * t1004 - 0.1280e4 / 0.27e2 * t33 * t2432 / t59 / t991 / t511 * t2439);
  t2454 = 0.2e1 * t129 * t2167 * t146 + 0.3e1 * t129 * t877 * t377 + t81 * t82 * t2317 / 0.2e1 + 0.2e1 * t302 * t877 * t370 + 0.4e1 / 0.27e2 * t1606 * t130 * t2324 + t302 * t130 * t2328 + 0.4e1 / 0.27e2 * t1589 * t82 * t2331 + t227 * t82 * t2335 - 0.4e1 / 0.9e1 * t655 * t351 * t1027 + 0.2e1 * t129 * t351 * t950 - t129 * t130 * t2317 / 0.2e1 - 0.2e1 / 0.3e1 * t655 * t130 * t370 * t377 - 0.2e1 / 0.3e1 * t638 * t82 * t361 * t366 + 0.4e1 / 0.3e1 * t302 * t130 * t950 * t146 + 0.4e1 / 0.3e1 * t227 * t82 * t937 * t142 + 0.4e1 * t302 * t351 * t1031 + 0.3e1 / 0.10e2 * t6 * t55 * t2448 + 0.4e1 / 0.5e1 * t2146 + 0.4e1 * t2155;
  t2472 = 0.4e1 * t2157 + 0.4e1 / 0.3e1 * t2159 + 0.4e1 / 0.3e1 * t2162 + 0.8e1 / 0.3e1 * t2165 - 0.8e1 / 0.27e2 * t2175 - 0.8e1 / 0.27e2 * t2178 - 0.4e1 / 0.9e1 * t1919 - 0.2e1 / 0.3e1 * t1941 - 0.2e1 / 0.3e1 * t1944 - 0.4e1 / 0.9e1 * t1947 - 0.4e1 / 0.3e1 * t1952 + 0.16e2 / 0.27e2 * t1707 + 0.16e2 / 0.27e2 * t1735 + 0.8e1 / 0.3e1 * t2215 + 0.8e1 / 0.3e1 * t2221 - 0.2e1 / 0.5e1 * t2066 + 0.16e2 / 0.45e2 * t1827 - t1457 - t1461;
  t2483 = t8 * (t2454 + t2472) + t1685 + t1688 - 0.4e1 / 0.3e1 * t805 - 0.4e1 / 0.3e1 * t815 - 0.4e1 / 0.5e1 * t790 + 0.12e2 / 0.5e1 * t873 + 0.2e1 * t939 + 0.4e1 * t942 + 0.6e1 * t944 + 0.6e1 * t947;
  t2495 = 0.2e1 * t952 + 0.6e1 / 0.5e1 * t1015 + 0.8e1 / 0.3e1 * t882 + 0.4e1 * t886 + 0.8e1 / 0.3e1 * t889 + 0.8e1 * t892 + 0.4e1 * t895 - 0.4e1 / 0.9e1 * t1022 + 0.4e1 * t1026 - 0.4e1 / 0.9e1 * t1029 + 0.4e1 * t1033;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[4] = t2483 + t2495;

  t2592 = t21 * t103 * sigma[0];
  t2593 = t32 * t692;
  t2598 = -0.64e2 / 0.9e1 * t104 * t113 * t1084 - 0.32e2 / 0.9e1 * t104 * t113 * t1088 - 0.4e1 * t104 * t105 * t692 * t467 * t267 + 0.4e1 / 0.3e1 * t104 * t105 * t266 * t1109 * t120 + 0.4e1 / 0.3e1 * t104 * t105 * t1083 * t292 + 0.4e1 / 0.9e1 * t104 * t105 * t448 * t730 + 0.2464e4 / 0.243e3 * t104 * t709 * t197 + 0.352e3 / 0.27e2 * t104 * t278 * t449 + 0.32e2 / 0.3e1 * t104 * t113 * t1079 + 0.16e2 / 0.3e1 * t104 * t105 * t1493 * t196 * t693 - 0.4e1 * t2592 * t2593 * t1252 * t292;
  t2604 = t6 * t92 * t472;
  t2606 = t6 * t18 * t1114;
  t2614 = t226 * t472;
  t2617 = t14 * t1114;
  t2623 = t81 * t17 * t472 * t87;
  t2626 = t81 * t1037 * t242;
  t2630 = t6 * t248 * t201 / 0.9e1;
  t2635 = t81 * t91 * t201 * t87;
  t2637 = t637 * t201;
  t2642 = t227 * t1037 * t228;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[0] = 0.3e1 / 0.10e2 * t184 * t185 * (-0.2e1 / 0.9e1 * t104 * t105 * t107 * (-0.140e3 / 0.27e2 * t33 * t189 * t704 * t38 - 0.364e3 / 0.9e1 * t33 * t677 * t116 + 0.1660e4 / 0.27e2 * t33 * t715 * t288 * sigma[0] - 0.488e3 / 0.9e1 * t33 * t722 * t726 * t282 + 0.160e3 / 0.9e1 * t33 / t30 / t713 / t544 * t1540 * t720) - 0.176e3 / 0.27e2 * t104 * t278 * t468 + 0.16e2 / 0.9e1 * t104 * t113 * t1110 - 0.32e2 / 0.9e1 * t25 * t438 * t268 - 0.4e1 / 0.3e1 * t25 * t186 * t694 + 0.4e1 / 0.3e1 * t104 * t1251 * t120 * t292 - 0.2464e4 / 0.243e3 * t25 * t26 * t677 * t42 - 0.176e3 / 0.27e2 * t25 * t1056 * t121 + 0.16e2 / 0.9e1 * t25 * t438 * t293 - 0.2e1 / 0.9e1 * t25 * t186 * t731 + t2598) + t2604 + 0.3e1 / 0.2e1 * t2606 + 0.3e1 / 0.2e1 * t433 * t1050 * t242 + t433 * t434 * t617 / 0.2e1 + t433 * t2614 * t228 + 0.3e1 / 0.2e1 * t433 * t2617 * t87 + 0.5e1 * t2623 + 0.5e1 / 0.2e1 * t2626 - t2630 + t433 * t1046 * t646 + 0.5e1 / 0.3e1 * t2635 - t433 * t2637 * t639 / 0.9e1 + 0.5e1 / 0.3e1 * t2642;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[1] = 0.0e0;

  t2645 = t302 * t1118 * t303;
  t2649 = t129 * t91 * t220 * t131;
  t2652 = t129 * t1118 * t311;
  t2656 = t6 * t315 * t220 / 0.9e1;
  t2657 = t654 * t220;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[2] = 0.5e1 / 0.3e1 * t2645 + 0.5e1 / 0.3e1 * t2649 + 0.5e1 / 0.2e1 * t2652 - t2656 - t433 * t2657 * t656 / 0.9e1 + t433 * t1125 * t663 + t433 * t478 * t627 / 0.2e1;

  t2671 = 0.5e1 / 0.3e1 * t1135 * t1141;
  t2686 = t332 * t2 * t5;
  t2687 = t2686 * t1146;
  t2697 = t91 * t2;
  t2698 = t2697 * t5;
  t2699 = t2698 * t482;
  t2702 = 0.10e2 / 0.9e1 * t1135 * t1138;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[3] = t1144 * t5 * t14 * t201 / 0.2e1 + t2671 + t433 * t2617 * t142 / 0.2e1 - t433 * t2637 * t763 / 0.9e1 + 0.2e1 / 0.3e1 * t1145 * t1046 * t770 + 0.2e1 / 0.3e1 * t2604 + t2606 / 0.2e1 + 0.5e1 / 0.3e1 * t2623 + 0.5e1 / 0.6e1 * t2626 - t2630 + t2687 / 0.6e1 + 0.2e1 / 0.3e1 * t433 * t2614 * t321 + t433 * t1046 * t751 / 0.3e1 + t1145 * t1050 * t7 + 0.5e1 / 0.9e1 * t2699 + t2702 + 0.10e2 / 0.9e1 * t2635 + 0.5e1 / 0.9e1 * t2642;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[4] = 0.0e0;

  t2708 = t2698 * t486;
  t2711 = 0.10e2 / 0.9e1 * t1135 * t1152;
  t2712 = t2686 * t1155;
  t2727 = t2697 * t524;
  t2730 = 0.5e1 / 0.3e1 * t1135 * t1161;
  t2731 = t301 * t523;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[5] = 0.5e1 / 0.9e1 * t2645 + 0.10e2 / 0.9e1 * t2649 + 0.5e1 / 0.6e1 * t2652 - t2656 + 0.5e1 / 0.9e1 * t2708 + t2711 - t2712 / 0.6e1 - t433 * t2657 * t774 / 0.9e1 - 0.2e1 / 0.3e1 * t1145 * t1125 * t759 + t433 * t1125 * t755 / 0.3e1 - t1144 * t5 * t53 * t220 / 0.2e1 + t2727 / 0.3e1 + t2730 + t433 * t2731 * t303 / 0.3e1 + t433 * t1160 * t311 / 0.2e1;

  t2742 = t1135 * t1165;
  t2753 = t1135 * t1168;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[6] = 0.10e2 / 0.9e1 * t2699 + t2702 + t2671 + 0.5e1 / 0.3e1 * t2687 + 0.5e1 / 0.9e1 * t2635 - t2630 + t2604 / 0.3e1 + 0.5e1 / 0.9e1 * t2742 - t433 * t2637 * t845 / 0.9e1 + t433 * t2614 * t361 / 0.3e1 + 0.2e1 / 0.3e1 * t1145 * t1046 * t868 + 0.5e1 / 0.6e1 * t2753 + t433 * t1046 * t849 / 0.3e1 + t433 * t1050 * t366 / 0.2e1 + t433 * t434 * t904 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[7] = 0.0e0;

  t2768 = t1135 * t1172;
  t2776 = t1135 * t1175;
  t2783 = t1135 * t1177;
  t2791 = t1134 * t1239;
  t2793 = t53 * t1238;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[8] = 0.10e2 / 0.9e1 * t2708 + t2711 - 0.5e1 / 0.3e1 * t2712 + 0.5e1 / 0.9e1 * t2649 - t2656 + 0.2e1 / 0.3e1 * t2727 + t2730 + 0.5e1 / 0.9e1 * t2768 - t433 * t2657 * t853 / 0.9e1 - 0.2e1 / 0.3e1 * t1145 * t1125 * t857 + 0.5e1 / 0.3e1 * t2776 + 0.2e1 / 0.3e1 * t433 * t2731 * t339 - t1145 * t1160 * t7 + 0.5e1 / 0.6e1 * t2783 + t433 * t1125 * t864 / 0.3e1 + t433 * t478 * t911 / 0.2e1 + t2791 / 0.2e1 + t433 * t2793 * t131 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[9] = 0.5e1 / 0.3e1 * t2699 + 0.5e1 / 0.3e1 * t2742 + 0.5e1 / 0.2e1 * t2753 - t2630 - t433 * t2637 * t1020 / 0.9e1 + t433 * t1046 * t1024 + t433 * t434 * t937 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[10] = 0.0e0;

  t2915 = t21 * t103 * sigma[2];
  t2916 = t61 * t970;
  t2921 = 0.4e1 / 0.9e1 * t104 * t157 * t499 * t1008 + 0.2464e4 / 0.243e3 * t104 * t987 * t216 + 0.352e3 / 0.27e2 * t104 * t405 * t500 - 0.64e2 / 0.9e1 * t104 * t165 * t1208 - 0.32e2 / 0.9e1 * t104 * t165 * t1212 - 0.4e1 * t104 * t157 * t970 * t518 * t394 + 0.4e1 / 0.3e1 * t104 * t157 * t393 * t1233 * t172 + 0.4e1 / 0.3e1 * t104 * t157 * t1207 * t419 + 0.32e2 / 0.3e1 * t104 * t165 * t1203 + 0.16e2 / 0.3e1 * t104 * t157 * t2392 * t215 * t971 - 0.4e1 * t2915 * t2916 * t1319 * t419;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho3sigma[11] = t433 * t478 * t950 / 0.2e1 + 0.3e1 / 0.2e1 * t433 * t1160 * t377 + t433 * t2731 * t370 + 0.3e1 / 0.2e1 * t433 * t2793 * t146 + 0.3e1 / 0.10e2 * t184 * t204 * (-0.2e1 / 0.9e1 * t104 * t157 * t159 * (-0.140e3 / 0.27e2 * t33 * t208 * t982 * t66 - 0.364e3 / 0.9e1 * t33 * t955 * t168 + 0.1660e4 / 0.27e2 * t33 * t993 * t415 * sigma[2] - 0.488e3 / 0.9e1 * t33 * t1000 * t1004 * t409 + 0.160e3 / 0.9e1 * t33 / t59 / t991 / t575 * t2439 * t998) - 0.176e3 / 0.27e2 * t104 * t405 * t519 + 0.16e2 / 0.9e1 * t104 * t165 * t1234 - 0.32e2 / 0.9e1 * t25 * t489 * t395 - 0.4e1 / 0.3e1 * t25 * t205 * t972 + 0.4e1 / 0.3e1 * t104 * t1318 * t172 * t419 - 0.2464e4 / 0.243e3 * t25 * t26 * t955 * t70 - 0.176e3 / 0.27e2 * t25 * t1180 * t173 + 0.16e2 / 0.9e1 * t25 * t489 * t420 - 0.2e1 / 0.9e1 * t25 * t205 * t1009 + t2921) - t433 * t2657 * t1027 / 0.9e1 + t433 * t1125 * t1031 + 0.5e1 / 0.3e1 * t2768 + 0.5e1 * t2776 + 0.5e1 / 0.2e1 * t2783 + 0.3e1 / 0.2e1 * t2791 + t2727 - t2656 + 0.5e1 / 0.3e1 * t2708;

  t2937 = t2697 * t556 / 0.3e1;
  t2938 = t1135 * t1245;
  t2940 = t1134 * t1300;
  t2941 = t226 * t555;
  t2945 = t14 * t1299;
  t3003 = t467 * t467;
  t3012 = 0.32e2 / 0.27e2 * t104 * t113 * t1295 - 0.2e1 / 0.9e1 * t104 * t105 * t107 * (-0.7e1 / 0.9e1 * t33 * t536 * t273 * t38 + 0.7e1 / 0.9e1 * t33 * t540 * t257 * t116 - 0.11e2 * t33 * t1099 + 0.47e2 / 0.3e1 * t33 * t1105 * sigma[0] - 0.20e2 / 0.3e1 * t33 / t30 / t1527 * t1540 * t282) - 0.352e3 / 0.81e2 * t25 * t1056 * t197 - 0.128e3 / 0.27e2 * t104 * t98 * t266 * t1252 + 0.16e2 / 0.9e1 * t104 * t1251 * t467 * t120 + 0.8e1 / 0.9e1 * t104 * t1251 * t196 * t292 + 0.64e2 / 0.27e2 * t25 * t438 * t468 - 0.4e1 / 0.9e1 * t25 * t186 * t1110 - 0.4e1 / 0.3e1 * t104 * t105 * t1262 * t292 + 0.8e1 / 0.9e1 * t104 * t105 * t266 * t3003 + 0.8e1 / 0.9e1 * t104 * t105 * t448 * t1109;
  t3055 = -0.176e3 / 0.81e2 * t104 * t278 * t551 - 0.64e2 / 0.27e2 * t104 * t113 * t1275 + 0.8e1 / 0.9e1 * t104 * t105 * t266 * t1294 * t120 + 0.4e1 / 0.9e1 * t104 * t105 * t1274 * t292 - 0.8e1 / 0.3e1 * t104 * t2593 * t196 * t267 + 0.352e3 / 0.81e2 * t104 * t278 * t531 + 0.64e2 / 0.9e1 * t104 * t113 * t1263 - 0.128e3 / 0.27e2 * t104 * t113 * t1267 - 0.4e1 / 0.3e1 * t104 * t105 * t692 * t550 * t267 + 0.16e2 / 0.3e1 * t104 * t105 * t1493 * t530 * t267 - 0.16e2 / 0.3e1 * t2592 * t2593 * t1252 * t467;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[0] = t2937 + 0.5e1 / 0.3e1 * t2938 + t2940 + t433 * t2941 * t228 / 0.3e1 + t433 * t2945 * t87 + t433 * t1244 * t242 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t185 * (t3012 + t3055);

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[1] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[2] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[3] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[4] = 0.0e0;

  t3061 = t2697 * t587 / 0.3e1;
  t3062 = t1135 * t1305;
  t3064 = t301 * t586;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[5] = t3061 + 0.5e1 / 0.3e1 * t3062 + t433 * t3064 * t303 / 0.3e1 + t433 * t1304 * t311 / 0.2e1;

  t3073 = t1135 * t1308;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[6] = t2937 + 0.5e1 / 0.6e1 * t2938 + t2940 / 0.2e1 + 0.5e1 / 0.6e1 * t3073 + t433 * t2941 * t321 / 0.3e1 + t433 * t2945 * t142 / 0.2e1 + t1145 * t1244 * t7 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[7] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[8] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[9] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[10] = 0.0e0;

  t3085 = t1135 * t1312;
  t3093 = t1134 * t1367;
  t3095 = t53 * t1366;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[11] = t3061 + 0.5e1 / 0.6e1 * t3062 + 0.5e1 / 0.6e1 * t3085 + t433 * t3064 * t339 / 0.3e1 - t1145 * t1304 * t7 / 0.2e1 + t3093 / 0.2e1 + t433 * t3095 * t131 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[12] = t2937 + 0.5e1 / 0.3e1 * t3073 + t433 * t2941 * t361 / 0.3e1 + t433 * t1244 * t366 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[13] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[14] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[15] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[16] = 0.0e0;

  t3115 = t518 * t518;
  t3159 = 0.8e1 / 0.9e1 * t104 * t157 * t393 * t3115 + 0.8e1 / 0.9e1 * t104 * t157 * t499 * t1233 - 0.176e3 / 0.81e2 * t104 * t405 * t582 - 0.64e2 / 0.27e2 * t104 * t165 * t1342 + 0.8e1 / 0.9e1 * t104 * t157 * t393 * t1361 * t172 + 0.4e1 / 0.9e1 * t104 * t157 * t1341 * t419 - 0.4e1 / 0.9e1 * t25 * t205 * t1234 - 0.4e1 / 0.3e1 * t104 * t157 * t970 * t581 * t394 + 0.16e2 / 0.3e1 * t104 * t157 * t2392 * t561 * t394 - 0.16e2 / 0.3e1 * t2915 * t2916 * t1319 * t518 + 0.32e2 / 0.27e2 * t104 * t165 * t1362;
  t3219 = -0.2e1 / 0.9e1 * t104 * t157 * t159 * (-0.7e1 / 0.9e1 * t33 * t567 * t400 * t66 + 0.7e1 / 0.9e1 * t33 * t571 * t384 * t168 - 0.11e2 * t33 * t1223 + 0.47e2 / 0.3e1 * t33 * t1229 * sigma[2] - 0.20e2 / 0.3e1 * t33 / t59 / t2426 * t2439 * t409) - 0.352e3 / 0.81e2 * t25 * t1180 * t216 - 0.128e3 / 0.27e2 * t104 * t152 * t393 * t1319 + 0.16e2 / 0.9e1 * t104 * t1318 * t518 * t172 + 0.8e1 / 0.9e1 * t104 * t1318 * t215 * t419 + 0.64e2 / 0.27e2 * t25 * t489 * t519 - 0.8e1 / 0.3e1 * t104 * t2916 * t215 * t394 + 0.352e3 / 0.81e2 * t104 * t405 * t562 + 0.64e2 / 0.9e1 * t104 * t165 * t1330 - 0.128e3 / 0.27e2 * t104 * t165 * t1334 - 0.4e1 / 0.3e1 * t104 * t157 * t1329 * t419;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho2sigma2[17] = t3061 + 0.5e1 / 0.3e1 * t3085 + t3093 + t433 * t3064 * t370 / 0.3e1 + t433 * t3095 * t146 + t433 * t1304 * t377 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t204 * (t3159 + t3219);

  t3224 = t1134 * t1410;
  t3226 = t14 * t1409;
  t3266 = t196 * t550;
  t3312 = -0.32e2 / 0.9e1 * t25 * t438 * t531 - 0.4e1 * t104 * t2593 * t530 * t120 + 0.8e1 / 0.3e1 * t104 * t1251 * t196 * t467 + 0.16e2 / 0.9e1 * t25 * t438 * t551 + 0.4e1 / 0.3e1 * t104 * t1251 * t550 * t120 - 0.2e1 / 0.3e1 * t25 * t186 * t1295 + 0.32e2 / 0.9e1 * t104 * t113 * t1377 + 0.16e2 / 0.3e1 * t104 * t105 * t1493 * t1376 * t120 - 0.4e1 * t104 * t105 * t1262 * t467 - 0.32e2 / 0.9e1 * t104 * t113 * t1381 - 0.4e1 * t2592 * t2593 * t3266 * t120 + 0.4e1 / 0.3e1 * t104 * t105 * t1083 * t550 + 0.4e1 / 0.3e1 * t104 * t105 * t448 * t1294 + 0.16e2 / 0.27e2 * t104 * t113 * t1405 + 0.4e1 / 0.9e1 * t104 * t105 * t266 * t1404 * t120 - 0.2e1 / 0.9e1 * t104 * t105 * t107 * (-t33 * t1386 * t109 * t38 / 0.2e1 + t33 * t1391 * t98 * t116 / 0.2e1 + t33 * t540 * t462 * t288 / 0.6e1 - 0.7e1 / 0.2e1 * t33 * t1291 + 0.5e1 / 0.2e1 * t33 / t30 / t721 * t1540 * sigma[0]);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[0] = t3224 / 0.2e1 + t433 * t3226 * t87 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t185 * t3312;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[1] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[2] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[3] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[4] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[5] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[6] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[7] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[8] = 0.0e0;

  t3316 = t1134 * t1452;
  t3317 = t53 * t1451;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[9] = t433 * t3317 * t131 / 0.2e1 + t3316 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[10] = t433 * t3226 * t142 / 0.2e1 + t3224 / 0.2e1;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[11] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[12] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[13] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[14] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[15] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[16] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[17] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[18] = 0.0e0;

  t3364 = t215 * t581;
  t3410 = -0.32e2 / 0.9e1 * t25 * t489 * t562 - 0.4e1 * t104 * t2916 * t561 * t172 + 0.8e1 / 0.3e1 * t104 * t1318 * t215 * t518 + 0.16e2 / 0.9e1 * t25 * t489 * t582 + 0.4e1 / 0.3e1 * t104 * t1318 * t581 * t172 - 0.2e1 / 0.3e1 * t25 * t205 * t1362 + 0.32e2 / 0.9e1 * t104 * t165 * t1419 + 0.16e2 / 0.3e1 * t104 * t157 * t2392 * t1418 * t172 - 0.4e1 * t104 * t157 * t1329 * t518 - 0.32e2 / 0.9e1 * t104 * t165 * t1423 - 0.4e1 * t2915 * t2916 * t3364 * t172 + 0.4e1 / 0.3e1 * t104 * t157 * t1207 * t581 + 0.4e1 / 0.3e1 * t104 * t157 * t499 * t1361 + 0.16e2 / 0.27e2 * t104 * t165 * t1447 + 0.4e1 / 0.9e1 * t104 * t157 * t393 * t1446 * t172 - 0.2e1 / 0.9e1 * t104 * t157 * t159 * (-t33 * t1428 * t161 * t66 / 0.2e1 + t33 * t1433 * t152 * t168 / 0.2e1 + t33 * t571 * t513 * t415 / 0.6e1 - 0.7e1 / 0.2e1 * t33 * t1358 + 0.5e1 / 0.2e1 * t33 / t59 / t999 * t2439 * sigma[2]);
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rhosigma3[19] = t3316 / 0.2e1 + t433 * t3317 * t146 / 0.2e1 + 0.3e1 / 0.10e2 * t184 * t204 * t3410;

  t3423 = t530 * t530;
  t3432 = t550 * t550;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[0] = 0.3e1 / 0.10e2 * t184 * t185 * (-0.16e2 / 0.3e1 * t25 * t186 * t1377 + 0.16e2 / 0.3e1 * t104 * t1251 * t3266 - 0.8e1 / 0.9e1 * t25 * t186 * t1405 + 0.16e2 / 0.3e1 * t104 * t105 * t1493 * t3423 - 0.8e1 * t104 * t105 * t1262 * t550 + 0.4e1 / 0.3e1 * t104 * t105 * t266 * t3432 + 0.16e2 / 0.9e1 * t104 * t105 * t448 * t1404 - 0.2e1 / 0.9e1 * t104 * t105 * t107 * (-0.15e2 / 0.16e2 * t33 / t34 / t720 * t36 * t38 + 0.15e2 / 0.16e2 * t33 / t720 * t32 * t116 + 0.5e1 / 0.16e2 * t33 * t1391 * t546 * t288 + 0.3e1 / 0.16e2 * t33 * t540 * t1400 * t726 - 0.15e2 / 0.16e2 * t33 / t30 / t1103 * t1540));

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[1] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[2] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[3] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[4] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[5] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[6] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[7] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[8] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[9] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[10] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[11] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[12] = 0.0e0;

  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[13] = 0.0e0;

  t3482 = t561 * t561;
  t3491 = t581 * t581;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4sigma4[14] = 0.3e1 / 0.10e2 * t184 * t204 * (-0.16e2 / 0.3e1 * t25 * t205 * t1419 + 0.16e2 / 0.3e1 * t104 * t1318 * t3364 - 0.8e1 / 0.9e1 * t25 * t205 * t1447 + 0.16e2 / 0.3e1 * t104 * t157 * t2392 * t3482 - 0.8e1 * t104 * t157 * t1329 * t581 + 0.4e1 / 0.3e1 * t104 * t157 * t393 * t3491 + 0.16e2 / 0.9e1 * t104 * t157 * t499 * t1446 - 0.2e1 / 0.9e1 * t104 * t157 * t159 * (-0.15e2 / 0.16e2 * t33 / t62 / t998 * t64 * t66 + 0.15e2 / 0.16e2 * t33 / t998 * t61 * t168 + 0.5e1 / 0.16e2 * t33 * t1433 * t577 * t415 + 0.3e1 / 0.16e2 * t33 * t571 * t1442 * t1004 - 0.15e2 / 0.16e2 * t33 / t59 / t1227 * t2439));

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}

